/* indicator-menu.c generated by valac 0.56.19, the Vala compiler
 * generated from indicator-menu.vala, do not modify */

/*
 * Copyright 2014-2017 Canonical Ltd.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Authors: William Hua <william.hua@canonical.com>
 */

#include <gio/gio.h>
#include <glib-object.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <ibus.h>
#include <glib/gi18n-lib.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define INDICATOR_KEYBOARD_TYPE_INDICATOR_MENU (indicator_keyboard_indicator_menu_get_type ())
#define INDICATOR_KEYBOARD_INDICATOR_MENU(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), INDICATOR_KEYBOARD_TYPE_INDICATOR_MENU, IndicatorKeyboardIndicatorMenu))
#define INDICATOR_KEYBOARD_INDICATOR_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), INDICATOR_KEYBOARD_TYPE_INDICATOR_MENU, IndicatorKeyboardIndicatorMenuClass))
#define INDICATOR_KEYBOARD_IS_INDICATOR_MENU(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), INDICATOR_KEYBOARD_TYPE_INDICATOR_MENU))
#define INDICATOR_KEYBOARD_IS_INDICATOR_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), INDICATOR_KEYBOARD_TYPE_INDICATOR_MENU))
#define INDICATOR_KEYBOARD_INDICATOR_MENU_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), INDICATOR_KEYBOARD_TYPE_INDICATOR_MENU, IndicatorKeyboardIndicatorMenuClass))

typedef struct _IndicatorKeyboardIndicatorMenu IndicatorKeyboardIndicatorMenu;
typedef struct _IndicatorKeyboardIndicatorMenuClass IndicatorKeyboardIndicatorMenuClass;
typedef struct _IndicatorKeyboardIndicatorMenuPrivate IndicatorKeyboardIndicatorMenuPrivate;
typedef enum  {
	INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_NONE = 0,
	INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_DCONF = 1 << 0,
	INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_XKB = 1 << 1,
	INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_IBUS = 1 << 2,
	INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_SETTINGS = 1 << 3,
	INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_OSK_SWITCH = 1 << 4
} IndicatorKeyboardIndicatorMenuOptions;

#define INDICATOR_KEYBOARD_INDICATOR_MENU_TYPE_OPTIONS (indicator_keyboard_indicator_menu_options_get_type ())

#define INDICATOR_KEYBOARD_TYPE_IBUS_MENU (indicator_keyboard_ibus_menu_get_type ())
#define INDICATOR_KEYBOARD_IBUS_MENU(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), INDICATOR_KEYBOARD_TYPE_IBUS_MENU, IndicatorKeyboardIBusMenu))
#define INDICATOR_KEYBOARD_IBUS_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), INDICATOR_KEYBOARD_TYPE_IBUS_MENU, IndicatorKeyboardIBusMenuClass))
#define INDICATOR_KEYBOARD_IS_IBUS_MENU(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), INDICATOR_KEYBOARD_TYPE_IBUS_MENU))
#define INDICATOR_KEYBOARD_IS_IBUS_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), INDICATOR_KEYBOARD_TYPE_IBUS_MENU))
#define INDICATOR_KEYBOARD_IBUS_MENU_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), INDICATOR_KEYBOARD_TYPE_IBUS_MENU, IndicatorKeyboardIBusMenuClass))

typedef struct _IndicatorKeyboardIBusMenu IndicatorKeyboardIBusMenu;
typedef struct _IndicatorKeyboardIBusMenuClass IndicatorKeyboardIBusMenuClass;
enum  {
	INDICATOR_KEYBOARD_INDICATOR_MENU_0_PROPERTY,
	INDICATOR_KEYBOARD_INDICATOR_MENU_NUM_PROPERTIES
};
static GParamSpec* indicator_keyboard_indicator_menu_properties[INDICATOR_KEYBOARD_INDICATOR_MENU_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define INDICATOR_KEYBOARD_TYPE_SOURCE (indicator_keyboard_source_get_type ())
#define INDICATOR_KEYBOARD_SOURCE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), INDICATOR_KEYBOARD_TYPE_SOURCE, IndicatorKeyboardSource))
#define INDICATOR_KEYBOARD_SOURCE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), INDICATOR_KEYBOARD_TYPE_SOURCE, IndicatorKeyboardSourceClass))
#define INDICATOR_KEYBOARD_IS_SOURCE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), INDICATOR_KEYBOARD_TYPE_SOURCE))
#define INDICATOR_KEYBOARD_IS_SOURCE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), INDICATOR_KEYBOARD_TYPE_SOURCE))
#define INDICATOR_KEYBOARD_SOURCE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), INDICATOR_KEYBOARD_TYPE_SOURCE, IndicatorKeyboardSourceClass))

typedef struct _IndicatorKeyboardSource IndicatorKeyboardSource;
typedef struct _IndicatorKeyboardSourceClass IndicatorKeyboardSourceClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_hash_table_unref0(var) ((var == NULL) ? NULL : (var = (g_hash_table_unref (var), NULL)))
enum  {
	INDICATOR_KEYBOARD_INDICATOR_MENU_ACTIVATE_SIGNAL,
	INDICATOR_KEYBOARD_INDICATOR_MENU_NUM_SIGNALS
};
static guint indicator_keyboard_indicator_menu_signals[INDICATOR_KEYBOARD_INDICATOR_MENU_NUM_SIGNALS] = {0};

struct _IndicatorKeyboardIndicatorMenu {
	GMenuModel parent_instance;
	IndicatorKeyboardIndicatorMenuPrivate * priv;
};

struct _IndicatorKeyboardIndicatorMenuClass {
	GMenuModelClass parent_class;
};

struct _IndicatorKeyboardIndicatorMenuPrivate {
	IndicatorKeyboardIndicatorMenuOptions options;
	GMenu* indicator_menu;
	GMenu* sources_section;
	GMenu* osk_section;
	IndicatorKeyboardIBusMenu* properties_section;
};

static gint IndicatorKeyboardIndicatorMenu_private_offset;
static gpointer indicator_keyboard_indicator_menu_parent_class = NULL;

VALA_EXTERN GType indicator_keyboard_indicator_menu_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (IndicatorKeyboardIndicatorMenu, g_object_unref)
VALA_EXTERN GType indicator_keyboard_indicator_menu_options_get_type (void) G_GNUC_CONST ;
VALA_EXTERN GType indicator_keyboard_ibus_menu_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (IndicatorKeyboardIBusMenu, g_object_unref)
VALA_EXTERN IndicatorKeyboardIndicatorMenu* indicator_keyboard_indicator_menu_new (GActionMap* action_map,
                                                                       IndicatorKeyboardIndicatorMenuOptions options);
VALA_EXTERN IndicatorKeyboardIndicatorMenu* indicator_keyboard_indicator_menu_construct (GType object_type,
                                                                             GActionMap* action_map,
                                                                             IndicatorKeyboardIndicatorMenuOptions options);
VALA_EXTERN IndicatorKeyboardIBusMenu* indicator_keyboard_ibus_menu_new (GActionMap* action_map,
                                                             IBusPropList* properties);
VALA_EXTERN IndicatorKeyboardIBusMenu* indicator_keyboard_ibus_menu_construct (GType object_type,
                                                                   GActionMap* action_map,
                                                                   IBusPropList* properties);
static void ____lambda10_ (IndicatorKeyboardIndicatorMenu* self,
                    IBusProperty* property,
                    IBusPropState state);
static void _____lambda10__indicator_keyboard_ibus_menu_activate (IndicatorKeyboardIBusMenu* _sender,
                                                           IBusProperty* property,
                                                           IBusPropState state,
                                                           gpointer self);
VALA_EXTERN void indicator_keyboard_indicator_menu_rebuild_osk_section (IndicatorKeyboardIndicatorMenu* self,
                                                            gboolean enable);
VALA_EXTERN GType indicator_keyboard_source_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (IndicatorKeyboardSource, g_object_unref)
VALA_EXTERN void indicator_keyboard_indicator_menu_set_sources (IndicatorKeyboardIndicatorMenu* self,
                                                    IndicatorKeyboardSource** sources,
                                                    gint sources_length1);
VALA_EXTERN gboolean indicator_keyboard_source_get_is_xkb (IndicatorKeyboardSource* self);
VALA_EXTERN gboolean indicator_keyboard_source_get_is_ibus (IndicatorKeyboardSource* self);
VALA_EXTERN const gchar* indicator_keyboard_source_get_name (IndicatorKeyboardSource* self);
VALA_EXTERN GIcon* indicator_keyboard_source_get_icon (IndicatorKeyboardSource* self);
VALA_EXTERN void indicator_keyboard_indicator_menu_set_properties (IndicatorKeyboardIndicatorMenu* self,
                                                       IBusPropList* properties);
VALA_EXTERN void indicator_keyboard_ibus_menu_set_properties (IndicatorKeyboardIBusMenu* self,
                                                  IBusPropList* properties);
VALA_EXTERN void indicator_keyboard_indicator_menu_update_property (IndicatorKeyboardIndicatorMenu* self,
                                                        IBusProperty* property);
VALA_EXTERN void indicator_keyboard_ibus_menu_update_property (IndicatorKeyboardIBusMenu* self,
                                                   IBusProperty* property);
static gboolean indicator_keyboard_indicator_menu_real_is_mutable (GMenuModel* base);
static gint indicator_keyboard_indicator_menu_real_get_n_items (GMenuModel* base);
static void indicator_keyboard_indicator_menu_real_get_item_attributes (GMenuModel* base,
                                                                 gint item_index,
                                                                 GHashTable** attributes);
static void indicator_keyboard_indicator_menu_real_get_item_links (GMenuModel* base,
                                                            gint item_index,
                                                            GHashTable** links);
static GVariant* indicator_keyboard_indicator_menu_real_get_item_attribute_value (GMenuModel* base,
                                                                           gint item_index,
                                                                           const gchar* attribute,
                                                                           const GVariantType* expected_type);
static GMenuModel* indicator_keyboard_indicator_menu_real_get_item_link (GMenuModel* base,
                                                                  gint item_index,
                                                                  const gchar* link);
static GMenuAttributeIter* indicator_keyboard_indicator_menu_real_iterate_item_attributes (GMenuModel* base,
                                                                                    gint item_index);
static GMenuLinkIter* indicator_keyboard_indicator_menu_real_iterate_item_links (GMenuModel* base,
                                                                          gint item_index);
static void g_cclosure_user_marshal_VOID__OBJECT_ENUM (GClosure * closure,
                                                GValue * return_value,
                                                guint n_param_values,
                                                const GValue * param_values,
                                                gpointer invocation_hint,
                                                gpointer marshal_data);
static void indicator_keyboard_indicator_menu_finalize (GObject * obj);
static GType indicator_keyboard_indicator_menu_get_type_once (void);

static inline gpointer
indicator_keyboard_indicator_menu_get_instance_private (IndicatorKeyboardIndicatorMenu* self)
{
	return G_STRUCT_MEMBER_P (self, IndicatorKeyboardIndicatorMenu_private_offset);
}

static GType
indicator_keyboard_indicator_menu_options_get_type_once (void)
{
	static const GEnumValue values[] = {{INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_NONE, "INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_NONE", "none"}, {INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_DCONF, "INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_DCONF", "dconf"}, {INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_XKB, "INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_XKB", "xkb"}, {INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_IBUS, "INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_IBUS", "ibus"}, {INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_SETTINGS, "INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_SETTINGS", "settings"}, {INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_OSK_SWITCH, "INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_OSK_SWITCH", "osk-switch"}, {0, NULL, NULL}};
	GType indicator_keyboard_indicator_menu_options_type_id;
	indicator_keyboard_indicator_menu_options_type_id = g_enum_register_static ("IndicatorKeyboardIndicatorMenuOptions", values);
	return indicator_keyboard_indicator_menu_options_type_id;
}

GType
indicator_keyboard_indicator_menu_options_get_type (void)
{
	static volatile gsize indicator_keyboard_indicator_menu_options_type_id__once = 0;
	if (g_once_init_enter (&indicator_keyboard_indicator_menu_options_type_id__once)) {
		GType indicator_keyboard_indicator_menu_options_type_id;
		indicator_keyboard_indicator_menu_options_type_id = indicator_keyboard_indicator_menu_options_get_type_once ();
		g_once_init_leave (&indicator_keyboard_indicator_menu_options_type_id__once, indicator_keyboard_indicator_menu_options_type_id);
	}
	return indicator_keyboard_indicator_menu_options_type_id__once;
}

static void
____lambda10_ (IndicatorKeyboardIndicatorMenu* self,
               IBusProperty* property,
               IBusPropState state)
{
	g_return_if_fail (property != NULL);
	g_signal_emit (self, indicator_keyboard_indicator_menu_signals[INDICATOR_KEYBOARD_INDICATOR_MENU_ACTIVATE_SIGNAL], 0, property, state);
}

static void
_____lambda10__indicator_keyboard_ibus_menu_activate (IndicatorKeyboardIBusMenu* _sender,
                                                      IBusProperty* property,
                                                      IBusPropState state,
                                                      gpointer self)
{
	____lambda10_ ((IndicatorKeyboardIndicatorMenu*) self, property, state);
}

IndicatorKeyboardIndicatorMenu*
indicator_keyboard_indicator_menu_construct (GType object_type,
                                             GActionMap* action_map,
                                             IndicatorKeyboardIndicatorMenuOptions options)
{
	IndicatorKeyboardIndicatorMenu * self = NULL;
	GMenu* _tmp0_;
	GMenu* _tmp1_;
	GMenu* _tmp2_;
	self = (IndicatorKeyboardIndicatorMenu*) g_object_new (object_type, NULL);
	self->priv->options = options;
	_tmp0_ = g_menu_new ();
	_g_object_unref0 (self->priv->indicator_menu);
	self->priv->indicator_menu = _tmp0_;
	_tmp1_ = g_menu_new ();
	_g_object_unref0 (self->priv->sources_section);
	self->priv->sources_section = _tmp1_;
	_tmp2_ = g_menu_new ();
	_g_object_unref0 (self->priv->osk_section);
	self->priv->osk_section = _tmp2_;
	if ((options & (~INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_DCONF)) != INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_NONE) {
		GMenu* submenu = NULL;
		GMenu* _tmp3_;
		GMenu* _tmp4_;
		GMenu* _tmp5_;
		GMenu* _tmp10_;
		GMenu* _tmp11_;
		GMenuItem* indicator = NULL;
		GMenu* _tmp18_;
		GMenuItem* _tmp19_;
		GMenuItem* _tmp20_;
		GMenuItem* _tmp21_;
		GMenu* _tmp26_;
		GMenuItem* _tmp27_;
		_tmp3_ = g_menu_new ();
		submenu = _tmp3_;
		_tmp4_ = submenu;
		_tmp5_ = self->priv->sources_section;
		g_menu_append_section (_tmp4_, NULL, (GMenuModel*) _tmp5_);
		if ((options & INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_IBUS) == INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_IBUS) {
			IndicatorKeyboardIBusMenu* _tmp6_;
			IndicatorKeyboardIBusMenu* _tmp7_;
			GMenu* _tmp8_;
			IndicatorKeyboardIBusMenu* _tmp9_;
			_tmp6_ = indicator_keyboard_ibus_menu_new (action_map, NULL);
			_g_object_unref0 (self->priv->properties_section);
			self->priv->properties_section = _tmp6_;
			_tmp7_ = self->priv->properties_section;
			g_signal_connect_object (_tmp7_, "activate", (GCallback) _____lambda10__indicator_keyboard_ibus_menu_activate, self, 0);
			_tmp8_ = submenu;
			_tmp9_ = self->priv->properties_section;
			g_menu_append_section (_tmp8_, NULL, (GMenuModel*) _tmp9_);
		}
		if ((options & INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_OSK_SWITCH) == INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_OSK_SWITCH) {
			indicator_keyboard_indicator_menu_rebuild_osk_section (self, TRUE);
		}
		_tmp10_ = submenu;
		_tmp11_ = self->priv->osk_section;
		g_menu_append_section (_tmp10_, NULL, (GMenuModel*) _tmp11_);
		if ((options & INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_SETTINGS) == INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_SETTINGS) {
			GMenu* settings_section = NULL;
			GMenu* _tmp12_;
			GMenu* _tmp13_;
			GMenu* _tmp14_;
			GMenu* _tmp15_;
			GMenu* _tmp16_;
			GMenu* _tmp17_;
			_tmp12_ = g_menu_new ();
			settings_section = _tmp12_;
			_tmp13_ = settings_section;
			g_menu_append (_tmp13_, _ ("Character Map"), "indicator.map");
			_tmp14_ = settings_section;
			g_menu_append (_tmp14_, _ ("Keyboard Layout Chart"), "indicator.chart");
			_tmp15_ = settings_section;
			g_menu_append (_tmp15_, _ ("Text Entry Settings..."), "indicator.settings");
			_tmp16_ = submenu;
			_tmp17_ = settings_section;
			g_menu_append_section (_tmp16_, NULL, (GMenuModel*) _tmp17_);
			_g_object_unref0 (settings_section);
		}
		_tmp18_ = submenu;
		_tmp19_ = g_menu_item_new_submenu (NULL, (GMenuModel*) _tmp18_);
		indicator = _tmp19_;
		_tmp20_ = indicator;
		g_menu_item_set_detailed_action (_tmp20_, "indicator.indicator");
		_tmp21_ = indicator;
		g_menu_item_set_attribute (_tmp21_, "x-canonical-type", "s", "com.canonical.indicator.root", NULL);
		if ((options & INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_DCONF) == INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_DCONF) {
			GMenuItem* _tmp22_;
			GMenuItem* _tmp23_;
			_tmp22_ = indicator;
			g_menu_item_set_attribute (_tmp22_, "x-canonical-secondary-action", "s", "indicator.next", NULL);
			_tmp23_ = indicator;
			g_menu_item_set_attribute (_tmp23_, "x-canonical-scroll-action", "s", "indicator.scroll", NULL);
		} else {
			GMenuItem* _tmp24_;
			GMenuItem* _tmp25_;
			_tmp24_ = indicator;
			g_menu_item_set_attribute (_tmp24_, "x-canonical-secondary-action", "s", "indicator.locked_next", NULL);
			_tmp25_ = indicator;
			g_menu_item_set_attribute (_tmp25_, "x-canonical-scroll-action", "s", "indicator.locked_scroll", NULL);
		}
		_tmp26_ = self->priv->indicator_menu;
		_tmp27_ = indicator;
		g_menu_append_item (_tmp26_, _tmp27_);
		_g_object_unref0 (indicator);
		_g_object_unref0 (submenu);
	}
	return self;
}

IndicatorKeyboardIndicatorMenu*
indicator_keyboard_indicator_menu_new (GActionMap* action_map,
                                       IndicatorKeyboardIndicatorMenuOptions options)
{
	return indicator_keyboard_indicator_menu_construct (INDICATOR_KEYBOARD_TYPE_INDICATOR_MENU, action_map, options);
}

void
indicator_keyboard_indicator_menu_set_sources (IndicatorKeyboardIndicatorMenu* self,
                                               IndicatorKeyboardSource** sources,
                                               gint sources_length1)
{
	GMenu* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->sources_section;
	g_menu_remove_all (_tmp0_);
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp1_ = FALSE;
			_tmp1_ = TRUE;
			while (TRUE) {
				gboolean _tmp3_ = FALSE;
				gboolean _tmp4_ = FALSE;
				IndicatorKeyboardSource* _tmp5_;
				gboolean _tmp6_;
				gboolean _tmp7_;
				gboolean visible = FALSE;
				if (!_tmp1_) {
					gint _tmp2_;
					_tmp2_ = i;
					i = _tmp2_ + 1;
				}
				_tmp1_ = FALSE;
				if (!(i < sources_length1)) {
					break;
				}
				_tmp5_ = sources[i];
				_tmp6_ = indicator_keyboard_source_get_is_xkb (_tmp5_);
				_tmp7_ = _tmp6_;
				if (_tmp7_) {
					_tmp4_ = (self->priv->options & INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_XKB) == INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_XKB;
				} else {
					_tmp4_ = FALSE;
				}
				if (_tmp4_) {
					_tmp3_ = TRUE;
				} else {
					gboolean _tmp8_ = FALSE;
					IndicatorKeyboardSource* _tmp9_;
					gboolean _tmp10_;
					gboolean _tmp11_;
					_tmp9_ = sources[i];
					_tmp10_ = indicator_keyboard_source_get_is_ibus (_tmp9_);
					_tmp11_ = _tmp10_;
					if (_tmp11_) {
						_tmp8_ = (self->priv->options & INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_IBUS) == INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_IBUS;
					} else {
						_tmp8_ = FALSE;
					}
					_tmp3_ = _tmp8_;
				}
				visible = _tmp3_;
				if (visible) {
					gchar* action = NULL;
					GMenuItem* item = NULL;
					IndicatorKeyboardSource* _tmp14_;
					const gchar* _tmp15_;
					const gchar* _tmp16_;
					const gchar* _tmp17_;
					GMenuItem* _tmp18_;
					GMenuItem* _tmp19_;
					IndicatorKeyboardSource* _tmp20_;
					GIcon* _tmp21_;
					GIcon* _tmp22_;
					GMenu* _tmp27_;
					GMenuItem* _tmp28_;
					if ((self->priv->options & INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_DCONF) == INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_DCONF) {
						gchar* _tmp12_;
						_tmp12_ = g_strdup ("indicator.current");
						_g_free0 (action);
						action = _tmp12_;
					} else {
						gchar* _tmp13_;
						_tmp13_ = g_strdup ("indicator.active");
						_g_free0 (action);
						action = _tmp13_;
					}
					_tmp14_ = sources[i];
					_tmp15_ = indicator_keyboard_source_get_name (_tmp14_);
					_tmp16_ = _tmp15_;
					_tmp17_ = action;
					_tmp18_ = g_menu_item_new (_tmp16_, _tmp17_);
					item = _tmp18_;
					_tmp19_ = item;
					g_menu_item_set_attribute (_tmp19_, G_MENU_ATTRIBUTE_TARGET, "u", i, NULL);
					_tmp20_ = sources[i];
					_tmp21_ = indicator_keyboard_source_get_icon (_tmp20_);
					_tmp22_ = _tmp21_;
					if (_tmp22_ != NULL) {
						GMenuItem* _tmp23_;
						IndicatorKeyboardSource* _tmp24_;
						GIcon* _tmp25_;
						GIcon* _tmp26_;
						_tmp23_ = item;
						_tmp24_ = sources[i];
						_tmp25_ = indicator_keyboard_source_get_icon (_tmp24_);
						_tmp26_ = _tmp25_;
						g_menu_item_set_icon (_tmp23_, G_TYPE_CHECK_INSTANCE_CAST (_tmp26_, g_icon_get_type (), GIcon));
					}
					_tmp27_ = self->priv->sources_section;
					_tmp28_ = item;
					g_menu_append_item (_tmp27_, _tmp28_);
					_g_object_unref0 (item);
					_g_free0 (action);
				}
			}
		}
	}
}

void
indicator_keyboard_indicator_menu_rebuild_osk_section (IndicatorKeyboardIndicatorMenu* self,
                                                       gboolean enable)
{
	GMenu* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->osk_section;
	g_menu_remove_all (_tmp0_);
	if (enable) {
		GMenuItem* osk_item = NULL;
		GMenuItem* _tmp1_;
		GMenuItem* _tmp2_;
		GMenu* _tmp3_;
		GMenuItem* _tmp4_;
		_tmp1_ = g_menu_item_new (_ ("On-screen keyboard"), "indicator.always-show-osk");
		osk_item = _tmp1_;
		_tmp2_ = osk_item;
		g_menu_item_set_attribute (_tmp2_, "x-canonical-type", "s", "com.canonical.indicator.switch", NULL);
		_tmp3_ = self->priv->osk_section;
		_tmp4_ = osk_item;
		g_menu_append_item (_tmp3_, _tmp4_);
		_g_object_unref0 (osk_item);
	}
}

void
indicator_keyboard_indicator_menu_set_properties (IndicatorKeyboardIndicatorMenu* self,
                                                  IBusPropList* properties)
{
	g_return_if_fail (self != NULL);
	g_return_if_fail (properties != NULL);
	if ((self->priv->options & INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_IBUS) == INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_IBUS) {
		IndicatorKeyboardIBusMenu* _tmp0_;
		_tmp0_ = self->priv->properties_section;
		indicator_keyboard_ibus_menu_set_properties (_tmp0_, properties);
	}
}

void
indicator_keyboard_indicator_menu_update_property (IndicatorKeyboardIndicatorMenu* self,
                                                   IBusProperty* property)
{
	g_return_if_fail (self != NULL);
	g_return_if_fail (property != NULL);
	if ((self->priv->options & INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_IBUS) == INDICATOR_KEYBOARD_INDICATOR_MENU_OPTIONS_IBUS) {
		IndicatorKeyboardIBusMenu* _tmp0_;
		_tmp0_ = self->priv->properties_section;
		indicator_keyboard_ibus_menu_update_property (_tmp0_, property);
	}
}

static gboolean
indicator_keyboard_indicator_menu_real_is_mutable (GMenuModel* base)
{
	IndicatorKeyboardIndicatorMenu * self;
	GMenu* _tmp0_;
	gboolean result;
	self = (IndicatorKeyboardIndicatorMenu*) base;
	_tmp0_ = self->priv->indicator_menu;
	result = g_menu_model_is_mutable ((GMenuModel*) _tmp0_);
	return result;
}

static gint
indicator_keyboard_indicator_menu_real_get_n_items (GMenuModel* base)
{
	IndicatorKeyboardIndicatorMenu * self;
	GMenu* _tmp0_;
	gint result;
	self = (IndicatorKeyboardIndicatorMenu*) base;
	_tmp0_ = self->priv->indicator_menu;
	result = g_menu_model_get_n_items ((GMenuModel*) _tmp0_);
	return result;
}

static void
indicator_keyboard_indicator_menu_real_get_item_attributes (GMenuModel* base,
                                                            gint item_index,
                                                            GHashTable** attributes)
{
	IndicatorKeyboardIndicatorMenu * self;
	GHashTable* _vala_attributes = NULL;
	GMenu* _tmp0_;
	GHashTable* _tmp1_ = NULL;
	self = (IndicatorKeyboardIndicatorMenu*) base;
	_tmp0_ = self->priv->indicator_menu;
	G_TYPE_INSTANCE_GET_CLASS ((GMenuModel*) _tmp0_, g_menu_model_get_type (), GMenuModelClass)->get_item_attributes ((GMenuModel*) _tmp0_, item_index, (GHashTable**) (&_tmp1_));
	_g_hash_table_unref0 (_vala_attributes);
	_vala_attributes = _tmp1_;
	if (attributes) {
		*attributes = _vala_attributes;
	} else {
		_g_hash_table_unref0 (_vala_attributes);
	}
}

static void
indicator_keyboard_indicator_menu_real_get_item_links (GMenuModel* base,
                                                       gint item_index,
                                                       GHashTable** links)
{
	IndicatorKeyboardIndicatorMenu * self;
	GHashTable* _vala_links = NULL;
	GMenu* _tmp0_;
	GHashTable* _tmp1_ = NULL;
	self = (IndicatorKeyboardIndicatorMenu*) base;
	_tmp0_ = self->priv->indicator_menu;
	G_TYPE_INSTANCE_GET_CLASS ((GMenuModel*) _tmp0_, g_menu_model_get_type (), GMenuModelClass)->get_item_links ((GMenuModel*) _tmp0_, item_index, &_tmp1_);
	_g_hash_table_unref0 (_vala_links);
	_vala_links = _tmp1_;
	if (links) {
		*links = _vala_links;
	} else {
		_g_hash_table_unref0 (_vala_links);
	}
}

static GVariant*
indicator_keyboard_indicator_menu_real_get_item_attribute_value (GMenuModel* base,
                                                                 gint item_index,
                                                                 const gchar* attribute,
                                                                 const GVariantType* expected_type)
{
	IndicatorKeyboardIndicatorMenu * self;
	GMenu* _tmp0_;
	GVariant* _tmp1_;
	GVariant* result;
	self = (IndicatorKeyboardIndicatorMenu*) base;
	g_return_val_if_fail (attribute != NULL, NULL);
	_tmp0_ = self->priv->indicator_menu;
	_tmp1_ = g_menu_model_get_item_attribute_value ((GMenuModel*) _tmp0_, item_index, attribute, expected_type);
	result = _tmp1_;
	return result;
}

static GMenuModel*
indicator_keyboard_indicator_menu_real_get_item_link (GMenuModel* base,
                                                      gint item_index,
                                                      const gchar* link)
{
	IndicatorKeyboardIndicatorMenu * self;
	GMenu* _tmp0_;
	GMenuModel* _tmp1_;
	GMenuModel* result;
	self = (IndicatorKeyboardIndicatorMenu*) base;
	g_return_val_if_fail (link != NULL, NULL);
	_tmp0_ = self->priv->indicator_menu;
	_tmp1_ = g_menu_model_get_item_link ((GMenuModel*) _tmp0_, item_index, link);
	result = _tmp1_;
	return result;
}

static GMenuAttributeIter*
indicator_keyboard_indicator_menu_real_iterate_item_attributes (GMenuModel* base,
                                                                gint item_index)
{
	IndicatorKeyboardIndicatorMenu * self;
	GMenu* _tmp0_;
	GMenuAttributeIter* _tmp1_;
	GMenuAttributeIter* result;
	self = (IndicatorKeyboardIndicatorMenu*) base;
	_tmp0_ = self->priv->indicator_menu;
	_tmp1_ = g_menu_model_iterate_item_attributes ((GMenuModel*) _tmp0_, item_index);
	result = _tmp1_;
	return result;
}

static GMenuLinkIter*
indicator_keyboard_indicator_menu_real_iterate_item_links (GMenuModel* base,
                                                           gint item_index)
{
	IndicatorKeyboardIndicatorMenu * self;
	GMenu* _tmp0_;
	GMenuLinkIter* _tmp1_;
	GMenuLinkIter* result;
	self = (IndicatorKeyboardIndicatorMenu*) base;
	_tmp0_ = self->priv->indicator_menu;
	_tmp1_ = g_menu_model_iterate_item_links ((GMenuModel*) _tmp0_, item_index);
	result = _tmp1_;
	return result;
}

static void
g_cclosure_user_marshal_VOID__OBJECT_ENUM (GClosure * closure,
                                           GValue * return_value,
                                           guint n_param_values,
                                           const GValue * param_values,
                                           gpointer invocation_hint,
                                           gpointer marshal_data)
{
	typedef void (*GMarshalFunc_VOID__OBJECT_ENUM) (gpointer data1, gpointer arg_1, gint arg_2, gpointer data2);
	register GMarshalFunc_VOID__OBJECT_ENUM callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	cc = (GCClosure *) closure;
	g_return_if_fail (n_param_values == 3);
	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = param_values->data[0].v_pointer;
	} else {
		data1 = param_values->data[0].v_pointer;
		data2 = closure->data;
	}
	callback = (GMarshalFunc_VOID__OBJECT_ENUM) (marshal_data ? marshal_data : cc->callback);
	callback (data1, g_value_get_object (param_values + 1), g_value_get_enum (param_values + 2), data2);
}

static void
indicator_keyboard_indicator_menu_class_init (IndicatorKeyboardIndicatorMenuClass * klass,
                                              gpointer klass_data)
{
	indicator_keyboard_indicator_menu_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &IndicatorKeyboardIndicatorMenu_private_offset);
	((GMenuModelClass *) klass)->is_mutable = (gboolean (*) (GMenuModel*)) indicator_keyboard_indicator_menu_real_is_mutable;
	((GMenuModelClass *) klass)->get_n_items = (gint (*) (GMenuModel*)) indicator_keyboard_indicator_menu_real_get_n_items;
	((GMenuModelClass *) klass)->get_item_attributes = (void (*) (GMenuModel*, gint, GHashTable**)) indicator_keyboard_indicator_menu_real_get_item_attributes;
	((GMenuModelClass *) klass)->get_item_links = (void (*) (GMenuModel*, gint, GHashTable**)) indicator_keyboard_indicator_menu_real_get_item_links;
	((GMenuModelClass *) klass)->get_item_attribute_value = (GVariant* (*) (GMenuModel*, gint, const gchar*, const GVariantType*)) indicator_keyboard_indicator_menu_real_get_item_attribute_value;
	((GMenuModelClass *) klass)->get_item_link = (GMenuModel* (*) (GMenuModel*, gint, const gchar*)) indicator_keyboard_indicator_menu_real_get_item_link;
	((GMenuModelClass *) klass)->iterate_item_attributes = (GMenuAttributeIter* (*) (GMenuModel*, gint)) indicator_keyboard_indicator_menu_real_iterate_item_attributes;
	((GMenuModelClass *) klass)->iterate_item_links = (GMenuLinkIter* (*) (GMenuModel*, gint)) indicator_keyboard_indicator_menu_real_iterate_item_links;
	G_OBJECT_CLASS (klass)->finalize = indicator_keyboard_indicator_menu_finalize;
	indicator_keyboard_indicator_menu_signals[INDICATOR_KEYBOARD_INDICATOR_MENU_ACTIVATE_SIGNAL] = g_signal_new ("activate", INDICATOR_KEYBOARD_TYPE_INDICATOR_MENU, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__OBJECT_ENUM, G_TYPE_NONE, 2, ibus_property_get_type (), ibus_prop_state_get_type ());
}

static void
indicator_keyboard_indicator_menu_instance_init (IndicatorKeyboardIndicatorMenu * self,
                                                 gpointer klass)
{
	self->priv = indicator_keyboard_indicator_menu_get_instance_private (self);
}

static void
indicator_keyboard_indicator_menu_finalize (GObject * obj)
{
	IndicatorKeyboardIndicatorMenu * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, INDICATOR_KEYBOARD_TYPE_INDICATOR_MENU, IndicatorKeyboardIndicatorMenu);
	_g_object_unref0 (self->priv->indicator_menu);
	_g_object_unref0 (self->priv->sources_section);
	_g_object_unref0 (self->priv->osk_section);
	_g_object_unref0 (self->priv->properties_section);
	G_OBJECT_CLASS (indicator_keyboard_indicator_menu_parent_class)->finalize (obj);
}

static GType
indicator_keyboard_indicator_menu_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (IndicatorKeyboardIndicatorMenuClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) indicator_keyboard_indicator_menu_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (IndicatorKeyboardIndicatorMenu), 0, (GInstanceInitFunc) indicator_keyboard_indicator_menu_instance_init, NULL };
	GType indicator_keyboard_indicator_menu_type_id;
	indicator_keyboard_indicator_menu_type_id = g_type_register_static (g_menu_model_get_type (), "IndicatorKeyboardIndicatorMenu", &g_define_type_info, 0);
	IndicatorKeyboardIndicatorMenu_private_offset = g_type_add_instance_private (indicator_keyboard_indicator_menu_type_id, sizeof (IndicatorKeyboardIndicatorMenuPrivate));
	return indicator_keyboard_indicator_menu_type_id;
}

GType
indicator_keyboard_indicator_menu_get_type (void)
{
	static volatile gsize indicator_keyboard_indicator_menu_type_id__once = 0;
	if (g_once_init_enter (&indicator_keyboard_indicator_menu_type_id__once)) {
		GType indicator_keyboard_indicator_menu_type_id;
		indicator_keyboard_indicator_menu_type_id = indicator_keyboard_indicator_menu_get_type_once ();
		g_once_init_leave (&indicator_keyboard_indicator_menu_type_id__once, indicator_keyboard_indicator_menu_type_id);
	}
	return indicator_keyboard_indicator_menu_type_id__once;
}

