/* unity-extras-internal.vapi generated by valac 0.56.19, do not modify. */

[CCode (gir_namespace = "UnityExtras", gir_version = "7.0")]
namespace Unity {
	[CCode (gir_namespace = "UnityExtras", gir_version = "1.0")]
	namespace Extras {
		[CCode (cheader_filename = "unity-extras-internal.h")]
		public class PreviewPlayer : GLib.Object {
			public async void play (string uri) throws GLib.Error;
			public async void pause () throws GLib.Error;
			public async void pause_resume () throws GLib.Error;
			public async void resume () throws GLib.Error;
			public async void stop () throws GLib.Error;
			public async void close () throws GLib.Error;
			public async GLib.HashTable<string,GLib.Variant> video_properties (string uri) throws GLib.Error;
			internal void on_progress_signal (string uri, uint32 state, double progress_value);
			public PreviewPlayer ();
			public signal void progress (string uri, Unity.MusicPreview.TrackState state, double progress);
		}
		[CCode (cheader_filename = "unity-extras-internal.h")]
		[DBus (name = "com.canonical.Unity.Lens.Music.PreviewPlayer")]
		internal interface PreviewPlayerService : GLib.Object {
			public abstract async void play (string uri) throws GLib.Error;
			public abstract async void pause () throws GLib.Error;
			public abstract async void pause_resume () throws GLib.Error;
			public abstract async void resume () throws GLib.Error;
			public abstract async void stop () throws GLib.Error;
			public abstract async void close () throws GLib.Error;
			public abstract async GLib.HashTable<string,GLib.Variant> video_properties (string uri) throws GLib.Error;
			public signal void progress (string uri, uint32 state, double progress);
		}
		[CCode (cheader_filename = "unity-extras-internal.h")]
		[DBus (name = "org.freedesktop.FileManager1")]
		internal interface FileManagerInterface : GLib.Object {
			public abstract async void show_items (string[] uris, string startup_id) throws GLib.Error;
		}
		[CCode (cheader_filename = "unity-extras-internal.h")]
		public delegate void CreateScopeCallback ();
		[CCode (cheader_filename = "unity-extras-internal.h")]
		internal const string PREVIEW_PLAYER_DBUS_NAME;
		[CCode (cheader_filename = "unity-extras-internal.h")]
		internal const string PREVIEW_PLAYER_DBUS_PATH;
		[CCode (cheader_filename = "unity-extras-internal.h")]
		internal const string FILE_MANAGER_DBUS_NAME;
		[CCode (cheader_filename = "unity-extras-internal.h")]
		internal const string FILE_MANAGER_DBUS_PATH;
		[CCode (cheader_filename = "unity-extras-internal.h")]
		public static async void show_in_folder (string uri) throws GLib.Error;
		[CCode (cheader_filename = "unity-extras-internal.h")]
		public static bool dbus_name_has_owner (string name) throws GLib.Error;
		[CCode (cheader_filename = "unity-extras-internal.h")]
		public static GLib.Application? dbus_own_name (string name, Unity.Extras.CreateScopeCallback scope_creation_cb) throws GLib.Error;
	}
}
