.TH GRAIL-TEST-EDGE 1 "March 29, 2012" "grail" "Open Input Framework"

.SH NAME
grail-test-edge \- test edge swipes

.SH SYNPOSIS
.B grail-test-edge
.br

.SH OPTIONS
There are no options for this program.

.SH DESCRIPTION
Attaches to the root window of the current X server and tries to identify edge
swipe gestures.

