.TH GRAIL-TEST-PROPAGATION 1 "March 29, 2012" "grail" "Open Input Framework"

.SH NAME
grail-test-propagation \- test driver tool for gesture accept/reject

.SH SYNPOSIS
.B grail-test-propagation 
.I window
.br

.SH OPTIONS
.I window
Specifies the
.I X window
of a specific window to associate with gestures.

.SH DESCRIPTION
Runs a gesture recognizer on the given X11 window, alternately exercising gesture
accept and reject functionality as gestures are performed.

