.TH GRAIL-TEST-3-1 1 "March 14, 2012" "grail" "Open Input Framework"

.SH NAME
grail-test-3-1 \- dump grail v3 events

.SH SYNPOSIS
.B grail-test-3-1
.I window
.br

.SH DESCRIPTION
This tool prints grail v3 events to stdout.
It requires an X11 server which supports multi-touch through XInput 2.2.
It subscribes to gestures with 3 touch start and max,
but with a minimum of 1 touch.
The grail-test-3-1 tool helps test continuation through touch count changes.
