/* scope-loader.c generated by valac 0.56.19, the Vala compiler
 * generated from scope-loader.vala, do not modify */

/* -*- mode: vala; c-basic-offset: 2; indent-tabs-mode: nil -*- */

#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <unity.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_option_context_free0(var) ((var == NULL) ? NULL : (var = (g_option_context_free (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

VALA_EXTERN gchar* options_group;
gchar* options_group = NULL;
VALA_EXTERN gchar* options_module;
gchar* options_module = NULL;

static gint _vala_main (gchar** args,
                 gint args_length1);

const GOptionEntry options[3] = {{"group", 'g', (gint) 0, G_OPTION_ARG_STRING, &options_group, "Scope group configuration", NULL}, {"module", 'm', (gint) 0, G_OPTION_ARG_STRING, &options_module, "Scope shared library (for testing)", NULL}, {NULL}};

static gint
_vala_main (gchar** args,
            gint args_length1)
{
	GOptionContext* opt_context = NULL;
	GOptionContext* _tmp0_;
	GOptionContext* _tmp1_;
	UnityScopeLoader* loader = NULL;
	UnityScopeLoader* _tmp5_;
	GError* _inner_error0_ = NULL;
	gint result;
	g_set_prgname ("unity-scope-loader");
	_tmp0_ = g_option_context_new ("[scope-ids]");
	opt_context = _tmp0_;
	_tmp1_ = opt_context;
	g_option_context_add_main_entries (_tmp1_, options, NULL);
	if (args_length1 <= 1) {
		GOptionContext* _tmp2_;
		gchar* _tmp3_;
		gchar* _tmp4_;
		_tmp2_ = opt_context;
		_tmp3_ = g_option_context_get_help (_tmp2_, TRUE, NULL);
		_tmp4_ = _tmp3_;
		g_print ("%s\n", _tmp4_);
		_g_free0 (_tmp4_);
		result = 0;
		_g_option_context_free0 (opt_context);
		return result;
	}
	_tmp5_ = unity_scope_loader_new ();
	loader = _tmp5_;
	{
		GOptionContext* _tmp6_;
		const gchar* _tmp7_;
		_tmp6_ = opt_context;
		g_option_context_parse (_tmp6_, (gint*) (&args_length1), &args, &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			goto __catch0_g_error;
		}
		_tmp7_ = options_group;
		if (_tmp7_ != NULL) {
			UnityScopeLoader* _tmp8_;
			const gchar* _tmp9_;
			_tmp8_ = loader;
			_tmp9_ = options_group;
			unity_scope_loader_load_group (_tmp8_, _tmp9_, &_inner_error0_);
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
				goto __catch0_g_error;
			}
		} else {
			const gchar* _tmp10_;
			_tmp10_ = options_module;
			if (_tmp10_ != NULL) {
				UnityScopeLoader* _tmp11_;
				const gchar* _tmp12_;
				_tmp11_ = loader;
				_tmp12_ = options_module;
				unity_scope_loader_load_module (_tmp11_, _tmp12_, "C", &_inner_error0_);
				if (G_UNLIKELY (_inner_error0_ != NULL)) {
					goto __catch0_g_error;
				}
			} else {
				{
					gint i = 0;
					i = 1;
					{
						gboolean _tmp13_ = FALSE;
						_tmp13_ = TRUE;
						while (TRUE) {
							gchar* scope_id = NULL;
							const gchar* _tmp15_;
							gchar* _tmp16_;
							UnityScopeLoader* _tmp17_;
							const gchar* _tmp18_;
							if (!_tmp13_) {
								gint _tmp14_;
								_tmp14_ = i;
								i = _tmp14_ + 1;
							}
							_tmp13_ = FALSE;
							if (!(i < args_length1)) {
								break;
							}
							_tmp15_ = args[i];
							_tmp16_ = g_strdup (_tmp15_);
							scope_id = _tmp16_;
							_tmp17_ = loader;
							_tmp18_ = scope_id;
							unity_scope_loader_load_scope (_tmp17_, _tmp18_, &_inner_error0_);
							if (G_UNLIKELY (_inner_error0_ != NULL)) {
								_g_free0 (scope_id);
								goto __catch0_g_error;
							}
							_g_free0 (scope_id);
						}
					}
				}
			}
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* err = NULL;
		const gchar* _tmp19_;
		err = _inner_error0_;
		_inner_error0_ = NULL;
		_tmp19_ = err->message;
		g_error ("scope-loader.vala:59: %s", _tmp19_);
		_g_error_free0 (err);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		gint _tmp20_ = -1;
		_g_object_unref0 (loader);
		_g_option_context_free0 (opt_context);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return _tmp20_;
	}
	unity_scope_dbus_connector_run ();
	result = 0;
	_g_object_unref0 (loader);
	_g_option_context_free0 (opt_context);
	return result;
}

int
main (int argc,
      char ** argv)
{
	return _vala_main (argv, argc);
}

