static const gchar org_gnome_zeitgeist_Blacklist_xml[] = 
"<?xml version='1.0' encoding='UTF-8' ?>"
"<node>"
""
"  <interface name='org.gnome.zeitgeist.Blacklist'>"
"  "
"    <!-- Events matching the blacklisted templates will not be inserted into the log -->"
"    <method name='SetBlacklist'>"
"      <!-- List of event templates to blacklist -->"
"      <arg direction='in'  type='a(asaasay)' name='events' />        "
"    </method>"
"  "
"    <method name='GetBlacklist'>"
"      <!-- List of event templates to blacklist -->"
"      <arg direction='out'  type='a(asaasay)' name='events' /> "
"    </method>"
"  "
"  </interface>"
"  "
"</node>"
;
