const char * _application_menu_registrar = 
"<?xml version=\"1.0\"?>\n"
"<node>\n"
"	\n"
"	<interface name=\"com.canonical.AppMenu.Registrar\">\n"
"		\n"
"		<method name=\"RegisterWindow\">\n"
"			<annotation name=\"org.freedesktop.DBus.GLib.Async\" value=\"true\"/>\n"
"			\n"
"			<arg name=\"windowId\" type=\"u\" direction=\"in\">\n"
"				\n"
"			</arg>\n"
"			<arg name=\"menuObjectPath\" type=\"o\" direction=\"in\">\n"
"				\n"
"			</arg>\n"
"		</method>\n"
"		<method name=\"UnregisterWindow\">\n"
"			\n"
"			<arg name=\"windowId\" type=\"u\" direction=\"in\">\n"
"				\n"
"			</arg>\n"
"		</method>\n"
"		<method name=\"GetMenuForWindow\">\n"
"			\n"
"			<arg name=\"windowId\" type=\"u\" direction=\"in\">\n"
"				\n"
"			</arg>\n"
"			<arg name=\"service\" type=\"s\" direction=\"out\">\n"
"				\n"
"			</arg>\n"
"			<arg name=\"menuObjectPath\" type=\"o\" direction=\"out\">\n"
"				\n"
"			</arg>\n"
"		</method>\n"
"		<method name=\"GetMenus\">\n"
"			<annotation name=\"com.trolltech.QtDBus.QtTypeName.Out0\" value=\"MenuInfoList\"/>\n"
"			\n"
"			<arg name=\"menus\" type=\"a(uso)\" direction=\"out\">\n"
"				\n"
"			</arg>\n"
"		</method>\n"
"		<signal name=\"WindowRegistered\">\n"
"			\n"
"			<arg name=\"windowId\" type=\"u\" direction=\"out\">\n"
"				\n"
"			</arg>\n"
"			<arg name=\"service\" type=\"s\" direction=\"out\">\n"
"				\n"
"			</arg>\n"
"			<arg name=\"menuObjectPath\" type=\"o\" direction=\"out\">\n"
"				\n"
"			</arg>\n"
"		</signal>\n"
"		<signal name=\"WindowUnregistered\">\n"
"			\n"
"			<arg name=\"windowId\" type=\"u\" direction=\"out\">\n"
"				\n"
"			</arg>\n"
"		</signal>\n"
"	</interface>\n"
"</node>\n"
;
