/* test-filters.c generated by valac 0.56.19, the Vala compiler
 * generated from test-filters.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: nil; c-basic-offset: 2; tab-width: 2 -*- */
/*
 * Copyright (C) 2011 Canonical Ltd
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Authored by Mikkel Kamstrup Erlandsen <mikkel.kamstrup@canonical.com>
 *
 */

#include <glib-object.h>
#include <glib.h>
#include <unity-internal.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <gobject/gvaluecollector.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define UNITY_TEST_TYPE_FILTER_SUITE (unity_test_filter_suite_get_type ())
#define UNITY_TEST_FILTER_SUITE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), UNITY_TEST_TYPE_FILTER_SUITE, UnityTestFilterSuite))
#define UNITY_TEST_FILTER_SUITE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), UNITY_TEST_TYPE_FILTER_SUITE, UnityTestFilterSuiteClass))
#define UNITY_TEST_IS_FILTER_SUITE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), UNITY_TEST_TYPE_FILTER_SUITE))
#define UNITY_TEST_IS_FILTER_SUITE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), UNITY_TEST_TYPE_FILTER_SUITE))
#define UNITY_TEST_FILTER_SUITE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), UNITY_TEST_TYPE_FILTER_SUITE, UnityTestFilterSuiteClass))

typedef struct _UnityTestFilterSuite UnityTestFilterSuite;
typedef struct _UnityTestFilterSuiteClass UnityTestFilterSuiteClass;
typedef struct _UnityTestFilterSuitePrivate UnityTestFilterSuitePrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _UnityTestParamSpecFilterSuite UnityTestParamSpecFilterSuite;
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _UnityTestFilterSuite {
	GTypeInstance parent_instance;
	volatile int ref_count;
	UnityTestFilterSuitePrivate * priv;
};

struct _UnityTestFilterSuiteClass {
	GTypeClass parent_class;
	void (*finalize) (UnityTestFilterSuite *self);
};

struct _UnityTestParamSpecFilterSuite {
	GParamSpec parent_instance;
};

static gpointer unity_test_filter_suite_parent_class = NULL;

VALA_EXTERN gpointer unity_test_filter_suite_ref (gpointer instance);
VALA_EXTERN void unity_test_filter_suite_unref (gpointer instance);
VALA_EXTERN GParamSpec* unity_test_param_spec_filter_suite (const gchar* name,
                                                const gchar* nick,
                                                const gchar* blurb,
                                                GType object_type,
                                                GParamFlags flags);
VALA_EXTERN void unity_test_value_set_filter_suite (GValue* value,
                                        gpointer v_object);
VALA_EXTERN void unity_test_value_take_filter_suite (GValue* value,
                                         gpointer v_object);
VALA_EXTERN gpointer unity_test_value_get_filter_suite (const GValue* value);
VALA_EXTERN GType unity_test_filter_suite_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (UnityTestFilterSuite, unity_test_filter_suite_unref)
VALA_EXTERN UnityTestFilterSuite* unity_test_filter_suite_new (void);
VALA_EXTERN UnityTestFilterSuite* unity_test_filter_suite_construct (GType object_type);
VALA_EXTERN void unity_test_filter_suite_test_options_filter_empty (void);
static void _unity_test_filter_suite_test_options_filter_empty_gtest_data_func (gpointer self);
VALA_EXTERN void unity_test_filter_suite_test_options_filter_sort_manual (void);
static void _unity_test_filter_suite_test_options_filter_sort_manual_gtest_data_func (gpointer self);
VALA_EXTERN void unity_test_filter_suite_test_options_filter_sort_display_name (void);
static void _unity_test_filter_suite_test_options_filter_sort_display_name_gtest_data_func (gpointer self);
VALA_EXTERN void unity_test_filter_suite_test_options_filter_sort_id (void);
static void _unity_test_filter_suite_test_options_filter_sort_id_gtest_data_func (gpointer self);
VALA_EXTERN void unity_test_filter_suite_test_radio_options_filter (void);
static void _unity_test_filter_suite_test_radio_options_filter_gtest_data_func (gpointer self);
VALA_EXTERN void unity_test_filter_suite_test_ratings_filter (void);
static void _unity_test_filter_suite_test_ratings_filter_gtest_data_func (gpointer self);
static gint unity_test_filter_suite_find_filter_offset_by_id (UnityOptionsFilter* filter,
                                                       const gchar* id);
static void unity_test_filter_suite_finalize (UnityTestFilterSuite * obj);
static GType unity_test_filter_suite_get_type_once (void);

static void
_unity_test_filter_suite_test_options_filter_empty_gtest_data_func (gpointer self)
{
	unity_test_filter_suite_test_options_filter_empty ();
}

static void
_unity_test_filter_suite_test_options_filter_sort_manual_gtest_data_func (gpointer self)
{
	unity_test_filter_suite_test_options_filter_sort_manual ();
}

static void
_unity_test_filter_suite_test_options_filter_sort_display_name_gtest_data_func (gpointer self)
{
	unity_test_filter_suite_test_options_filter_sort_display_name ();
}

static void
_unity_test_filter_suite_test_options_filter_sort_id_gtest_data_func (gpointer self)
{
	unity_test_filter_suite_test_options_filter_sort_id ();
}

static void
_unity_test_filter_suite_test_radio_options_filter_gtest_data_func (gpointer self)
{
	unity_test_filter_suite_test_radio_options_filter ();
}

static void
_unity_test_filter_suite_test_ratings_filter_gtest_data_func (gpointer self)
{
	unity_test_filter_suite_test_ratings_filter ();
}

UnityTestFilterSuite*
unity_test_filter_suite_construct (GType object_type)
{
	UnityTestFilterSuite* self = NULL;
	self = (UnityTestFilterSuite*) g_type_create_instance (object_type);
	g_test_add_data_func ("/Unit/Filters/OptionsFilter/Empty", NULL, _unity_test_filter_suite_test_options_filter_empty_gtest_data_func);
	g_test_add_data_func ("/Unit/Filters/OptionsFilter/SortManual", NULL, _unity_test_filter_suite_test_options_filter_sort_manual_gtest_data_func);
	g_test_add_data_func ("/Unit/Filters/OptionsFilter/SortDisplayName", NULL, _unity_test_filter_suite_test_options_filter_sort_display_name_gtest_data_func);
	g_test_add_data_func ("/Unit/Filters/OptionsFilter/SortId", NULL, _unity_test_filter_suite_test_options_filter_sort_id_gtest_data_func);
	g_test_add_data_func ("/Unit/Filters/RadioOptionsFilter", NULL, _unity_test_filter_suite_test_radio_options_filter_gtest_data_func);
	g_test_add_data_func ("/Unit/Filters/RatingsFilter", NULL, _unity_test_filter_suite_test_ratings_filter_gtest_data_func);
	return self;
}

UnityTestFilterSuite*
unity_test_filter_suite_new (void)
{
	return unity_test_filter_suite_construct (UNITY_TEST_TYPE_FILTER_SUITE);
}

void
unity_test_filter_suite_test_options_filter_empty (void)
{
	UnityOptionsFilter* filter = NULL;
	UnityOptionsFilter* _tmp0_;
	GList* _tmp1_;
	_tmp0_ = unity_options_filter_new ();
	filter = _tmp0_;
	_tmp1_ = filter->options;
	_vala_assert (g_list_length (_tmp1_) == ((guint) 0), "filter.options.length () == 0");
	_g_object_unref0 (filter);
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

static gint
unity_test_filter_suite_find_filter_offset_by_id (UnityOptionsFilter* filter,
                                                  const gchar* id)
{
	gint i = 0;
	GList* _tmp0_;
	gint result;
	g_return_val_if_fail (filter != NULL, -1);
	g_return_val_if_fail (id != NULL, -1);
	i = 0;
	_tmp0_ = filter->options;
	{
		GList* f_collection = NULL;
		GList* f_it = NULL;
		f_collection = _tmp0_;
		for (f_it = f_collection; f_it != NULL; f_it = f_it->next) {
			UnityFilterOption* _tmp1_;
			UnityFilterOption* f = NULL;
			_tmp1_ = _g_object_ref0 ((UnityFilterOption*) f_it->data);
			f = _tmp1_;
			{
				UnityFilterOption* _tmp2_;
				const gchar* _tmp3_;
				const gchar* _tmp4_;
				gint _tmp5_;
				_tmp2_ = f;
				_tmp3_ = unity_filter_option_get_id (_tmp2_);
				_tmp4_ = _tmp3_;
				if (g_strcmp0 (_tmp4_, id) == 0) {
					result = i;
					_g_object_unref0 (f);
					return result;
				}
				_tmp5_ = i;
				i = _tmp5_ + 1;
				_g_object_unref0 (f);
			}
		}
	}
	result = -1;
	return result;
}

void
unity_test_filter_suite_test_options_filter_sort_manual (void)
{
	UnityOptionsFilter* filter = NULL;
	UnityOptionsFilter* _tmp0_;
	UnityOptionsFilterSortType _tmp1_;
	UnityOptionsFilterSortType _tmp2_;
	UnityFilterOption* _tmp3_;
	UnityFilterOption* _tmp4_;
	UnityFilterOption* _tmp5_;
	UnityFilterOption* _tmp6_;
	UnityFilterOption* _tmp7_;
	UnityFilterOption* _tmp8_;
	UnityFilterOption* _tmp9_;
	UnityFilterOption* _tmp10_;
	_tmp0_ = unity_options_filter_new ();
	filter = _tmp0_;
	_tmp1_ = unity_options_filter_get_sort_type (filter);
	_tmp2_ = _tmp1_;
	_vala_assert (_tmp2_ == UNITY_OPTIONS_FILTER_SORT_TYPE_MANUAL, "filter.sort_type == OptionsFilter.SortType.MANUAL");
	_tmp3_ = unity_options_filter_add_option (filter, "accessories", "Accessories", NULL);
	_tmp4_ = _tmp3_;
	_g_object_unref0 (_tmp4_);
	_tmp5_ = unity_options_filter_add_option (filter, "bccessories", "Bccessories", NULL);
	_tmp6_ = _tmp5_;
	_g_object_unref0 (_tmp6_);
	_tmp7_ = unity_options_filter_add_option (filter, "xenomorphs", "Xenomorphic Creatures", NULL);
	_tmp8_ = _tmp7_;
	_g_object_unref0 (_tmp8_);
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id (filter, "accessories") == 0, "find_filter_offset_by_id (filter, \"accessories\") == 0");
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id (filter, "bccessories") == 1, "find_filter_offset_by_id (filter, \"bccessories\") == 1");
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id (filter, "xenomorphs") == 2, "find_filter_offset_by_id (filter, \"xenomorphs\") == 2");
	_tmp9_ = unity_options_filter_add_option (filter, "aardvaark", "Weird Animal", NULL);
	_tmp10_ = _tmp9_;
	_g_object_unref0 (_tmp10_);
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id (filter, "accessories") == 0, "find_filter_offset_by_id (filter, \"accessories\") == 0");
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id (filter, "bccessories") == 1, "find_filter_offset_by_id (filter, \"bccessories\") == 1");
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id (filter, "xenomorphs") == 2, "find_filter_offset_by_id (filter, \"xenomorphs\") == 2");
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id (filter, "aardvaark") == 3, "find_filter_offset_by_id (filter, \"aardvaark\") == 3");
	_g_object_unref0 (filter);
}

void
unity_test_filter_suite_test_options_filter_sort_display_name (void)
{
	UnityOptionsFilter* filter = NULL;
	UnityOptionsFilter* _tmp0_;
	UnityOptionsFilterSortType _tmp1_;
	UnityOptionsFilterSortType _tmp2_;
	UnityFilterOption* _tmp3_;
	UnityFilterOption* _tmp4_;
	UnityFilterOption* _tmp5_;
	UnityFilterOption* _tmp6_;
	UnityFilterOption* _tmp7_;
	UnityFilterOption* _tmp8_;
	UnityFilterOption* _tmp9_;
	UnityFilterOption* _tmp10_;
	UnityFilterOption* _tmp11_;
	UnityFilterOption* _tmp12_;
	_tmp0_ = unity_options_filter_new ();
	filter = _tmp0_;
	unity_options_filter_set_sort_type (filter, UNITY_OPTIONS_FILTER_SORT_TYPE_DISPLAY_NAME);
	_tmp1_ = unity_options_filter_get_sort_type (filter);
	_tmp2_ = _tmp1_;
	_vala_assert (_tmp2_ == UNITY_OPTIONS_FILTER_SORT_TYPE_DISPLAY_NAME, "filter.sort_type == OptionsFilter.SortType.DISPLAY_NAME");
	_tmp3_ = unity_options_filter_add_option (filter, "accessories", "Accessories", NULL);
	_tmp4_ = _tmp3_;
	_g_object_unref0 (_tmp4_);
	_tmp5_ = unity_options_filter_add_option (filter, "bccessories", "Bccessories", NULL);
	_tmp6_ = _tmp5_;
	_g_object_unref0 (_tmp6_);
	_tmp7_ = unity_options_filter_add_option (filter, "xenomorphs", "Xenomorphic Creatures", NULL);
	_tmp8_ = _tmp7_;
	_g_object_unref0 (_tmp8_);
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id (filter, "accessories") == 0, "find_filter_offset_by_id (filter, \"accessories\") == 0");
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id (filter, "bccessories") == 1, "find_filter_offset_by_id (filter, \"bccessories\") == 1");
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id (filter, "xenomorphs") == 2, "find_filter_offset_by_id (filter, \"xenomorphs\") == 2");
	_tmp9_ = unity_options_filter_add_option (filter, "weirdanimal", "Aardvaark", NULL);
	_tmp10_ = _tmp9_;
	_g_object_unref0 (_tmp10_);
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id (filter, "weirdanimal") == 0, "find_filter_offset_by_id (filter, \"weirdanimal\") == 0");
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id (filter, "accessories") == 1, "find_filter_offset_by_id (filter, \"accessories\") == 1");
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id (filter, "bccessories") == 2, "find_filter_offset_by_id (filter, \"bccessories\") == 2");
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id (filter, "xenomorphs") == 3, "find_filter_offset_by_id (filter, \"xenomorphs\") == 3");
	_tmp11_ = unity_options_filter_add_option (filter, "zooanimal", "Zebra", NULL);
	_tmp12_ = _tmp11_;
	_g_object_unref0 (_tmp12_);
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id (filter, "weirdanimal") == 0, "find_filter_offset_by_id (filter, \"weirdanimal\") == 0");
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id (filter, "accessories") == 1, "find_filter_offset_by_id (filter, \"accessories\") == 1");
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id (filter, "bccessories") == 2, "find_filter_offset_by_id (filter, \"bccessories\") == 2");
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id (filter, "xenomorphs") == 3, "find_filter_offset_by_id (filter, \"xenomorphs\") == 3");
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id (filter, "zooanimal") == 4, "find_filter_offset_by_id (filter, \"zooanimal\") == 4");
	_g_object_unref0 (filter);
}

void
unity_test_filter_suite_test_options_filter_sort_id (void)
{
	UnityOptionsFilter* filter = NULL;
	UnityOptionsFilter* _tmp0_;
	UnityOptionsFilterSortType _tmp1_;
	UnityOptionsFilterSortType _tmp2_;
	UnityFilterOption* _tmp3_;
	UnityFilterOption* _tmp4_;
	UnityFilterOption* _tmp5_;
	UnityFilterOption* _tmp6_;
	UnityFilterOption* _tmp7_;
	UnityFilterOption* _tmp8_;
	UnityFilterOption* _tmp9_;
	UnityFilterOption* _tmp10_;
	UnityFilterOption* _tmp11_;
	UnityFilterOption* _tmp12_;
	_tmp0_ = unity_options_filter_new ();
	filter = _tmp0_;
	unity_options_filter_set_sort_type (filter, UNITY_OPTIONS_FILTER_SORT_TYPE_ID);
	_tmp1_ = unity_options_filter_get_sort_type (filter);
	_tmp2_ = _tmp1_;
	_vala_assert (_tmp2_ == UNITY_OPTIONS_FILTER_SORT_TYPE_ID, "filter.sort_type == OptionsFilter.SortType.ID");
	_tmp3_ = unity_options_filter_add_option (filter, "accessories", "Accessories", NULL);
	_tmp4_ = _tmp3_;
	_g_object_unref0 (_tmp4_);
	_tmp5_ = unity_options_filter_add_option (filter, "bccessories", "Bccessories", NULL);
	_tmp6_ = _tmp5_;
	_g_object_unref0 (_tmp6_);
	_tmp7_ = unity_options_filter_add_option (filter, "xenomorphs", "Xenomorphic Creatures", NULL);
	_tmp8_ = _tmp7_;
	_g_object_unref0 (_tmp8_);
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id (filter, "accessories") == 0, "find_filter_offset_by_id (filter, \"accessories\") == 0");
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id (filter, "bccessories") == 1, "find_filter_offset_by_id (filter, \"bccessories\") == 1");
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id (filter, "xenomorphs") == 2, "find_filter_offset_by_id (filter, \"xenomorphs\") == 2");
	_tmp9_ = unity_options_filter_add_option (filter, "weirdanimal", "Aardvaark", NULL);
	_tmp10_ = _tmp9_;
	_g_object_unref0 (_tmp10_);
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id (filter, "accessories") == 0, "find_filter_offset_by_id (filter, \"accessories\") == 0");
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id (filter, "bccessories") == 1, "find_filter_offset_by_id (filter, \"bccessories\") == 1");
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id (filter, "weirdanimal") == 2, "find_filter_offset_by_id (filter, \"weirdanimal\") == 2");
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id (filter, "xenomorphs") == 3, "find_filter_offset_by_id (filter, \"xenomorphs\") == 3");
	_tmp11_ = unity_options_filter_add_option (filter, "zooanimal", "Zebra", NULL);
	_tmp12_ = _tmp11_;
	_g_object_unref0 (_tmp12_);
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id (filter, "accessories") == 0, "find_filter_offset_by_id (filter, \"accessories\") == 0");
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id (filter, "bccessories") == 1, "find_filter_offset_by_id (filter, \"bccessories\") == 1");
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id (filter, "weirdanimal") == 2, "find_filter_offset_by_id (filter, \"weirdanimal\") == 2");
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id (filter, "xenomorphs") == 3, "find_filter_offset_by_id (filter, \"xenomorphs\") == 3");
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id (filter, "zooanimal") == 4, "find_filter_offset_by_id (filter, \"zooanimal\") == 4");
	_g_object_unref0 (filter);
}

void
unity_test_filter_suite_test_radio_options_filter (void)
{
	UnityRadioOptionFilter* filter = NULL;
	UnityRadioOptionFilter* _tmp0_;
	UnityOptionsFilterSortType _tmp1_;
	UnityOptionsFilterSortType _tmp2_;
	UnityFilterOption* _tmp3_;
	UnityFilterOption* _tmp4_;
	UnityFilterOption* _tmp5_;
	UnityFilterOption* _tmp6_;
	UnityFilterOption* _tmp7_;
	UnityFilterOption* _tmp8_;
	UnityFilterOption* _tmp9_;
	UnityFilterOption* _tmp10_;
	UnityFilterOption* _tmp11_;
	UnityFilterOption* _tmp12_;
	_tmp0_ = unity_radio_option_filter_new ("radio1", "Radio 1", NULL, FALSE);
	filter = _tmp0_;
	unity_options_filter_set_sort_type ((UnityOptionsFilter*) filter, UNITY_OPTIONS_FILTER_SORT_TYPE_ID);
	_tmp1_ = unity_options_filter_get_sort_type ((UnityOptionsFilter*) filter);
	_tmp2_ = _tmp1_;
	_vala_assert (_tmp2_ == UNITY_OPTIONS_FILTER_SORT_TYPE_ID, "filter.sort_type == OptionsFilter.SortType.ID");
	_tmp3_ = unity_options_filter_add_option ((UnityOptionsFilter*) filter, "accessories", "Accessories", NULL);
	_tmp4_ = _tmp3_;
	_g_object_unref0 (_tmp4_);
	_tmp5_ = unity_options_filter_add_option ((UnityOptionsFilter*) filter, "bccessories", "Bccessories", NULL);
	_tmp6_ = _tmp5_;
	_g_object_unref0 (_tmp6_);
	_tmp7_ = unity_options_filter_add_option ((UnityOptionsFilter*) filter, "xenomorphs", "Xenomorphic Creatures", NULL);
	_tmp8_ = _tmp7_;
	_g_object_unref0 (_tmp8_);
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id ((UnityOptionsFilter*) filter, "accessories") == 0, "find_filter_offset_by_id (filter, \"accessories\") == 0");
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id ((UnityOptionsFilter*) filter, "bccessories") == 1, "find_filter_offset_by_id (filter, \"bccessories\") == 1");
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id ((UnityOptionsFilter*) filter, "xenomorphs") == 2, "find_filter_offset_by_id (filter, \"xenomorphs\") == 2");
	_tmp9_ = unity_options_filter_add_option ((UnityOptionsFilter*) filter, "weirdanimal", "Aardvaark", NULL);
	_tmp10_ = _tmp9_;
	_g_object_unref0 (_tmp10_);
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id ((UnityOptionsFilter*) filter, "accessories") == 0, "find_filter_offset_by_id (filter, \"accessories\") == 0");
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id ((UnityOptionsFilter*) filter, "bccessories") == 1, "find_filter_offset_by_id (filter, \"bccessories\") == 1");
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id ((UnityOptionsFilter*) filter, "weirdanimal") == 2, "find_filter_offset_by_id (filter, \"weirdanimal\") == 2");
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id ((UnityOptionsFilter*) filter, "xenomorphs") == 3, "find_filter_offset_by_id (filter, \"xenomorphs\") == 3");
	_tmp11_ = unity_options_filter_add_option ((UnityOptionsFilter*) filter, "zooanimal", "Zebra", NULL);
	_tmp12_ = _tmp11_;
	_g_object_unref0 (_tmp12_);
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id ((UnityOptionsFilter*) filter, "accessories") == 0, "find_filter_offset_by_id (filter, \"accessories\") == 0");
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id ((UnityOptionsFilter*) filter, "bccessories") == 1, "find_filter_offset_by_id (filter, \"bccessories\") == 1");
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id ((UnityOptionsFilter*) filter, "weirdanimal") == 2, "find_filter_offset_by_id (filter, \"weirdanimal\") == 2");
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id ((UnityOptionsFilter*) filter, "xenomorphs") == 3, "find_filter_offset_by_id (filter, \"xenomorphs\") == 3");
	_vala_assert (unity_test_filter_suite_find_filter_offset_by_id ((UnityOptionsFilter*) filter, "zooanimal") == 4, "find_filter_offset_by_id (filter, \"zooanimal\") == 4");
	_g_object_unref0 (filter);
}

void
unity_test_filter_suite_test_ratings_filter (void)
{
	UnityRatingsFilter* filter = NULL;
	UnityRatingsFilter* _tmp0_;
	gfloat _tmp1_;
	gfloat _tmp2_;
	_tmp0_ = unity_ratings_filter_new ("ratings1", "Ratings 1", NULL, FALSE);
	filter = _tmp0_;
	_tmp1_ = unity_ratings_filter_get_rating (filter);
	_tmp2_ = _tmp1_;
	_vala_assert (_tmp2_ >= ((gfloat) 0), "filter.rating >= 0");
	_g_object_unref0 (filter);
}

static void
unity_test_value_filter_suite_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}

static void
unity_test_value_filter_suite_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		unity_test_filter_suite_unref (value->data[0].v_pointer);
	}
}

static void
unity_test_value_filter_suite_copy_value (const GValue* src_value,
                                          GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = unity_test_filter_suite_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}

static gpointer
unity_test_value_filter_suite_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}

static gchar*
unity_test_value_filter_suite_collect_value (GValue* value,
                                             guint n_collect_values,
                                             GTypeCValue* collect_values,
                                             guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		UnityTestFilterSuite * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = unity_test_filter_suite_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}

static gchar*
unity_test_value_filter_suite_lcopy_value (const GValue* value,
                                           guint n_collect_values,
                                           GTypeCValue* collect_values,
                                           guint collect_flags)
{
	UnityTestFilterSuite ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = unity_test_filter_suite_ref (value->data[0].v_pointer);
	}
	return NULL;
}

GParamSpec*
unity_test_param_spec_filter_suite (const gchar* name,
                                    const gchar* nick,
                                    const gchar* blurb,
                                    GType object_type,
                                    GParamFlags flags)
{
	UnityTestParamSpecFilterSuite* spec;
	g_return_val_if_fail (g_type_is_a (object_type, UNITY_TEST_TYPE_FILTER_SUITE), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}

gpointer
unity_test_value_get_filter_suite (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, UNITY_TEST_TYPE_FILTER_SUITE), NULL);
	return value->data[0].v_pointer;
}

void
unity_test_value_set_filter_suite (GValue* value,
                                   gpointer v_object)
{
	UnityTestFilterSuite * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, UNITY_TEST_TYPE_FILTER_SUITE));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, UNITY_TEST_TYPE_FILTER_SUITE));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		unity_test_filter_suite_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		unity_test_filter_suite_unref (old);
	}
}

void
unity_test_value_take_filter_suite (GValue* value,
                                    gpointer v_object)
{
	UnityTestFilterSuite * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, UNITY_TEST_TYPE_FILTER_SUITE));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, UNITY_TEST_TYPE_FILTER_SUITE));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		unity_test_filter_suite_unref (old);
	}
}

static void
unity_test_filter_suite_class_init (UnityTestFilterSuiteClass * klass,
                                    gpointer klass_data)
{
	unity_test_filter_suite_parent_class = g_type_class_peek_parent (klass);
	((UnityTestFilterSuiteClass *) klass)->finalize = unity_test_filter_suite_finalize;
}

static void
unity_test_filter_suite_instance_init (UnityTestFilterSuite * self,
                                       gpointer klass)
{
	self->ref_count = 1;
}

static void
unity_test_filter_suite_finalize (UnityTestFilterSuite * obj)
{
	UnityTestFilterSuite * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, UNITY_TEST_TYPE_FILTER_SUITE, UnityTestFilterSuite);
	g_signal_handlers_destroy (self);
}

static GType
unity_test_filter_suite_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { unity_test_value_filter_suite_init, unity_test_value_filter_suite_free_value, unity_test_value_filter_suite_copy_value, unity_test_value_filter_suite_peek_pointer, "p", unity_test_value_filter_suite_collect_value, "p", unity_test_value_filter_suite_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (UnityTestFilterSuiteClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) unity_test_filter_suite_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (UnityTestFilterSuite), 0, (GInstanceInitFunc) unity_test_filter_suite_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType unity_test_filter_suite_type_id;
	unity_test_filter_suite_type_id = g_type_register_fundamental (g_type_fundamental_next (), "UnityTestFilterSuite", &g_define_type_info, &g_define_type_fundamental_info, 0);
	return unity_test_filter_suite_type_id;
}

GType
unity_test_filter_suite_get_type (void)
{
	static volatile gsize unity_test_filter_suite_type_id__once = 0;
	if (g_once_init_enter (&unity_test_filter_suite_type_id__once)) {
		GType unity_test_filter_suite_type_id;
		unity_test_filter_suite_type_id = unity_test_filter_suite_get_type_once ();
		g_once_init_leave (&unity_test_filter_suite_type_id__once, unity_test_filter_suite_type_id);
	}
	return unity_test_filter_suite_type_id__once;
}

gpointer
unity_test_filter_suite_ref (gpointer instance)
{
	UnityTestFilterSuite * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}

void
unity_test_filter_suite_unref (gpointer instance)
{
	UnityTestFilterSuite * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		UNITY_TEST_FILTER_SUITE_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}

