/* test-extras.c generated by valac 0.56.19, the Vala compiler
 * generated from test-extras.vala, do not modify */

/*
 * Copyright (C) 2010 Canonical Ltd
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Authored by Pawel Stolowski <pawel.stolowski@canonical.com>
 *
 */

#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <config.h>
#include <stdio.h>
#include <gobject/gvaluecollector.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define TYPE_MAIN (main_get_type ())
#define MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAIN, Main))
#define MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MAIN, MainClass))
#define IS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAIN))
#define IS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MAIN))
#define MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MAIN, MainClass))

typedef struct _Main Main;
typedef struct _MainClass MainClass;
typedef struct _MainPrivate MainPrivate;

#define UNITY_TEST_TYPE_UTILS_TEST_SUITE (unity_test_utils_test_suite_get_type ())
#define UNITY_TEST_UTILS_TEST_SUITE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), UNITY_TEST_TYPE_UTILS_TEST_SUITE, UnityTestUtilsTestSuite))
#define UNITY_TEST_UTILS_TEST_SUITE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), UNITY_TEST_TYPE_UTILS_TEST_SUITE, UnityTestUtilsTestSuiteClass))
#define UNITY_TEST_IS_UTILS_TEST_SUITE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), UNITY_TEST_TYPE_UTILS_TEST_SUITE))
#define UNITY_TEST_IS_UTILS_TEST_SUITE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), UNITY_TEST_TYPE_UTILS_TEST_SUITE))
#define UNITY_TEST_UTILS_TEST_SUITE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), UNITY_TEST_TYPE_UTILS_TEST_SUITE, UnityTestUtilsTestSuiteClass))

typedef struct _UnityTestUtilsTestSuite UnityTestUtilsTestSuite;
typedef struct _UnityTestUtilsTestSuiteClass UnityTestUtilsTestSuiteClass;

#define UNITY_TEST_TYPE_PREVIEW_PLAYER_IFACE_TEST_SUITE (unity_test_preview_player_iface_test_suite_get_type ())
#define UNITY_TEST_PREVIEW_PLAYER_IFACE_TEST_SUITE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), UNITY_TEST_TYPE_PREVIEW_PLAYER_IFACE_TEST_SUITE, UnityTestPreviewPlayerIfaceTestSuite))
#define UNITY_TEST_PREVIEW_PLAYER_IFACE_TEST_SUITE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), UNITY_TEST_TYPE_PREVIEW_PLAYER_IFACE_TEST_SUITE, UnityTestPreviewPlayerIfaceTestSuiteClass))
#define UNITY_TEST_IS_PREVIEW_PLAYER_IFACE_TEST_SUITE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), UNITY_TEST_TYPE_PREVIEW_PLAYER_IFACE_TEST_SUITE))
#define UNITY_TEST_IS_PREVIEW_PLAYER_IFACE_TEST_SUITE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), UNITY_TEST_TYPE_PREVIEW_PLAYER_IFACE_TEST_SUITE))
#define UNITY_TEST_PREVIEW_PLAYER_IFACE_TEST_SUITE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), UNITY_TEST_TYPE_PREVIEW_PLAYER_IFACE_TEST_SUITE, UnityTestPreviewPlayerIfaceTestSuiteClass))

typedef struct _UnityTestPreviewPlayerIfaceTestSuite UnityTestPreviewPlayerIfaceTestSuite;
typedef struct _UnityTestPreviewPlayerIfaceTestSuiteClass UnityTestPreviewPlayerIfaceTestSuiteClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _unity_test_preview_player_iface_test_suite_unref0(var) ((var == NULL) ? NULL : (var = (unity_test_preview_player_iface_test_suite_unref (var), NULL)))
#define _unity_test_utils_test_suite_unref0(var) ((var == NULL) ? NULL : (var = (unity_test_utils_test_suite_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _ParamSpecMain ParamSpecMain;

struct _Main {
	GTypeInstance parent_instance;
	volatile int ref_count;
	MainPrivate * priv;
};

struct _MainClass {
	GTypeClass parent_class;
	void (*finalize) (Main *self);
};

struct _ParamSpecMain {
	GParamSpec parent_instance;
};

static gpointer main_parent_class = NULL;

VALA_EXTERN gpointer main_ref (gpointer instance);
VALA_EXTERN void main_unref (gpointer instance);
VALA_EXTERN GParamSpec* param_spec_main (const gchar* name,
                             const gchar* nick,
                             const gchar* blurb,
                             GType object_type,
                             GParamFlags flags);
VALA_EXTERN void value_set_main (GValue* value,
                     gpointer v_object);
VALA_EXTERN void value_take_main (GValue* value,
                      gpointer v_object);
VALA_EXTERN gpointer value_get_main (const GValue* value);
VALA_EXTERN GType main_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (Main, main_unref)
static gint main_main (gchar** args,
                gint args_length1);
VALA_EXTERN gpointer unity_test_utils_test_suite_ref (gpointer instance);
VALA_EXTERN void unity_test_utils_test_suite_unref (gpointer instance);
VALA_EXTERN GParamSpec* unity_test_param_spec_utils_test_suite (const gchar* name,
                                                    const gchar* nick,
                                                    const gchar* blurb,
                                                    GType object_type,
                                                    GParamFlags flags);
VALA_EXTERN void unity_test_value_set_utils_test_suite (GValue* value,
                                            gpointer v_object);
VALA_EXTERN void unity_test_value_take_utils_test_suite (GValue* value,
                                             gpointer v_object);
VALA_EXTERN gpointer unity_test_value_get_utils_test_suite (const GValue* value);
VALA_EXTERN GType unity_test_utils_test_suite_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (UnityTestUtilsTestSuite, unity_test_utils_test_suite_unref)
VALA_EXTERN gpointer unity_test_preview_player_iface_test_suite_ref (gpointer instance);
VALA_EXTERN void unity_test_preview_player_iface_test_suite_unref (gpointer instance);
VALA_EXTERN GParamSpec* unity_test_param_spec_preview_player_iface_test_suite (const gchar* name,
                                                                   const gchar* nick,
                                                                   const gchar* blurb,
                                                                   GType object_type,
                                                                   GParamFlags flags);
VALA_EXTERN void unity_test_value_set_preview_player_iface_test_suite (GValue* value,
                                                           gpointer v_object);
VALA_EXTERN void unity_test_value_take_preview_player_iface_test_suite (GValue* value,
                                                            gpointer v_object);
VALA_EXTERN gpointer unity_test_value_get_preview_player_iface_test_suite (const GValue* value);
VALA_EXTERN GType unity_test_preview_player_iface_test_suite_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (UnityTestPreviewPlayerIfaceTestSuite, unity_test_preview_player_iface_test_suite_unref)
VALA_EXTERN UnityTestUtilsTestSuite* unity_test_utils_test_suite_new (void);
VALA_EXTERN UnityTestUtilsTestSuite* unity_test_utils_test_suite_construct (GType object_type);
VALA_EXTERN UnityTestPreviewPlayerIfaceTestSuite* unity_test_preview_player_iface_test_suite_new (void);
VALA_EXTERN UnityTestPreviewPlayerIfaceTestSuite* unity_test_preview_player_iface_test_suite_construct (GType object_type);
VALA_EXTERN Main* main_new (void);
VALA_EXTERN Main* main_construct (GType object_type);
static void main_finalize (Main * obj);
static GType main_get_type_once (void);

static gint
main_main (gchar** args,
           gint args_length1)
{
	UnityTestUtilsTestSuite* utils_suite = NULL;
	UnityTestPreviewPlayerIfaceTestSuite* preview_player_suite = NULL;
	gchar* gsettings_schema_dir = NULL;
	gchar* _tmp0_;
	const gchar* _tmp1_;
	UnityTestUtilsTestSuite* _tmp10_;
	UnityTestPreviewPlayerIfaceTestSuite* _tmp11_;
	GError* _inner_error0_ = NULL;
	gint result;
	_tmp0_ = g_strdup (BUILDDIR "/data");
	gsettings_schema_dir = _tmp0_;
	g_setenv ("XDG_DATA_HOME", TESTDIR "/data", TRUE);
	_tmp1_ = gsettings_schema_dir;
	g_setenv ("GSETTINGS_SCHEMA_DIR", _tmp1_, TRUE);
	g_setenv ("GSETTINGS_BACKEND", "memory", TRUE);
	{
		const gchar* _tmp2_;
		gchar* _tmp3_;
		gchar* _tmp4_;
		_tmp2_ = gsettings_schema_dir;
		_tmp3_ = g_strconcat ("glib-compile-schemas ", _tmp2_, NULL);
		_tmp4_ = _tmp3_;
		g_spawn_command_line_sync (_tmp4_, NULL, NULL, NULL, &_inner_error0_);
		_g_free0 (_tmp4_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			gint _tmp5_ = -1;
			if (_inner_error0_->domain == G_SPAWN_ERROR) {
				goto __catch0_g_spawn_error;
			}
			_g_free0 (gsettings_schema_dir);
			_unity_test_preview_player_iface_test_suite_unref0 (preview_player_suite);
			_unity_test_utils_test_suite_unref0 (utils_suite);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return _tmp5_;
		}
	}
	goto __finally0;
	__catch0_g_spawn_error:
	{
		GError* e = NULL;
		FILE* _tmp6_;
		GError* _tmp7_;
		const gchar* _tmp8_;
		e = _inner_error0_;
		_inner_error0_ = NULL;
		_tmp6_ = stderr;
		_tmp7_ = e;
		_tmp8_ = _tmp7_->message;
		fprintf (_tmp6_, "%s\n", _tmp8_);
		result = 1;
		_g_error_free0 (e);
		_g_free0 (gsettings_schema_dir);
		_unity_test_preview_player_iface_test_suite_unref0 (preview_player_suite);
		_unity_test_utils_test_suite_unref0 (utils_suite);
		return result;
	}
	__finally0:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		gint _tmp9_ = -1;
		_g_free0 (gsettings_schema_dir);
		_unity_test_preview_player_iface_test_suite_unref0 (preview_player_suite);
		_unity_test_utils_test_suite_unref0 (utils_suite);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return _tmp9_;
	}
	g_test_init ((gint*) (&args_length1), &args, NULL);
	_tmp10_ = unity_test_utils_test_suite_new ();
	_unity_test_utils_test_suite_unref0 (utils_suite);
	utils_suite = _tmp10_;
	_tmp11_ = unity_test_preview_player_iface_test_suite_new ();
	_unity_test_preview_player_iface_test_suite_unref0 (preview_player_suite);
	preview_player_suite = _tmp11_;
	g_test_run ();
	result = 0;
	_g_free0 (gsettings_schema_dir);
	_unity_test_preview_player_iface_test_suite_unref0 (preview_player_suite);
	_unity_test_utils_test_suite_unref0 (utils_suite);
	return result;
}

int
main (int argc,
      char ** argv)
{
	return main_main (argv, argc);
}

Main*
main_construct (GType object_type)
{
	Main* self = NULL;
	self = (Main*) g_type_create_instance (object_type);
	return self;
}

Main*
main_new (void)
{
	return main_construct (TYPE_MAIN);
}

static void
value_main_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}

static void
value_main_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		main_unref (value->data[0].v_pointer);
	}
}

static void
value_main_copy_value (const GValue* src_value,
                       GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = main_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}

static gpointer
value_main_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}

static gchar*
value_main_collect_value (GValue* value,
                          guint n_collect_values,
                          GTypeCValue* collect_values,
                          guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		Main * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = main_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}

static gchar*
value_main_lcopy_value (const GValue* value,
                        guint n_collect_values,
                        GTypeCValue* collect_values,
                        guint collect_flags)
{
	Main ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = main_ref (value->data[0].v_pointer);
	}
	return NULL;
}

GParamSpec*
param_spec_main (const gchar* name,
                 const gchar* nick,
                 const gchar* blurb,
                 GType object_type,
                 GParamFlags flags)
{
	ParamSpecMain* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_MAIN), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}

gpointer
value_get_main (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_MAIN), NULL);
	return value->data[0].v_pointer;
}

void
value_set_main (GValue* value,
                gpointer v_object)
{
	Main * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_MAIN));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_MAIN));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		main_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		main_unref (old);
	}
}

void
value_take_main (GValue* value,
                 gpointer v_object)
{
	Main * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_MAIN));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_MAIN));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		main_unref (old);
	}
}

static void
main_class_init (MainClass * klass,
                 gpointer klass_data)
{
	main_parent_class = g_type_class_peek_parent (klass);
	((MainClass *) klass)->finalize = main_finalize;
}

static void
main_instance_init (Main * self,
                    gpointer klass)
{
	self->ref_count = 1;
}

static void
main_finalize (Main * obj)
{
	Main * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_MAIN, Main);
	g_signal_handlers_destroy (self);
}

static GType
main_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { value_main_init, value_main_free_value, value_main_copy_value, value_main_peek_pointer, "p", value_main_collect_value, "p", value_main_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (MainClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) main_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Main), 0, (GInstanceInitFunc) main_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType main_type_id;
	main_type_id = g_type_register_fundamental (g_type_fundamental_next (), "Main", &g_define_type_info, &g_define_type_fundamental_info, 0);
	return main_type_id;
}

GType
main_get_type (void)
{
	static volatile gsize main_type_id__once = 0;
	if (g_once_init_enter (&main_type_id__once)) {
		GType main_type_id;
		main_type_id = main_get_type_once ();
		g_once_init_leave (&main_type_id__once, main_type_id);
	}
	return main_type_id__once;
}

gpointer
main_ref (gpointer instance)
{
	Main * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}

void
main_unref (gpointer instance)
{
	Main * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		MAIN_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}

