/* dash-proxy.c generated by valac 0.56.19, the Vala compiler
 * generated from dash-proxy.vala, do not modify */

/*
 * Copyright (C) 2012 Canonical Ltd
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Authored by Pawel Stolowski <pawel.stolowski@canonical.com>
 */

#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>

#define PREVIEW_PLAYER_DASH_DBUS_NAME "com.canonical.Unity"
#define PREVIEW_PLAYER_DASH_DBUS_PATH "/com/canonical/Unity/Dash"
#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define PREVIEW_PLAYER_TYPE_DASH_INTERFACE (preview_player_dash_interface_get_type ())
#define PREVIEW_PLAYER_DASH_INTERFACE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PREVIEW_PLAYER_TYPE_DASH_INTERFACE, PreviewPlayerDashInterface))
#define PREVIEW_PLAYER_IS_DASH_INTERFACE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PREVIEW_PLAYER_TYPE_DASH_INTERFACE))
#define PREVIEW_PLAYER_DASH_INTERFACE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), PREVIEW_PLAYER_TYPE_DASH_INTERFACE, PreviewPlayerDashInterfaceIface))

typedef struct _PreviewPlayerDashInterface PreviewPlayerDashInterface;
typedef struct _PreviewPlayerDashInterfaceIface PreviewPlayerDashInterfaceIface;

#define PREVIEW_PLAYER_TYPE_DASH_INTERFACE_PROXY (preview_player_dash_interface_proxy_get_type ())
typedef GDBusProxy PreviewPlayerDashInterfaceProxy;
typedef GDBusProxyClass PreviewPlayerDashInterfaceProxyClass;
typedef struct _PreviewPlayerDashInterfaceHideDashReadyData PreviewPlayerDashInterfaceHideDashReadyData;

#define PREVIEW_PLAYER_TYPE_DASH_PROXY (preview_player_dash_proxy_get_type ())
#define PREVIEW_PLAYER_DASH_PROXY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PREVIEW_PLAYER_TYPE_DASH_PROXY, PreviewPlayerDashProxy))
#define PREVIEW_PLAYER_DASH_PROXY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PREVIEW_PLAYER_TYPE_DASH_PROXY, PreviewPlayerDashProxyClass))
#define PREVIEW_PLAYER_IS_DASH_PROXY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PREVIEW_PLAYER_TYPE_DASH_PROXY))
#define PREVIEW_PLAYER_IS_DASH_PROXY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PREVIEW_PLAYER_TYPE_DASH_PROXY))
#define PREVIEW_PLAYER_DASH_PROXY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PREVIEW_PLAYER_TYPE_DASH_PROXY, PreviewPlayerDashProxyClass))

typedef struct _PreviewPlayerDashProxy PreviewPlayerDashProxy;
typedef struct _PreviewPlayerDashProxyClass PreviewPlayerDashProxyClass;
typedef struct _PreviewPlayerDashProxyPrivate PreviewPlayerDashProxyPrivate;
enum  {
	PREVIEW_PLAYER_DASH_PROXY_0_PROPERTY,
	PREVIEW_PLAYER_DASH_PROXY_NUM_PROPERTIES
};
static GParamSpec* preview_player_dash_proxy_properties[PREVIEW_PLAYER_DASH_PROXY_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _PreviewPlayerDashProxyConnectToData PreviewPlayerDashProxyConnectToData;
typedef struct _PreviewPlayerDashProxyHideDashData PreviewPlayerDashProxyHideDashData;

struct _PreviewPlayerDashInterfaceIface {
	GTypeInterface parent_iface;
	void (*hide_dash) (PreviewPlayerDashInterface* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
	void (*hide_dash_finish) (PreviewPlayerDashInterface* self, GAsyncResult* _res_, GError** error);
};

struct _PreviewPlayerDashInterfaceHideDashReadyData {
	GDBusMethodInvocation* _invocation_;
};

struct _PreviewPlayerDashProxy {
	GObject parent_instance;
	PreviewPlayerDashProxyPrivate * priv;
};

struct _PreviewPlayerDashProxyClass {
	GObjectClass parent_class;
};

struct _PreviewPlayerDashProxyPrivate {
	PreviewPlayerDashInterface* _dash_interface;
};

struct _PreviewPlayerDashProxyConnectToData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	PreviewPlayerDashProxy* self;
	PreviewPlayerDashInterface* _tmp0_;
	PreviewPlayerDashInterface* _tmp1_;
	PreviewPlayerDashInterface* _tmp2_;
	GError* _inner_error0_;
};

struct _PreviewPlayerDashProxyHideDashData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	PreviewPlayerDashProxy* self;
	PreviewPlayerDashInterface* _tmp0_;
	PreviewPlayerDashInterface* _tmp1_;
	GError* _inner_error0_;
};

static gint PreviewPlayerDashProxy_private_offset;
static gpointer preview_player_dash_proxy_parent_class = NULL;

VALA_EXTERN GType preview_player_dash_interface_proxy_get_type (void) G_GNUC_CONST ;
VALA_EXTERN guint preview_player_dash_interface_register_object (void* object,
                                                     GDBusConnection* connection,
                                                     const gchar* path,
                                                     GError** error);
VALA_EXTERN GType preview_player_dash_interface_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (PreviewPlayerDashInterface, g_object_unref)
VALA_EXTERN void preview_player_dash_interface_hide_dash (PreviewPlayerDashInterface* self,
                                              GAsyncReadyCallback _callback_,
                                              gpointer _user_data_);
VALA_EXTERN void preview_player_dash_interface_hide_dash_finish (PreviewPlayerDashInterface* self,
                                                     GAsyncResult* _res_,
                                                     GError** error);
static GType preview_player_dash_interface_get_type_once (void);
static void preview_player_dash_interface_proxy_g_signal (GDBusProxy* proxy,
                                                   const gchar* sender_name,
                                                   const gchar* signal_name,
                                                   GVariant* parameters);
static void _vala_g_async_ready_callback (GObject *source_object,
                                   GAsyncResult *res,
                                   void *user_data);
static void preview_player_dash_interface_proxy_hide_dash_async (PreviewPlayerDashInterface* self,
                                                          GAsyncReadyCallback _callback_,
                                                          gpointer _user_data_);
static void preview_player_dash_interface_proxy_hide_dash_finish (PreviewPlayerDashInterface* self,
                                                           GAsyncResult* _res_,
                                                           GError** error);
static void preview_player_dash_interface_proxy_preview_player_dash_interface_interface_init (PreviewPlayerDashInterfaceIface* iface);
static void _dbus_preview_player_dash_interface_hide_dash (PreviewPlayerDashInterface* self,
                                                    GVariant* _parameters_,
                                                    GDBusMethodInvocation* invocation);
static void _dbus_preview_player_dash_interface_hide_dash_ready (GObject * source_object,
                                                          GAsyncResult * _res_,
                                                          gpointer _user_data_);
static void preview_player_dash_interface_dbus_interface_method_call (GDBusConnection* connection,
                                                               const gchar* sender,
                                                               const gchar* object_path,
                                                               const gchar* interface_name,
                                                               const gchar* method_name,
                                                               GVariant* parameters,
                                                               GDBusMethodInvocation* invocation,
                                                               gpointer user_data);
static GVariant* preview_player_dash_interface_dbus_interface_get_property (GDBusConnection* connection,
                                                                     const gchar* sender,
                                                                     const gchar* object_path,
                                                                     const gchar* interface_name,
                                                                     const gchar* property_name,
                                                                     GError** error,
                                                                     gpointer user_data);
static gboolean preview_player_dash_interface_dbus_interface_set_property (GDBusConnection* connection,
                                                                    const gchar* sender,
                                                                    const gchar* object_path,
                                                                    const gchar* interface_name,
                                                                    const gchar* property_name,
                                                                    GVariant* value,
                                                                    GError** error,
                                                                    gpointer user_data);
static void _preview_player_dash_interface_unregister_object (gpointer user_data);
VALA_EXTERN GType preview_player_dash_proxy_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (PreviewPlayerDashProxy, g_object_unref)
static void preview_player_dash_proxy_connect_to_data_free (gpointer _data);
VALA_EXTERN void preview_player_dash_proxy_connect_to (PreviewPlayerDashProxy* self,
                                           GAsyncReadyCallback _callback_,
                                           gpointer _user_data_);
VALA_EXTERN void preview_player_dash_proxy_connect_to_finish (PreviewPlayerDashProxy* self,
                                                  GAsyncResult* _res_,
                                                  GError** error);
static gboolean preview_player_dash_proxy_connect_to_co (PreviewPlayerDashProxyConnectToData* _data_);
static void preview_player_dash_proxy_hide_dash_data_free (gpointer _data);
VALA_EXTERN void preview_player_dash_proxy_hide_dash (PreviewPlayerDashProxy* self,
                                          GAsyncReadyCallback _callback_,
                                          gpointer _user_data_);
VALA_EXTERN void preview_player_dash_proxy_hide_dash_finish (PreviewPlayerDashProxy* self,
                                                 GAsyncResult* _res_,
                                                 GError** error);
static gboolean preview_player_dash_proxy_hide_dash_co (PreviewPlayerDashProxyHideDashData* _data_);
static void preview_player_dash_proxy_hide_dash_ready (GObject* source_object,
                                                GAsyncResult* _res_,
                                                gpointer _user_data_);
VALA_EXTERN PreviewPlayerDashProxy* preview_player_dash_proxy_new (void);
VALA_EXTERN PreviewPlayerDashProxy* preview_player_dash_proxy_construct (GType object_type);
static void preview_player_dash_proxy_finalize (GObject * obj);
static GType preview_player_dash_proxy_get_type_once (void);

static const GDBusArgInfo * const _preview_player_dash_interface_dbus_arg_info_hide_dash_in[] = {NULL};
static const GDBusArgInfo * const _preview_player_dash_interface_dbus_arg_info_hide_dash_out[] = {NULL};
static const GDBusMethodInfo _preview_player_dash_interface_dbus_method_info_hide_dash = {-1, "HideDash", (GDBusArgInfo **) (&_preview_player_dash_interface_dbus_arg_info_hide_dash_in), (GDBusArgInfo **) (&_preview_player_dash_interface_dbus_arg_info_hide_dash_out), NULL};
static const GDBusMethodInfo * const _preview_player_dash_interface_dbus_method_info[] = {&_preview_player_dash_interface_dbus_method_info_hide_dash, NULL};
static const GDBusSignalInfo * const _preview_player_dash_interface_dbus_signal_info[] = {NULL};
static const GDBusPropertyInfo * const _preview_player_dash_interface_dbus_property_info[] = {NULL};
static const GDBusInterfaceInfo _preview_player_dash_interface_dbus_interface_info = {-1, "com.canonical.Unity.Dash", (GDBusMethodInfo **) (&_preview_player_dash_interface_dbus_method_info), (GDBusSignalInfo **) (&_preview_player_dash_interface_dbus_signal_info), (GDBusPropertyInfo **) (&_preview_player_dash_interface_dbus_property_info), NULL};
static const GDBusInterfaceVTable _preview_player_dash_interface_dbus_interface_vtable = {preview_player_dash_interface_dbus_interface_method_call, preview_player_dash_interface_dbus_interface_get_property, preview_player_dash_interface_dbus_interface_set_property};

void
preview_player_dash_interface_hide_dash (PreviewPlayerDashInterface* self,
                                         GAsyncReadyCallback _callback_,
                                         gpointer _user_data_)
{
	PreviewPlayerDashInterfaceIface* _iface_;
	_iface_ = PREVIEW_PLAYER_DASH_INTERFACE_GET_INTERFACE (self);
	if (_iface_->hide_dash) {
		_iface_->hide_dash (self, _callback_, _user_data_);
	}
}

void
preview_player_dash_interface_hide_dash_finish (PreviewPlayerDashInterface* self,
                                                GAsyncResult* _res_,
                                                GError** error)
{
	PreviewPlayerDashInterfaceIface* _iface_;
	_iface_ = PREVIEW_PLAYER_DASH_INTERFACE_GET_INTERFACE (self);
	if (_iface_->hide_dash_finish) {
		_iface_->hide_dash_finish (self, _res_, error);
	}
}

static void
preview_player_dash_interface_default_init (PreviewPlayerDashInterfaceIface * iface,
                                            gpointer iface_data)
{
}

static GType
preview_player_dash_interface_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (PreviewPlayerDashInterfaceIface), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) preview_player_dash_interface_default_init, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
	GType preview_player_dash_interface_type_id;
	preview_player_dash_interface_type_id = g_type_register_static (G_TYPE_INTERFACE, "PreviewPlayerDashInterface", &g_define_type_info, 0);
	g_type_interface_add_prerequisite (preview_player_dash_interface_type_id, G_TYPE_OBJECT);
	g_type_set_qdata (preview_player_dash_interface_type_id, g_quark_from_static_string ("vala-dbus-proxy-type"), (void*) preview_player_dash_interface_proxy_get_type);
	g_type_set_qdata (preview_player_dash_interface_type_id, g_quark_from_static_string ("vala-dbus-interface-name"), "com.canonical.Unity.Dash");
	g_type_set_qdata (preview_player_dash_interface_type_id, g_quark_from_static_string ("vala-dbus-interface-info"), (void*) (&_preview_player_dash_interface_dbus_interface_info));
	g_type_set_qdata (preview_player_dash_interface_type_id, g_quark_from_static_string ("vala-dbus-register-object"), (void*) preview_player_dash_interface_register_object);
	return preview_player_dash_interface_type_id;
}

GType
preview_player_dash_interface_get_type (void)
{
	static volatile gsize preview_player_dash_interface_type_id__once = 0;
	if (g_once_init_enter (&preview_player_dash_interface_type_id__once)) {
		GType preview_player_dash_interface_type_id;
		preview_player_dash_interface_type_id = preview_player_dash_interface_get_type_once ();
		g_once_init_leave (&preview_player_dash_interface_type_id__once, preview_player_dash_interface_type_id);
	}
	return preview_player_dash_interface_type_id__once;
}

G_DEFINE_TYPE_EXTENDED (PreviewPlayerDashInterfaceProxy, preview_player_dash_interface_proxy, G_TYPE_DBUS_PROXY, 0, G_IMPLEMENT_INTERFACE (PREVIEW_PLAYER_TYPE_DASH_INTERFACE, preview_player_dash_interface_proxy_preview_player_dash_interface_interface_init) )
static void
preview_player_dash_interface_proxy_class_init (PreviewPlayerDashInterfaceProxyClass* klass)
{
	G_DBUS_PROXY_CLASS (klass)->g_signal = preview_player_dash_interface_proxy_g_signal;
}

static void
preview_player_dash_interface_proxy_g_signal (GDBusProxy* proxy,
                                              const gchar* sender_name,
                                              const gchar* signal_name,
                                              GVariant* parameters)
{
}

static void
preview_player_dash_interface_proxy_init (PreviewPlayerDashInterfaceProxy* self)
{
	g_dbus_proxy_set_interface_info (G_DBUS_PROXY (self), (GDBusInterfaceInfo *) (&_preview_player_dash_interface_dbus_interface_info));
}

static void
_vala_g_async_ready_callback (GObject *source_object,
                              GAsyncResult *res,
                              void *user_data)
{
	g_task_return_pointer (user_data, g_object_ref (res), g_object_unref);
	g_object_unref (user_data);
}

static void
preview_player_dash_interface_proxy_hide_dash_async (PreviewPlayerDashInterface* self,
                                                     GAsyncReadyCallback _callback_,
                                                     gpointer _user_data_)
{
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "com.canonical.Unity.Dash", "HideDash");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	if (_callback_ != NULL) {
		g_dbus_connection_send_message_with_reply (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, _vala_g_async_ready_callback, g_task_new ((GObject *) self, NULL, _callback_, _user_data_));
	} else {
		g_dbus_message_set_flags (_message, G_DBUS_MESSAGE_FLAGS_NO_REPLY_EXPECTED);
		g_dbus_connection_send_message (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	}
	g_object_unref (_message);
}

static void
preview_player_dash_interface_proxy_hide_dash_finish (PreviewPlayerDashInterface* self,
                                                      GAsyncResult* _res_,
                                                      GError** error)
{
	GAsyncResult *_inner_res;
	GDBusMessage *_reply_message;
	_inner_res = g_task_propagate_pointer ((GTask *) _res_, NULL);
	_reply_message = g_dbus_connection_send_message_with_reply_finish (g_dbus_proxy_get_connection ((GDBusProxy *) self), _inner_res, error);
	g_object_unref (_inner_res);
	if (!_reply_message) {
		return;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return;
	}
	g_object_unref (_reply_message);
}

static void
preview_player_dash_interface_proxy_preview_player_dash_interface_interface_init (PreviewPlayerDashInterfaceIface* iface)
{
	iface->hide_dash = preview_player_dash_interface_proxy_hide_dash_async;
	iface->hide_dash_finish = preview_player_dash_interface_proxy_hide_dash_finish;
}

static void
_dbus_preview_player_dash_interface_hide_dash (PreviewPlayerDashInterface* self,
                                               GVariant* _parameters_,
                                               GDBusMethodInvocation* invocation)
{
	GVariantIter _arguments_iter;
	PreviewPlayerDashInterfaceHideDashReadyData* _ready_data;
	g_variant_iter_init (&_arguments_iter, _parameters_);
	_ready_data = g_slice_new0 (PreviewPlayerDashInterfaceHideDashReadyData);
	_ready_data->_invocation_ = invocation;
	preview_player_dash_interface_hide_dash (self, (GAsyncReadyCallback) _dbus_preview_player_dash_interface_hide_dash_ready, _ready_data);
}

static void
_dbus_preview_player_dash_interface_hide_dash_ready (GObject * source_object,
                                                     GAsyncResult * _res_,
                                                     gpointer _user_data_)
{
	PreviewPlayerDashInterfaceHideDashReadyData* _ready_data;
	GDBusMethodInvocation* invocation;
	GError* error = NULL;
	GDBusMessage* _reply_message = NULL;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	_ready_data = _user_data_;
	invocation = _ready_data->_invocation_;
	preview_player_dash_interface_hide_dash_finish ((PreviewPlayerDashInterface*) source_object, _res_, &error);
	if (error) {
		g_dbus_method_invocation_take_error (invocation, error);
		goto _error;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
	_error:
	g_slice_free (PreviewPlayerDashInterfaceHideDashReadyData, _ready_data);
}

static void
preview_player_dash_interface_dbus_interface_method_call (GDBusConnection* connection,
                                                          const gchar* sender,
                                                          const gchar* object_path,
                                                          const gchar* interface_name,
                                                          const gchar* method_name,
                                                          GVariant* parameters,
                                                          GDBusMethodInvocation* invocation,
                                                          gpointer user_data)
{
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (method_name, "HideDash") == 0) {
		_dbus_preview_player_dash_interface_hide_dash (object, parameters, invocation);
	} else {
		g_object_unref (invocation);
	}
}

static GVariant*
preview_player_dash_interface_dbus_interface_get_property (GDBusConnection* connection,
                                                           const gchar* sender,
                                                           const gchar* object_path,
                                                           const gchar* interface_name,
                                                           const gchar* property_name,
                                                           GError** error,
                                                           gpointer user_data)
{
	return NULL;
}

static gboolean
preview_player_dash_interface_dbus_interface_set_property (GDBusConnection* connection,
                                                           const gchar* sender,
                                                           const gchar* object_path,
                                                           const gchar* interface_name,
                                                           const gchar* property_name,
                                                           GVariant* value,
                                                           GError** error,
                                                           gpointer user_data)
{
	return FALSE;
}

guint
preview_player_dash_interface_register_object (gpointer object,
                                               GDBusConnection* connection,
                                               const gchar* path,
                                               GError** error)
{
	guint result;
	gpointer *data;
	data = g_new (gpointer, 3);
	data[0] = g_object_ref (object);
	data[1] = g_object_ref (connection);
	data[2] = g_strdup (path);
	result = g_dbus_connection_register_object (connection, path, (GDBusInterfaceInfo *) (&_preview_player_dash_interface_dbus_interface_info), &_preview_player_dash_interface_dbus_interface_vtable, data, _preview_player_dash_interface_unregister_object, error);
	if (!result) {
		return 0;
	}
	return result;
}

static void
_preview_player_dash_interface_unregister_object (gpointer user_data)
{
	gpointer* data;
	data = user_data;
	g_object_unref (data[0]);
	g_object_unref (data[1]);
	g_free (data[2]);
	g_free (data);
}

static inline gpointer
preview_player_dash_proxy_get_instance_private (PreviewPlayerDashProxy* self)
{
	return G_STRUCT_MEMBER_P (self, PreviewPlayerDashProxy_private_offset);
}

static void
preview_player_dash_proxy_connect_to_data_free (gpointer _data)
{
	PreviewPlayerDashProxyConnectToData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->self);
	g_slice_free (PreviewPlayerDashProxyConnectToData, _data_);
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

void
preview_player_dash_proxy_connect_to (PreviewPlayerDashProxy* self,
                                      GAsyncReadyCallback _callback_,
                                      gpointer _user_data_)
{
	PreviewPlayerDashProxyConnectToData* _data_;
	PreviewPlayerDashProxy* _tmp0_;
	g_return_if_fail (self != NULL);
	_data_ = g_slice_new0 (PreviewPlayerDashProxyConnectToData);
	_data_->_async_result = g_task_new (G_OBJECT (self), NULL, _callback_, _user_data_);
	g_task_set_task_data (_data_->_async_result, _data_, preview_player_dash_proxy_connect_to_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	preview_player_dash_proxy_connect_to_co (_data_);
}

void
preview_player_dash_proxy_connect_to_finish (PreviewPlayerDashProxy* self,
                                             GAsyncResult* _res_,
                                             GError** error)
{
	PreviewPlayerDashProxyConnectToData* _data_;
	_data_ = g_task_propagate_pointer (G_TASK (_res_), error);
	if (NULL == _data_) {
		return;
	}
}

static gboolean
preview_player_dash_proxy_connect_to_co (PreviewPlayerDashProxyConnectToData* _data_)
{
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp1_ = (PreviewPlayerDashInterface*) g_initable_new (PREVIEW_PLAYER_TYPE_DASH_INTERFACE_PROXY, NULL, &_data_->_inner_error0_, "g-flags", 0, "g-name", PREVIEW_PLAYER_DASH_DBUS_NAME, "g-bus-type", G_BUS_TYPE_SESSION, "g-object-path", PREVIEW_PLAYER_DASH_DBUS_PATH, "g-interface-name", "com.canonical.Unity.Dash", NULL);
	_data_->_tmp0_ = (PreviewPlayerDashInterface*) _data_->_tmp1_;
	if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
		g_task_return_error (_data_->_async_result, _data_->_inner_error0_);
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	_data_->_tmp2_ = _data_->_tmp0_;
	_data_->_tmp0_ = NULL;
	_g_object_unref0 (_data_->self->priv->_dash_interface);
	_data_->self->priv->_dash_interface = _data_->_tmp2_;
	_g_object_unref0 (_data_->_tmp0_);
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
	if (_data_->_state_ != 0) {
		while (!g_task_get_completed (_data_->_async_result)) {
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
		}
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}

static void
preview_player_dash_proxy_hide_dash_data_free (gpointer _data)
{
	PreviewPlayerDashProxyHideDashData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->self);
	g_slice_free (PreviewPlayerDashProxyHideDashData, _data_);
}

void
preview_player_dash_proxy_hide_dash (PreviewPlayerDashProxy* self,
                                     GAsyncReadyCallback _callback_,
                                     gpointer _user_data_)
{
	PreviewPlayerDashProxyHideDashData* _data_;
	PreviewPlayerDashProxy* _tmp0_;
	g_return_if_fail (self != NULL);
	_data_ = g_slice_new0 (PreviewPlayerDashProxyHideDashData);
	_data_->_async_result = g_task_new (G_OBJECT (self), NULL, _callback_, _user_data_);
	g_task_set_task_data (_data_->_async_result, _data_, preview_player_dash_proxy_hide_dash_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	preview_player_dash_proxy_hide_dash_co (_data_);
}

void
preview_player_dash_proxy_hide_dash_finish (PreviewPlayerDashProxy* self,
                                            GAsyncResult* _res_,
                                            GError** error)
{
	PreviewPlayerDashProxyHideDashData* _data_;
	_data_ = g_task_propagate_pointer (G_TASK (_res_), error);
	if (NULL == _data_) {
		return;
	}
}

static void
preview_player_dash_proxy_hide_dash_ready (GObject* source_object,
                                           GAsyncResult* _res_,
                                           gpointer _user_data_)
{
	PreviewPlayerDashProxyHideDashData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	preview_player_dash_proxy_hide_dash_co (_data_);
}

static gboolean
preview_player_dash_proxy_hide_dash_co (PreviewPlayerDashProxyHideDashData* _data_)
{
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		case 2:
		goto _state_2;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp0_ = _data_->self->priv->_dash_interface;
	if (_data_->_tmp0_ == NULL) {
		_data_->_state_ = 1;
		preview_player_dash_proxy_connect_to (_data_->self, preview_player_dash_proxy_hide_dash_ready, _data_);
		return FALSE;
		_state_1:
		preview_player_dash_proxy_connect_to_finish (_data_->self, _data_->_res_, &_data_->_inner_error0_);
		if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
			g_task_return_error (_data_->_async_result, _data_->_inner_error0_);
			g_object_unref (_data_->_async_result);
			return FALSE;
		}
	}
	_data_->_tmp1_ = _data_->self->priv->_dash_interface;
	_data_->_state_ = 2;
	preview_player_dash_interface_hide_dash (_data_->_tmp1_, preview_player_dash_proxy_hide_dash_ready, _data_);
	return FALSE;
	_state_2:
	preview_player_dash_interface_hide_dash_finish (_data_->_tmp1_, _data_->_res_, &_data_->_inner_error0_);
	if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
		g_task_return_error (_data_->_async_result, _data_->_inner_error0_);
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
	if (_data_->_state_ != 0) {
		while (!g_task_get_completed (_data_->_async_result)) {
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
		}
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}

PreviewPlayerDashProxy*
preview_player_dash_proxy_construct (GType object_type)
{
	PreviewPlayerDashProxy * self = NULL;
	self = (PreviewPlayerDashProxy*) g_object_new (object_type, NULL);
	return self;
}

PreviewPlayerDashProxy*
preview_player_dash_proxy_new (void)
{
	return preview_player_dash_proxy_construct (PREVIEW_PLAYER_TYPE_DASH_PROXY);
}

static void
preview_player_dash_proxy_class_init (PreviewPlayerDashProxyClass * klass,
                                      gpointer klass_data)
{
	preview_player_dash_proxy_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &PreviewPlayerDashProxy_private_offset);
	G_OBJECT_CLASS (klass)->finalize = preview_player_dash_proxy_finalize;
}

static void
preview_player_dash_proxy_instance_init (PreviewPlayerDashProxy * self,
                                         gpointer klass)
{
	self->priv = preview_player_dash_proxy_get_instance_private (self);
}

static void
preview_player_dash_proxy_finalize (GObject * obj)
{
	PreviewPlayerDashProxy * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PREVIEW_PLAYER_TYPE_DASH_PROXY, PreviewPlayerDashProxy);
	_g_object_unref0 (self->priv->_dash_interface);
	G_OBJECT_CLASS (preview_player_dash_proxy_parent_class)->finalize (obj);
}

static GType
preview_player_dash_proxy_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (PreviewPlayerDashProxyClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) preview_player_dash_proxy_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PreviewPlayerDashProxy), 0, (GInstanceInitFunc) preview_player_dash_proxy_instance_init, NULL };
	GType preview_player_dash_proxy_type_id;
	preview_player_dash_proxy_type_id = g_type_register_static (G_TYPE_OBJECT, "PreviewPlayerDashProxy", &g_define_type_info, 0);
	PreviewPlayerDashProxy_private_offset = g_type_add_instance_private (preview_player_dash_proxy_type_id, sizeof (PreviewPlayerDashProxyPrivate));
	return preview_player_dash_proxy_type_id;
}

GType
preview_player_dash_proxy_get_type (void)
{
	static volatile gsize preview_player_dash_proxy_type_id__once = 0;
	if (g_once_init_enter (&preview_player_dash_proxy_type_id__once)) {
		GType preview_player_dash_proxy_type_id;
		preview_player_dash_proxy_type_id = preview_player_dash_proxy_get_type_once ();
		g_once_init_leave (&preview_player_dash_proxy_type_id__once, preview_player_dash_proxy_type_id);
	}
	return preview_player_dash_proxy_type_id__once;
}

