/* rhythmbox-scope.c generated by valac 0.56.19, the Vala compiler
 * generated from rhythmbox-scope.vala, do not modify */

/*
 * Copyright (C) 2011 Canonical Ltd
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Authored by Alex Launi <alex.launi@canonical.com>
 *
 */

#include <glib-object.h>
#include <gio/gio.h>
#include <unity.h>
#include <glib.h>
#include <glib/gi18n-lib.h>
#include <stdlib.h>
#include <string.h>
#include <unity-extras.h>

#define CONFIG_PKGDATADIR "/usr/share/unity"
#define UNITY_MUSIC_LENS_UNITY_ICON_PATH CONFIG_PKGDATADIR "/icons"
#define UNITY_MUSIC_LENS_ALBUM_MISSING_PREVIEW_ICON_PATH UNITY_MUSIC_LENS_UNITY_ICON_PATH "/album_missing_preview.png"
#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define UNITY_MUSIC_LENS_TYPE_SIMPLE_SCOPE (unity_music_lens_simple_scope_get_type ())
#define UNITY_MUSIC_LENS_SIMPLE_SCOPE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), UNITY_MUSIC_LENS_TYPE_SIMPLE_SCOPE, UnityMusicLensSimpleScope))
#define UNITY_MUSIC_LENS_SIMPLE_SCOPE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), UNITY_MUSIC_LENS_TYPE_SIMPLE_SCOPE, UnityMusicLensSimpleScopeClass))
#define UNITY_MUSIC_LENS_IS_SIMPLE_SCOPE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), UNITY_MUSIC_LENS_TYPE_SIMPLE_SCOPE))
#define UNITY_MUSIC_LENS_IS_SIMPLE_SCOPE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), UNITY_MUSIC_LENS_TYPE_SIMPLE_SCOPE))
#define UNITY_MUSIC_LENS_SIMPLE_SCOPE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), UNITY_MUSIC_LENS_TYPE_SIMPLE_SCOPE, UnityMusicLensSimpleScopeClass))

typedef struct _UnityMusicLensSimpleScope UnityMusicLensSimpleScope;
typedef struct _UnityMusicLensSimpleScopeClass UnityMusicLensSimpleScopeClass;
typedef struct _UnityMusicLensSimpleScopePrivate UnityMusicLensSimpleScopePrivate;

#define UNITY_MUSIC_LENS_TYPE_FILTER_PARSER (unity_music_lens_filter_parser_get_type ())
#define UNITY_MUSIC_LENS_FILTER_PARSER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), UNITY_MUSIC_LENS_TYPE_FILTER_PARSER, UnityMusicLensFilterParser))
#define UNITY_MUSIC_LENS_FILTER_PARSER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), UNITY_MUSIC_LENS_TYPE_FILTER_PARSER, UnityMusicLensFilterParserClass))
#define UNITY_MUSIC_LENS_IS_FILTER_PARSER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), UNITY_MUSIC_LENS_TYPE_FILTER_PARSER))
#define UNITY_MUSIC_LENS_IS_FILTER_PARSER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), UNITY_MUSIC_LENS_TYPE_FILTER_PARSER))
#define UNITY_MUSIC_LENS_FILTER_PARSER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), UNITY_MUSIC_LENS_TYPE_FILTER_PARSER, UnityMusicLensFilterParserClass))

typedef struct _UnityMusicLensFilterParser UnityMusicLensFilterParser;
typedef struct _UnityMusicLensFilterParserClass UnityMusicLensFilterParserClass;

#define UNITY_MUSIC_LENS_TYPE_RHYTHMBOX_SCOPE (unity_music_lens_rhythmbox_scope_get_type ())
#define UNITY_MUSIC_LENS_RHYTHMBOX_SCOPE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), UNITY_MUSIC_LENS_TYPE_RHYTHMBOX_SCOPE, UnityMusicLensRhythmboxScope))
#define UNITY_MUSIC_LENS_RHYTHMBOX_SCOPE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), UNITY_MUSIC_LENS_TYPE_RHYTHMBOX_SCOPE, UnityMusicLensRhythmboxScopeClass))
#define UNITY_MUSIC_LENS_IS_RHYTHMBOX_SCOPE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), UNITY_MUSIC_LENS_TYPE_RHYTHMBOX_SCOPE))
#define UNITY_MUSIC_LENS_IS_RHYTHMBOX_SCOPE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), UNITY_MUSIC_LENS_TYPE_RHYTHMBOX_SCOPE))
#define UNITY_MUSIC_LENS_RHYTHMBOX_SCOPE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), UNITY_MUSIC_LENS_TYPE_RHYTHMBOX_SCOPE, UnityMusicLensRhythmboxScopeClass))

typedef struct _UnityMusicLensRhythmboxScope UnityMusicLensRhythmboxScope;
typedef struct _UnityMusicLensRhythmboxScopeClass UnityMusicLensRhythmboxScopeClass;
typedef struct _UnityMusicLensRhythmboxScopePrivate UnityMusicLensRhythmboxScopePrivate;

#define UNITY_MUSIC_LENS_TYPE_RHYTHMBOX_COLLECTION (unity_music_lens_rhythmbox_collection_get_type ())
#define UNITY_MUSIC_LENS_RHYTHMBOX_COLLECTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), UNITY_MUSIC_LENS_TYPE_RHYTHMBOX_COLLECTION, UnityMusicLensRhythmboxCollection))
#define UNITY_MUSIC_LENS_RHYTHMBOX_COLLECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), UNITY_MUSIC_LENS_TYPE_RHYTHMBOX_COLLECTION, UnityMusicLensRhythmboxCollectionClass))
#define UNITY_MUSIC_LENS_IS_RHYTHMBOX_COLLECTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), UNITY_MUSIC_LENS_TYPE_RHYTHMBOX_COLLECTION))
#define UNITY_MUSIC_LENS_IS_RHYTHMBOX_COLLECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), UNITY_MUSIC_LENS_TYPE_RHYTHMBOX_COLLECTION))
#define UNITY_MUSIC_LENS_RHYTHMBOX_COLLECTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), UNITY_MUSIC_LENS_TYPE_RHYTHMBOX_COLLECTION, UnityMusicLensRhythmboxCollectionClass))

typedef struct _UnityMusicLensRhythmboxCollection UnityMusicLensRhythmboxCollection;
typedef struct _UnityMusicLensRhythmboxCollectionClass UnityMusicLensRhythmboxCollectionClass;
enum  {
	UNITY_MUSIC_LENS_RHYTHMBOX_SCOPE_0_PROPERTY,
	UNITY_MUSIC_LENS_RHYTHMBOX_SCOPE_NUM_RESULTS_WITHOUT_SEARCH_PROPERTY,
	UNITY_MUSIC_LENS_RHYTHMBOX_SCOPE_NUM_RESULTS_GLOBAL_SEARCH_PROPERTY,
	UNITY_MUSIC_LENS_RHYTHMBOX_SCOPE_NUM_RESULTS_LENS_SEARCH_PROPERTY,
	UNITY_MUSIC_LENS_RHYTHMBOX_SCOPE_NUM_PROPERTIES
};
static GParamSpec* unity_music_lens_rhythmbox_scope_properties[UNITY_MUSIC_LENS_RHYTHMBOX_SCOPE_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _Block1Data Block1Data;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_thread_unref0(var) ((var == NULL) ? NULL : (var = (g_thread_unref (var), NULL)))
typedef struct _UnityMusicLensRhythmboxScopePrepareRhythmboxPlayQueueData UnityMusicLensRhythmboxScopePrepareRhythmboxPlayQueueData;
#define _g_free0(var) (var = (g_free (var), NULL))

#define UNITY_MUSIC_LENS_TYPE_TRACK (unity_music_lens_track_get_type ())
#define UNITY_MUSIC_LENS_TRACK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), UNITY_MUSIC_LENS_TYPE_TRACK, UnityMusicLensTrack))
#define UNITY_MUSIC_LENS_TRACK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), UNITY_MUSIC_LENS_TYPE_TRACK, UnityMusicLensTrackClass))
#define UNITY_MUSIC_LENS_IS_TRACK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), UNITY_MUSIC_LENS_TYPE_TRACK))
#define UNITY_MUSIC_LENS_IS_TRACK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), UNITY_MUSIC_LENS_TYPE_TRACK))
#define UNITY_MUSIC_LENS_TRACK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), UNITY_MUSIC_LENS_TYPE_TRACK, UnityMusicLensTrackClass))

typedef struct _UnityMusicLensTrack UnityMusicLensTrack;
typedef struct _UnityMusicLensTrackClass UnityMusicLensTrackClass;
typedef enum  {
	UNITY_MUSIC_LENS_CATEGORY_MUSIC,
	UNITY_MUSIC_LENS_CATEGORY_SONGS,
	UNITY_MUSIC_LENS_CATEGORY_ALBUMS,
	UNITY_MUSIC_LENS_CATEGORY_RADIOS
} UnityMusicLensCategory;

#define UNITY_MUSIC_LENS_TYPE_CATEGORY (unity_music_lens_category_get_type ())
typedef struct _UnityMusicLensRhythmboxScopePerformSearchData UnityMusicLensRhythmboxScopePerformSearchData;

struct _UnityMusicLensSimpleScope {
	GObject parent_instance;
	UnityMusicLensSimpleScopePrivate * priv;
};

struct _UnityMusicLensSimpleScopeClass {
	GObjectClass parent_class;
	void (*perform_search) (UnityMusicLensSimpleScope* self, UnityDeprecatedScopeSearch* search, UnitySearchType search_type, GList* filters, gint max_results, GCancellable* cancellable, GAsyncReadyCallback _callback_, gpointer _user_data_);
	void (*perform_search_finish) (UnityMusicLensSimpleScope* self, GAsyncResult* _res_);
	gint (*get_num_results_without_search) (UnityMusicLensSimpleScope* self);
	gint (*get_num_results_global_search) (UnityMusicLensSimpleScope* self);
	gint (*get_num_results_lens_search) (UnityMusicLensSimpleScope* self);
};

struct _UnityMusicLensRhythmboxScope {
	UnityMusicLensSimpleScope parent_instance;
	UnityMusicLensRhythmboxScopePrivate * priv;
};

struct _UnityMusicLensRhythmboxScopeClass {
	UnityMusicLensSimpleScopeClass parent_class;
};

struct _UnityMusicLensRhythmboxScopePrivate {
	UnityMusicLensRhythmboxCollection* collection;
	gboolean db_ready;
	GFileMonitor* rb_xml_monitor;
	UnityMusicPreview* music_preview;
};

struct _Block1Data {
	int _ref_count_;
	UnityMusicLensRhythmboxScope* self;
	gchar** main_exec;
	gint main_exec_length1;
	gint _main_exec_size_;
	gpointer _async_data_;
};

struct _UnityMusicLensRhythmboxScopePrepareRhythmboxPlayQueueData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	UnityMusicLensRhythmboxScope* self;
	gchar** exec_args;
	gint exec_args_length1;
	Block1Data* _data1_;
	gchar** _tmp0_;
	gint _tmp0__length1;
	GThread* _tmp1_;
	GThread* _tmp2_;
	GError* err;
	GError* _tmp3_;
	const gchar* _tmp4_;
	GError* _inner_error0_;
};

struct _UnityMusicLensRhythmboxScopePerformSearchData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	UnityMusicLensRhythmboxScope* self;
	UnityDeprecatedScopeSearch* search;
	UnitySearchType search_type;
	GList* filters;
	gint max_results;
	GCancellable* cancellable;
	gint category_override;
	gchar* tdb_path;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	UnityMusicLensRhythmboxCollection* _tmp2_;
	const gchar* _tmp3_;
	gchar* xml_path;
	const gchar* _tmp4_;
	gchar* _tmp5_;
	UnityMusicLensRhythmboxCollection* _tmp6_;
	const gchar* _tmp7_;
	GFileMonitor* _tmp8_;
	GFile* xml_file;
	const gchar* _tmp9_;
	GFile* _tmp10_;
	GFileMonitor* _tmp11_;
	GFile* _tmp12_;
	GFileMonitor* _tmp13_;
	GFileMonitor* _tmp14_;
	GFileMonitor* _tmp15_;
	GError* err;
	GError* _tmp16_;
	const gchar* _tmp17_;
	UnityMusicLensRhythmboxCollection* _tmp18_;
	GError* _inner_error0_;
};

static gint UnityMusicLensRhythmboxScope_private_offset;
static gpointer unity_music_lens_rhythmbox_scope_parent_class = NULL;

VALA_EXTERN GType unity_music_lens_simple_scope_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (UnityMusicLensSimpleScope, g_object_unref)
VALA_EXTERN GType unity_music_lens_filter_parser_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (UnityMusicLensFilterParser, g_object_unref)
VALA_EXTERN GType unity_music_lens_rhythmbox_scope_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (UnityMusicLensRhythmboxScope, g_object_unref)
VALA_EXTERN GType unity_music_lens_rhythmbox_collection_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (UnityMusicLensRhythmboxCollection, g_object_unref)
VALA_EXTERN void unity_music_lens_simple_scope_perform_search (UnityMusicLensSimpleScope* self,
                                                   UnityDeprecatedScopeSearch* search,
                                                   UnitySearchType search_type,
                                                   GList* filters,
                                                   gint max_results,
                                                   GCancellable* cancellable,
                                                   GAsyncReadyCallback _callback_,
                                                   gpointer _user_data_);
VALA_EXTERN void unity_music_lens_simple_scope_perform_search_finish (UnityMusicLensSimpleScope* self,
                                                          GAsyncResult* _res_);
VALA_EXTERN gint unity_music_lens_simple_scope_get_num_results_without_search (UnityMusicLensSimpleScope* self);
VALA_EXTERN gint unity_music_lens_simple_scope_get_num_results_global_search (UnityMusicLensSimpleScope* self);
VALA_EXTERN gint unity_music_lens_simple_scope_get_num_results_lens_search (UnityMusicLensSimpleScope* self);
VALA_EXTERN UnityMusicLensRhythmboxScope* unity_music_lens_rhythmbox_scope_new (void);
VALA_EXTERN UnityMusicLensRhythmboxScope* unity_music_lens_rhythmbox_scope_construct (GType object_type);
VALA_EXTERN UnityMusicLensSimpleScope* unity_music_lens_simple_scope_construct (GType object_type);
VALA_EXTERN void unity_music_lens_simple_scope_set_scope (UnityMusicLensSimpleScope* self,
                                              UnityDeprecatedScope* value);
VALA_EXTERN UnityDeprecatedScope* unity_music_lens_simple_scope_get_scope (UnityMusicLensSimpleScope* self);
VALA_EXTERN UnityActivationResponse* unity_music_lens_rhythmbox_scope_activate (UnityMusicLensRhythmboxScope* self,
                                                                    const gchar* uri);
static UnityActivationResponse* _unity_music_lens_rhythmbox_scope_activate_unity_deprecated_scope_activate_uri (UnityDeprecatedScope* _sender,
                                                                                                         const gchar* uri,
                                                                                                         gpointer self);
VALA_EXTERN UnityPreview* unity_music_lens_rhythmbox_scope_preview (UnityMusicLensRhythmboxScope* self,
                                                        const gchar* uri);
static UnityPreview* _unity_music_lens_rhythmbox_scope_preview_unity_deprecated_scope_preview_uri (UnityDeprecatedScope* _sender,
                                                                                            const gchar* uri,
                                                                                            gpointer self);
VALA_EXTERN void unity_music_lens_simple_scope_initialize (UnityMusicLensSimpleScope* self);
VALA_EXTERN UnityMusicLensRhythmboxCollection* unity_music_lens_rhythmbox_collection_new (void);
VALA_EXTERN UnityMusicLensRhythmboxCollection* unity_music_lens_rhythmbox_collection_construct (GType object_type);
static void unity_music_lens_rhythmbox_scope_prepare_rhythmbox_play_queue_data_free (gpointer _data);
static void unity_music_lens_rhythmbox_scope_prepare_rhythmbox_play_queue (UnityMusicLensRhythmboxScope* self,
                                                                    gchar** exec_args,
                                                                    gint exec_args_length1,
                                                                    GAsyncReadyCallback _callback_,
                                                                    gpointer _user_data_);
static void unity_music_lens_rhythmbox_scope_prepare_rhythmbox_play_queue_finish (UnityMusicLensRhythmboxScope* self,
                                                                           GAsyncResult* _res_);
static gboolean unity_music_lens_rhythmbox_scope_prepare_rhythmbox_play_queue_co (UnityMusicLensRhythmboxScopePrepareRhythmboxPlayQueueData* _data_);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static gchar** _vala_array_dup1 (gchar** self,
                          gssize length);
static void* ___lambda14_ (Block1Data* _data1_);
static gboolean _unity_music_lens_rhythmbox_scope_prepare_rhythmbox_play_queue_co_gsource_func (gpointer self);
static gpointer ____lambda14__gthread_func (gpointer self);
VALA_EXTERN GType unity_music_lens_track_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (UnityMusicLensTrack, g_object_unref)
VALA_EXTERN GSList* unity_music_lens_rhythmbox_collection_get_album_tracks_detailed (UnityMusicLensRhythmboxCollection* self,
                                                                         const gchar* album_key);
VALA_EXTERN const gchar* unity_music_lens_track_get_artwork_path (UnityMusicLensTrack* self);
VALA_EXTERN const gchar* unity_music_lens_track_get_album (UnityMusicLensTrack* self);
VALA_EXTERN const gchar* unity_music_lens_track_get_album_artist (UnityMusicLensTrack* self);
static UnityActivationResponse* unity_music_lens_rhythmbox_scope_play_album_preview (UnityMusicLensRhythmboxScope* self,
                                                                              const gchar* uri);
static UnityActivationResponse* _unity_music_lens_rhythmbox_scope_play_album_preview_unity_preview_action_activated (UnityPreviewAction* _sender,
                                                                                                              const gchar* uri,
                                                                                                              gpointer self);
static UnityActivationResponse* unity_music_lens_rhythmbox_scope_show_in_folder (UnityMusicLensRhythmboxScope* self,
                                                                          const gchar* uri);
static UnityActivationResponse* _unity_music_lens_rhythmbox_scope_show_in_folder_unity_preview_action_activated (UnityPreviewAction* _sender,
                                                                                                          const gchar* uri,
                                                                                                          gpointer self);
VALA_EXTERN const gchar* unity_music_lens_track_get_uri (UnityMusicLensTrack* self);
VALA_EXTERN gint unity_music_lens_track_get_track_number (UnityMusicLensTrack* self);
VALA_EXTERN const gchar* unity_music_lens_track_get_title (UnityMusicLensTrack* self);
VALA_EXTERN gint unity_music_lens_track_get_duration (UnityMusicLensTrack* self);
static void _g_object_unref0_ (gpointer var);
static inline void _g_slist_free__g_object_unref0_ (GSList* self);
VALA_EXTERN UnityMusicLensTrack* unity_music_lens_rhythmbox_collection_get_album_track (UnityMusicLensRhythmboxCollection* self,
                                                                            const gchar* uri);
static UnityActivationResponse* unity_music_lens_rhythmbox_scope_play_track_in_rhythmbox (UnityMusicLensRhythmboxScope* self,
                                                                                   const gchar* uri);
static UnityActivationResponse* _unity_music_lens_rhythmbox_scope_play_track_in_rhythmbox_unity_preview_action_activated (UnityPreviewAction* _sender,
                                                                                                                   const gchar* uri,
                                                                                                                   gpointer self);
VALA_EXTERN GSList* unity_music_lens_rhythmbox_collection_get_album_tracks (UnityMusicLensRhythmboxCollection* self,
                                                                const gchar* album_key);
static void _vala_array_add1 (gchar** * array,
                       gint* length,
                       gint* size,
                       gchar* value);
static void _vala_array_add2 (gchar** * array,
                       gint* length,
                       gint* size,
                       gchar* value);
static void _vala_array_add3 (gchar** * array,
                       gint* length,
                       gint* size,
                       gchar* value);
static void _vala_array_add4 (gchar** * array,
                       gint* length,
                       gint* size,
                       gchar* value);
static void _vala_array_add5 (gchar** * array,
                       gint* length,
                       gint* size,
                       gchar* value);
static void _vala_array_add6 (gchar** * array,
                       gint* length,
                       gint* size,
                       gchar* value);
static inline void _g_list_free__g_object_unref0_ (GList* self);
static void unity_music_lens_rhythmbox_scope_real_perform_search_data_free (gpointer _data);
static void unity_music_lens_rhythmbox_scope_real_perform_search (UnityMusicLensSimpleScope* base,
                                                           UnityDeprecatedScopeSearch* search,
                                                           UnitySearchType search_type,
                                                           GList* filters,
                                                           gint max_results,
                                                           GCancellable* cancellable,
                                                           GAsyncReadyCallback _callback_,
                                                           gpointer _user_data_);
static gboolean unity_music_lens_rhythmbox_scope_real_perform_search_co (UnityMusicLensRhythmboxScopePerformSearchData* _data_);
VALA_EXTERN GType unity_music_lens_category_get_type (void) G_GNUC_CONST ;
VALA_EXTERN gboolean unity_music_lens_simple_scope_is_search_empty (UnityMusicLensSimpleScope* self,
                                                        UnityDeprecatedScopeSearch* search);
VALA_EXTERN void unity_music_lens_rhythmbox_collection_parse_metadata_file (UnityMusicLensRhythmboxCollection* self,
                                                                const gchar* path);
VALA_EXTERN void unity_music_lens_rhythmbox_collection_parse_file (UnityMusicLensRhythmboxCollection* self,
                                                       const gchar* path);
static void _____lambda15_ (UnityMusicLensRhythmboxScope* self);
static void ______lambda15__g_file_monitor_changed (GFileMonitor* _sender,
                                             GFile* file,
                                             GFile* other_file,
                                             GFileMonitorEvent event_type,
                                             gpointer self);
VALA_EXTERN void unity_music_lens_rhythmbox_collection_search (UnityMusicLensRhythmboxCollection* self,
                                                   UnityDeprecatedScopeSearch* search,
                                                   UnitySearchType search_type,
                                                   GList* filters,
                                                   gint max_results,
                                                   gint category_override);
static void unity_music_lens_rhythmbox_scope_finalize (GObject * obj);
static GType unity_music_lens_rhythmbox_scope_get_type_once (void);
static void _vala_unity_music_lens_rhythmbox_scope_get_property (GObject * object,
                                                          guint property_id,
                                                          GValue * value,
                                                          GParamSpec * pspec);
static void _vala_array_destroy (gpointer array,
                          gssize array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gssize array_length,
                       GDestroyNotify destroy_func);

static inline gpointer
unity_music_lens_rhythmbox_scope_get_instance_private (UnityMusicLensRhythmboxScope* self)
{
	return G_STRUCT_MEMBER_P (self, UnityMusicLensRhythmboxScope_private_offset);
}

static UnityActivationResponse*
_unity_music_lens_rhythmbox_scope_activate_unity_deprecated_scope_activate_uri (UnityDeprecatedScope* _sender,
                                                                                const gchar* uri,
                                                                                gpointer self)
{
	UnityActivationResponse* result;
	result = unity_music_lens_rhythmbox_scope_activate ((UnityMusicLensRhythmboxScope*) self, uri);
	return result;
}

static UnityPreview*
_unity_music_lens_rhythmbox_scope_preview_unity_deprecated_scope_preview_uri (UnityDeprecatedScope* _sender,
                                                                              const gchar* uri,
                                                                              gpointer self)
{
	UnityPreview* result;
	result = unity_music_lens_rhythmbox_scope_preview ((UnityMusicLensRhythmboxScope*) self, uri);
	return result;
}

UnityMusicLensRhythmboxScope*
unity_music_lens_rhythmbox_scope_construct (GType object_type)
{
	UnityMusicLensRhythmboxScope * self = NULL;
	UnityDeprecatedScope* _tmp0_;
	UnityDeprecatedScope* _tmp1_;
	UnityDeprecatedScope* _tmp2_;
	UnityDeprecatedScope* _tmp3_;
	UnityDeprecatedScope* _tmp4_;
	UnityDeprecatedScope* _tmp5_;
	UnityDeprecatedScope* _tmp6_;
	UnityDeprecatedScope* _tmp7_;
	UnityDeprecatedScope* _tmp8_;
	UnityDeprecatedScope* _tmp9_;
	UnityDeprecatedScope* _tmp10_;
	UnityDeprecatedScope* _tmp11_;
	UnityDeprecatedScope* _tmp12_;
	UnityDeprecatedScope* _tmp13_;
	UnityOptionsFilter* _tmp14_;
	UnityOptionsFilter* _tmp15_;
	UnityFilterOption* _tmp16_;
	UnityFilterOption* _tmp17_;
	UnityMusicLensRhythmboxCollection* _tmp18_;
	self = (UnityMusicLensRhythmboxScope*) unity_music_lens_simple_scope_construct (object_type);
	_tmp0_ = unity_deprecated_scope_new ("/com/canonical/unity/scope/rhythmbox", "music-rhythmbox.scope");
	_tmp1_ = _tmp0_;
	unity_music_lens_simple_scope_set_scope ((UnityMusicLensSimpleScope*) self, _tmp1_);
	_g_object_unref0 (_tmp1_);
	_tmp2_ = unity_music_lens_simple_scope_get_scope ((UnityMusicLensSimpleScope*) self);
	_tmp3_ = _tmp2_;
	unity_deprecated_scope_base_set_search_in_global ((UnityDeprecatedScopeBase*) _tmp3_, TRUE);
	_tmp4_ = unity_music_lens_simple_scope_get_scope ((UnityMusicLensSimpleScope*) self);
	_tmp5_ = _tmp4_;
	unity_deprecated_scope_base_set_search_hint ((UnityDeprecatedScopeBase*) _tmp5_, _ ("Search music"));
	_tmp6_ = unity_music_lens_simple_scope_get_scope ((UnityMusicLensSimpleScope*) self);
	_tmp7_ = _tmp6_;
	unity_deprecated_scope_base_set_visible ((UnityDeprecatedScopeBase*) _tmp7_, TRUE);
	_tmp8_ = unity_music_lens_simple_scope_get_scope ((UnityMusicLensSimpleScope*) self);
	_tmp9_ = _tmp8_;
	g_signal_connect_object (_tmp9_, "activate-uri", (GCallback) _unity_music_lens_rhythmbox_scope_activate_unity_deprecated_scope_activate_uri, self, 0);
	_tmp10_ = unity_music_lens_simple_scope_get_scope ((UnityMusicLensSimpleScope*) self);
	_tmp11_ = _tmp10_;
	g_signal_connect_object (_tmp11_, "preview-uri", (GCallback) _unity_music_lens_rhythmbox_scope_preview_unity_deprecated_scope_preview_uri, self, 0);
	_tmp12_ = unity_music_lens_simple_scope_get_scope ((UnityMusicLensSimpleScope*) self);
	_tmp13_ = _tmp12_;
	_tmp14_ = unity_deprecated_scope_base_get_sources ((UnityDeprecatedScopeBase*) _tmp13_);
	_tmp15_ = _tmp14_;
	_tmp16_ = unity_options_filter_add_option (_tmp15_, "rhythmbox", _ ("Rhythmbox"), NULL);
	_tmp17_ = _tmp16_;
	_g_object_unref0 (_tmp17_);
	unity_music_lens_simple_scope_initialize (G_TYPE_CHECK_INSTANCE_CAST (self, UNITY_MUSIC_LENS_TYPE_SIMPLE_SCOPE, UnityMusicLensSimpleScope));
	_tmp18_ = unity_music_lens_rhythmbox_collection_new ();
	_g_object_unref0 (self->priv->collection);
	self->priv->collection = _tmp18_;
	self->priv->db_ready = FALSE;
	return self;
}

UnityMusicLensRhythmboxScope*
unity_music_lens_rhythmbox_scope_new (void)
{
	return unity_music_lens_rhythmbox_scope_construct (UNITY_MUSIC_LENS_TYPE_RHYTHMBOX_SCOPE);
}

static void
unity_music_lens_rhythmbox_scope_prepare_rhythmbox_play_queue_data_free (gpointer _data)
{
	UnityMusicLensRhythmboxScopePrepareRhythmboxPlayQueueData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->self);
	g_slice_free (UnityMusicLensRhythmboxScopePrepareRhythmboxPlayQueueData, _data_);
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

static void
unity_music_lens_rhythmbox_scope_prepare_rhythmbox_play_queue (UnityMusicLensRhythmboxScope* self,
                                                               gchar** exec_args,
                                                               gint exec_args_length1,
                                                               GAsyncReadyCallback _callback_,
                                                               gpointer _user_data_)
{
	UnityMusicLensRhythmboxScopePrepareRhythmboxPlayQueueData* _data_;
	UnityMusicLensRhythmboxScope* _tmp0_;
	g_return_if_fail (self != NULL);
	_data_ = g_slice_new0 (UnityMusicLensRhythmboxScopePrepareRhythmboxPlayQueueData);
	_data_->_async_result = g_task_new (G_OBJECT (self), NULL, _callback_, _user_data_);
	g_task_set_task_data (_data_->_async_result, _data_, unity_music_lens_rhythmbox_scope_prepare_rhythmbox_play_queue_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	_data_->exec_args = exec_args;
	_data_->exec_args_length1 = exec_args_length1;
	unity_music_lens_rhythmbox_scope_prepare_rhythmbox_play_queue_co (_data_);
}

static void
unity_music_lens_rhythmbox_scope_prepare_rhythmbox_play_queue_finish (UnityMusicLensRhythmboxScope* self,
                                                                      GAsyncResult* _res_)
{
	UnityMusicLensRhythmboxScopePrepareRhythmboxPlayQueueData* _data_;
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
}

static Block1Data*
block1_data_ref (Block1Data* _data1_)
{
	g_atomic_int_inc (&_data1_->_ref_count_);
	return _data1_;
}

static void
block1_data_unref (void * _userdata_)
{
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
		UnityMusicLensRhythmboxScope* self;
		self = _data1_->self;
		_data1_->main_exec = (_vala_array_free (_data1_->main_exec, _data1_->main_exec_length1, (GDestroyNotify) g_free), NULL);
		_g_object_unref0 (self);
		g_slice_free (Block1Data, _data1_);
	}
}

static gchar**
_vala_array_dup1 (gchar** self,
                  gssize length)
{
	if (length >= 0) {
		gchar** result;
		gssize i;
		result = g_new0 (gchar*, length + 1);
		for (i = 0; i < length; i++) {
			gchar* _tmp0_;
			_tmp0_ = g_strdup (self[i]);
			result[i] = _tmp0_;
		}
		return result;
	}
	return NULL;
}

static gboolean
_unity_music_lens_rhythmbox_scope_prepare_rhythmbox_play_queue_co_gsource_func (gpointer self)
{
	gboolean result;
	result = unity_music_lens_rhythmbox_scope_prepare_rhythmbox_play_queue_co (self);
	return result;
}

static void*
___lambda14_ (Block1Data* _data1_)
{
	UnityMusicLensRhythmboxScope* self;
	GError* _inner_error0_ = NULL;
	void* result;
	self = _data1_->self;
	{
		g_spawn_command_line_sync ("rhythmbox-client --pause", NULL, NULL, NULL, &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			goto __catch0_g_error;
		}
		g_spawn_command_line_sync ("rhythmbox-client --clear-queue", NULL, NULL, NULL, &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			goto __catch0_g_error;
		}
		g_spawn_sync (NULL, _data1_->main_exec, NULL, G_SPAWN_SEARCH_PATH, NULL, NULL, NULL, NULL, NULL, &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			goto __catch0_g_error;
		}
		g_spawn_command_line_sync ("rhythmbox-client --next", NULL, NULL, NULL, &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			goto __catch0_g_error;
		}
		g_spawn_command_line_sync ("rhythmbox-client --play", NULL, NULL, NULL, &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			goto __catch0_g_error;
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* err = NULL;
		GError* _tmp0_;
		const gchar* _tmp1_;
		err = _inner_error0_;
		_inner_error0_ = NULL;
		_tmp0_ = err;
		_tmp1_ = _tmp0_->message;
		g_warning ("rhythmbox-scope.vala:71: %s", _tmp1_);
		_g_error_free0 (err);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return NULL;
	}
	g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, _unity_music_lens_rhythmbox_scope_prepare_rhythmbox_play_queue_co_gsource_func, _data1_->_async_data_, NULL);
	result = NULL;
	return result;
}

static gpointer
____lambda14__gthread_func (gpointer self)
{
	gpointer result;
	result = ___lambda14_ (self);
	block1_data_unref (self);
	return result;
}

static gboolean
unity_music_lens_rhythmbox_scope_prepare_rhythmbox_play_queue_co (UnityMusicLensRhythmboxScopePrepareRhythmboxPlayQueueData* _data_)
{
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_data1_ = g_slice_new0 (Block1Data);
	_data_->_data1_->_ref_count_ = 1;
	_data_->_data1_->self = g_object_ref (_data_->self);
	_data_->_data1_->_async_data_ = _data_;
	_data_->_tmp0_ = (_data_->exec_args != NULL) ? _vala_array_dup1 (_data_->exec_args, _data_->exec_args_length1) : _data_->exec_args;
	_data_->_tmp0__length1 = _data_->exec_args_length1;
	_data_->_data1_->main_exec = _data_->_tmp0_;
	_data_->_data1_->main_exec_length1 = _data_->_tmp0__length1;
	_data_->_data1_->_main_exec_size_ = _data_->_data1_->main_exec_length1;
	{
		_data_->_tmp1_ = g_thread_try_new ("rhythmbox-thread", ____lambda14__gthread_func, block1_data_ref (_data_->_data1_), &_data_->_inner_error0_);
		_data_->_tmp2_ = _data_->_tmp1_;
		_g_thread_unref0 (_data_->_tmp2_);
		if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
			goto __catch0_g_error;
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		_data_->err = _data_->_inner_error0_;
		_data_->_inner_error0_ = NULL;
		_data_->_tmp3_ = _data_->err;
		_data_->_tmp4_ = _data_->_tmp3_->message;
		g_warning ("rhythmbox-scope.vala:79: Could not create rhythmbox-thread: %s", _data_->_tmp4_);
		_g_error_free0 (_data_->err);
	}
	__finally0:
	if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
		block1_data_unref (_data_->_data1_);
		_data_->_data1_ = NULL;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error0_->message, g_quark_to_string (_data_->_inner_error0_->domain), _data_->_inner_error0_->code);
		g_clear_error (&_data_->_inner_error0_);
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	_data_->_state_ = 1;
	return FALSE;
	_state_1:
	;
	block1_data_unref (_data_->_data1_);
	_data_->_data1_ = NULL;
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
	if (_data_->_state_ != 0) {
		while (!g_task_get_completed (_data_->_async_result)) {
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
		}
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}

static glong
string_strnlen (gchar* str,
                glong maxlen)
{
	gchar* end = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	glong result;
	_tmp0_ = memchr (str, 0, (gsize) maxlen);
	end = _tmp0_;
	_tmp1_ = end;
	if (_tmp1_ == NULL) {
		result = maxlen;
		return result;
	} else {
		gchar* _tmp2_;
		_tmp2_ = end;
		result = (glong) (_tmp2_ - str);
		return result;
	}
}

static gchar*
string_substring (const gchar* self,
                  glong offset,
                  glong len)
{
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	gchar* _tmp3_;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	if (offset >= ((glong) 0)) {
		_tmp0_ = len >= ((glong) 0);
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		string_length = string_strnlen ((gchar*) self, offset + len);
	} else {
		gint _tmp1_;
		gint _tmp2_;
		_tmp1_ = strlen (self);
		_tmp2_ = _tmp1_;
		string_length = (glong) _tmp2_;
	}
	if (offset < ((glong) 0)) {
		offset = string_length + offset;
		g_return_val_if_fail (offset >= ((glong) 0), NULL);
	} else {
		g_return_val_if_fail (offset <= string_length, NULL);
	}
	if (len < ((glong) 0)) {
		len = string_length - offset;
	}
	g_return_val_if_fail ((offset + len) <= string_length, NULL);
	_tmp3_ = g_strndup (((gchar*) self) + offset, (gsize) len);
	result = _tmp3_;
	return result;
}

static UnityActivationResponse*
_unity_music_lens_rhythmbox_scope_play_album_preview_unity_preview_action_activated (UnityPreviewAction* _sender,
                                                                                     const gchar* uri,
                                                                                     gpointer self)
{
	UnityActivationResponse* result;
	result = unity_music_lens_rhythmbox_scope_play_album_preview ((UnityMusicLensRhythmboxScope*) self, uri);
	return result;
}

static UnityActivationResponse*
_unity_music_lens_rhythmbox_scope_show_in_folder_unity_preview_action_activated (UnityPreviewAction* _sender,
                                                                                 const gchar* uri,
                                                                                 gpointer self)
{
	UnityActivationResponse* result;
	result = unity_music_lens_rhythmbox_scope_show_in_folder ((UnityMusicLensRhythmboxScope*) self, uri);
	return result;
}

static void
_g_object_unref0_ (gpointer var)
{
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
}

static inline void
_g_slist_free__g_object_unref0_ (GSList* self)
{
	g_slist_free_full (self, (GDestroyNotify) _g_object_unref0_);
}

static UnityActivationResponse*
_unity_music_lens_rhythmbox_scope_play_track_in_rhythmbox_unity_preview_action_activated (UnityPreviewAction* _sender,
                                                                                          const gchar* uri,
                                                                                          gpointer self)
{
	UnityActivationResponse* result;
	result = unity_music_lens_rhythmbox_scope_play_track_in_rhythmbox ((UnityMusicLensRhythmboxScope*) self, uri);
	return result;
}

UnityPreview*
unity_music_lens_rhythmbox_scope_preview (UnityMusicLensRhythmboxScope* self,
                                          const gchar* uri)
{
	GIcon* icon_file = NULL;
	GIcon* missing_icon_file = NULL;
	GFile* _tmp0_;
	GFile* _tmp1_;
	GFileIcon* _tmp2_;
	GIcon* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gboolean _tmp6_;
	UnityMusicPreview* _tmp114_;
	UnityPreview* _tmp115_;
	UnityPreview* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (uri != NULL, NULL);
	_g_object_unref0 (self->priv->music_preview);
	self->priv->music_preview = NULL;
	icon_file = NULL;
	_tmp0_ = g_file_new_for_path (UNITY_MUSIC_LENS_ALBUM_MISSING_PREVIEW_ICON_PATH);
	_tmp1_ = _tmp0_;
	_tmp2_ = (GFileIcon*) g_file_icon_new (_tmp1_);
	_tmp3_ = (GIcon*) _tmp2_;
	_g_object_unref0 (_tmp1_);
	missing_icon_file = _tmp3_;
	_tmp4_ = g_uri_parse_scheme (uri);
	_tmp5_ = _tmp4_;
	_tmp6_ = g_strcmp0 (_tmp5_, "album") == 0;
	_g_free0 (_tmp5_);
	if (_tmp6_) {
		gchar* album_key = NULL;
		gchar* _tmp7_;
		UnityMusicLensRhythmboxCollection* _tmp8_;
		const gchar* _tmp9_;
		GSList* _tmp10_;
		_tmp7_ = string_substring (uri, (glong) 8, (glong) -1);
		album_key = _tmp7_;
		_tmp8_ = self->priv->collection;
		_tmp9_ = album_key;
		_tmp10_ = unity_music_lens_rhythmbox_collection_get_album_tracks_detailed (_tmp8_, _tmp9_);
		{
			GSList* track_collection = NULL;
			GSList* track_it = NULL;
			track_collection = _tmp10_;
			for (track_it = track_collection; track_it != NULL; track_it = track_it->next) {
				UnityMusicLensTrack* track = NULL;
				track = (UnityMusicLensTrack*) track_it->data;
				{
					UnityMusicPreview* _tmp11_;
					UnityTrackMetadata* tm = NULL;
					UnityTrackMetadata* _tmp41_;
					UnityTrackMetadata* _tmp42_;
					UnityMusicLensTrack* _tmp43_;
					const gchar* _tmp44_;
					const gchar* _tmp45_;
					UnityTrackMetadata* _tmp46_;
					UnityMusicLensTrack* _tmp47_;
					gint _tmp48_;
					gint _tmp49_;
					UnityTrackMetadata* _tmp50_;
					UnityMusicLensTrack* _tmp51_;
					const gchar* _tmp52_;
					const gchar* _tmp53_;
					UnityTrackMetadata* _tmp54_;
					UnityMusicLensTrack* _tmp55_;
					gint _tmp56_;
					gint _tmp57_;
					UnityMusicPreview* _tmp58_;
					UnityTrackMetadata* _tmp59_;
					_tmp11_ = self->priv->music_preview;
					if (_tmp11_ == NULL) {
						gchar* artwork_path = NULL;
						UnityMusicLensTrack* _tmp12_;
						const gchar* _tmp13_;
						const gchar* _tmp14_;
						gchar* _tmp15_;
						gboolean _tmp16_ = FALSE;
						const gchar* _tmp17_;
						UnityMusicLensTrack* _tmp25_;
						const gchar* _tmp26_;
						const gchar* _tmp27_;
						UnityMusicLensTrack* _tmp28_;
						const gchar* _tmp29_;
						const gchar* _tmp30_;
						GIcon* _tmp31_;
						UnityMusicPreview* _tmp32_;
						UnityPreviewAction* play_action = NULL;
						UnityPreviewAction* _tmp33_;
						UnityPreviewAction* _tmp34_;
						UnityMusicPreview* _tmp35_;
						UnityPreviewAction* _tmp36_;
						UnityPreviewAction* show_folder_action = NULL;
						UnityPreviewAction* _tmp37_;
						UnityPreviewAction* _tmp38_;
						UnityMusicPreview* _tmp39_;
						UnityPreviewAction* _tmp40_;
						_tmp12_ = track;
						_tmp13_ = unity_music_lens_track_get_artwork_path (_tmp12_);
						_tmp14_ = _tmp13_;
						_tmp15_ = g_strdup (_tmp14_);
						artwork_path = _tmp15_;
						_tmp17_ = artwork_path;
						if (_tmp17_ == NULL) {
							_tmp16_ = TRUE;
						} else {
							const gchar* _tmp18_;
							_tmp18_ = artwork_path;
							_tmp16_ = g_strcmp0 (_tmp18_, "") == 0;
						}
						if (_tmp16_) {
							GIcon* _tmp19_;
							GIcon* _tmp20_;
							_tmp19_ = missing_icon_file;
							_tmp20_ = _g_object_ref0 (_tmp19_);
							_g_object_unref0 (icon_file);
							icon_file = _tmp20_;
						} else {
							const gchar* _tmp21_;
							GFile* _tmp22_;
							GFile* _tmp23_;
							GFileIcon* _tmp24_;
							_tmp21_ = artwork_path;
							_tmp22_ = g_file_new_for_path (_tmp21_);
							_tmp23_ = _tmp22_;
							_tmp24_ = (GFileIcon*) g_file_icon_new (_tmp23_);
							_g_object_unref0 (icon_file);
							icon_file = (GIcon*) _tmp24_;
							_g_object_unref0 (_tmp23_);
						}
						_tmp25_ = track;
						_tmp26_ = unity_music_lens_track_get_album (_tmp25_);
						_tmp27_ = _tmp26_;
						_tmp28_ = track;
						_tmp29_ = unity_music_lens_track_get_album_artist (_tmp28_);
						_tmp30_ = _tmp29_;
						_tmp31_ = icon_file;
						_tmp32_ = unity_music_preview_new (_tmp27_, _tmp30_, _tmp31_);
						_g_object_unref0 (self->priv->music_preview);
						self->priv->music_preview = _tmp32_;
						_tmp33_ = unity_preview_action_new ("play_album", _ ("Play"), NULL);
						play_action = _tmp33_;
						_tmp34_ = play_action;
						g_signal_connect_object (_tmp34_, "activated", (GCallback) _unity_music_lens_rhythmbox_scope_play_album_preview_unity_preview_action_activated, self, 0);
						_tmp35_ = self->priv->music_preview;
						_tmp36_ = play_action;
						unity_preview_add_action ((UnityPreview*) _tmp35_, _tmp36_);
						_tmp37_ = unity_preview_action_new ("show_in_folder", _ ("Show in Folder"), NULL);
						show_folder_action = _tmp37_;
						_tmp38_ = show_folder_action;
						g_signal_connect_object (_tmp38_, "activated", (GCallback) _unity_music_lens_rhythmbox_scope_show_in_folder_unity_preview_action_activated, self, 0);
						_tmp39_ = self->priv->music_preview;
						_tmp40_ = show_folder_action;
						unity_preview_add_action ((UnityPreview*) _tmp39_, _tmp40_);
						_g_object_unref0 (show_folder_action);
						_g_object_unref0 (play_action);
						_g_free0 (artwork_path);
					}
					_tmp41_ = unity_track_metadata_new ();
					tm = _tmp41_;
					_tmp42_ = tm;
					_tmp43_ = track;
					_tmp44_ = unity_music_lens_track_get_uri (_tmp43_);
					_tmp45_ = _tmp44_;
					unity_track_metadata_set_uri (_tmp42_, _tmp45_);
					_tmp46_ = tm;
					_tmp47_ = track;
					_tmp48_ = unity_music_lens_track_get_track_number (_tmp47_);
					_tmp49_ = _tmp48_;
					unity_track_metadata_set_track_no (_tmp46_, _tmp49_);
					_tmp50_ = tm;
					_tmp51_ = track;
					_tmp52_ = unity_music_lens_track_get_title (_tmp51_);
					_tmp53_ = _tmp52_;
					unity_track_metadata_set_title (_tmp50_, _tmp53_);
					_tmp54_ = tm;
					_tmp55_ = track;
					_tmp56_ = unity_music_lens_track_get_duration (_tmp55_);
					_tmp57_ = _tmp56_;
					unity_track_metadata_set_length (_tmp54_, (guint) _tmp57_);
					_tmp58_ = self->priv->music_preview;
					_tmp59_ = tm;
					unity_music_preview_add_track (_tmp58_, _tmp59_);
					_g_object_unref0 (tm);
				}
			}
			(track_collection == NULL) ? NULL : (track_collection = (_g_slist_free__g_object_unref0_ (track_collection), NULL));
		}
		_g_free0 (album_key);
	} else {
		gchar* _tmp60_;
		gchar* _tmp61_;
		gboolean _tmp62_;
		_tmp60_ = g_uri_parse_scheme (uri);
		_tmp61_ = _tmp60_;
		_tmp62_ = g_strcmp0 (_tmp61_, "file") == 0;
		_g_free0 (_tmp61_);
		if (_tmp62_) {
			UnityMusicLensTrack* track = NULL;
			UnityMusicLensRhythmboxCollection* _tmp63_;
			UnityMusicLensTrack* _tmp64_;
			UnityMusicLensTrack* _tmp65_;
			_tmp63_ = self->priv->collection;
			_tmp64_ = unity_music_lens_rhythmbox_collection_get_album_track (_tmp63_, uri);
			track = _tmp64_;
			_tmp65_ = track;
			if (_tmp65_ != NULL) {
				gchar* artwork_path = NULL;
				UnityMusicLensTrack* _tmp66_;
				const gchar* _tmp67_;
				const gchar* _tmp68_;
				gchar* _tmp69_;
				gboolean _tmp70_ = FALSE;
				const gchar* _tmp71_;
				UnityMusicLensTrack* _tmp79_;
				const gchar* _tmp80_;
				const gchar* _tmp81_;
				UnityMusicLensTrack* _tmp82_;
				const gchar* _tmp83_;
				const gchar* _tmp84_;
				GIcon* _tmp85_;
				UnityMusicPreview* _tmp86_;
				UnityPreviewAction* play_action = NULL;
				UnityPreviewAction* _tmp87_;
				UnityPreviewAction* _tmp88_;
				UnityMusicPreview* _tmp89_;
				UnityPreviewAction* _tmp90_;
				UnityPreviewAction* show_folder_action = NULL;
				UnityPreviewAction* _tmp91_;
				UnityPreviewAction* _tmp92_;
				UnityMusicPreview* _tmp93_;
				UnityPreviewAction* _tmp94_;
				UnityTrackMetadata* tm = NULL;
				UnityTrackMetadata* _tmp95_;
				UnityTrackMetadata* _tmp96_;
				UnityMusicLensTrack* _tmp97_;
				const gchar* _tmp98_;
				const gchar* _tmp99_;
				UnityTrackMetadata* _tmp100_;
				UnityMusicLensTrack* _tmp101_;
				gint _tmp102_;
				gint _tmp103_;
				UnityTrackMetadata* _tmp104_;
				UnityMusicLensTrack* _tmp105_;
				const gchar* _tmp106_;
				const gchar* _tmp107_;
				UnityTrackMetadata* _tmp108_;
				UnityMusicLensTrack* _tmp109_;
				gint _tmp110_;
				gint _tmp111_;
				UnityMusicPreview* _tmp112_;
				UnityTrackMetadata* _tmp113_;
				_tmp66_ = track;
				_tmp67_ = unity_music_lens_track_get_artwork_path (_tmp66_);
				_tmp68_ = _tmp67_;
				_tmp69_ = g_strdup (_tmp68_);
				artwork_path = _tmp69_;
				_tmp71_ = artwork_path;
				if (_tmp71_ == NULL) {
					_tmp70_ = TRUE;
				} else {
					const gchar* _tmp72_;
					_tmp72_ = artwork_path;
					_tmp70_ = g_strcmp0 (_tmp72_, "") == 0;
				}
				if (_tmp70_) {
					GIcon* _tmp73_;
					GIcon* _tmp74_;
					_tmp73_ = missing_icon_file;
					_tmp74_ = _g_object_ref0 (_tmp73_);
					_g_object_unref0 (icon_file);
					icon_file = _tmp74_;
				} else {
					const gchar* _tmp75_;
					GFile* _tmp76_;
					GFile* _tmp77_;
					GFileIcon* _tmp78_;
					_tmp75_ = artwork_path;
					_tmp76_ = g_file_new_for_path (_tmp75_);
					_tmp77_ = _tmp76_;
					_tmp78_ = (GFileIcon*) g_file_icon_new (_tmp77_);
					_g_object_unref0 (icon_file);
					icon_file = (GIcon*) _tmp78_;
					_g_object_unref0 (_tmp77_);
				}
				_tmp79_ = track;
				_tmp80_ = unity_music_lens_track_get_title (_tmp79_);
				_tmp81_ = _tmp80_;
				_tmp82_ = track;
				_tmp83_ = unity_music_lens_track_get_album_artist (_tmp82_);
				_tmp84_ = _tmp83_;
				_tmp85_ = icon_file;
				_tmp86_ = unity_music_preview_new (_tmp81_, _tmp84_, _tmp85_);
				_g_object_unref0 (self->priv->music_preview);
				self->priv->music_preview = _tmp86_;
				_tmp87_ = unity_preview_action_new ("play_track", _ ("Play"), NULL);
				play_action = _tmp87_;
				_tmp88_ = play_action;
				g_signal_connect_object (_tmp88_, "activated", (GCallback) _unity_music_lens_rhythmbox_scope_play_track_in_rhythmbox_unity_preview_action_activated, self, 0);
				_tmp89_ = self->priv->music_preview;
				_tmp90_ = play_action;
				unity_preview_add_action ((UnityPreview*) _tmp89_, _tmp90_);
				_tmp91_ = unity_preview_action_new ("show_in_folder", _ ("Show in Folder"), NULL);
				show_folder_action = _tmp91_;
				_tmp92_ = show_folder_action;
				g_signal_connect_object (_tmp92_, "activated", (GCallback) _unity_music_lens_rhythmbox_scope_show_in_folder_unity_preview_action_activated, self, 0);
				_tmp93_ = self->priv->music_preview;
				_tmp94_ = show_folder_action;
				unity_preview_add_action ((UnityPreview*) _tmp93_, _tmp94_);
				_tmp95_ = unity_track_metadata_new ();
				tm = _tmp95_;
				_tmp96_ = tm;
				_tmp97_ = track;
				_tmp98_ = unity_music_lens_track_get_uri (_tmp97_);
				_tmp99_ = _tmp98_;
				unity_track_metadata_set_uri (_tmp96_, _tmp99_);
				_tmp100_ = tm;
				_tmp101_ = track;
				_tmp102_ = unity_music_lens_track_get_track_number (_tmp101_);
				_tmp103_ = _tmp102_;
				unity_track_metadata_set_track_no (_tmp100_, _tmp103_);
				_tmp104_ = tm;
				_tmp105_ = track;
				_tmp106_ = unity_music_lens_track_get_title (_tmp105_);
				_tmp107_ = _tmp106_;
				unity_track_metadata_set_title (_tmp104_, _tmp107_);
				_tmp108_ = tm;
				_tmp109_ = track;
				_tmp110_ = unity_music_lens_track_get_duration (_tmp109_);
				_tmp111_ = _tmp110_;
				unity_track_metadata_set_length (_tmp108_, (guint) _tmp111_);
				_tmp112_ = self->priv->music_preview;
				_tmp113_ = tm;
				unity_music_preview_add_track (_tmp112_, _tmp113_);
				_g_object_unref0 (tm);
				_g_object_unref0 (show_folder_action);
				_g_object_unref0 (play_action);
				_g_free0 (artwork_path);
			}
			_g_object_unref0 (track);
		}
	}
	_tmp114_ = self->priv->music_preview;
	_tmp115_ = _g_object_ref0 ((UnityPreview*) _tmp114_);
	result = _tmp115_;
	_g_object_unref0 (missing_icon_file);
	_g_object_unref0 (icon_file);
	return result;
}

static UnityActivationResponse*
unity_music_lens_rhythmbox_scope_show_in_folder (UnityMusicLensRhythmboxScope* self,
                                                 const gchar* uri)
{
	gchar* file_uri = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gboolean _tmp2_;
	const gchar* _tmp12_;
	UnityActivationResponse* _tmp15_;
	UnityActivationResponse* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (uri != NULL, NULL);
	file_uri = NULL;
	_tmp0_ = g_uri_parse_scheme (uri);
	_tmp1_ = _tmp0_;
	_tmp2_ = g_strcmp0 (_tmp1_, "album") == 0;
	_g_free0 (_tmp1_);
	if (_tmp2_) {
		gchar* album_key = NULL;
		gchar* _tmp3_;
		GSList* tracks = NULL;
		UnityMusicLensRhythmboxCollection* _tmp4_;
		const gchar* _tmp5_;
		GSList* _tmp6_;
		GSList* _tmp7_;
		_tmp3_ = string_substring (uri, (glong) 8, (glong) -1);
		album_key = _tmp3_;
		_tmp4_ = self->priv->collection;
		_tmp5_ = album_key;
		_tmp6_ = unity_music_lens_rhythmbox_collection_get_album_tracks (_tmp4_, _tmp5_);
		tracks = _tmp6_;
		_tmp7_ = tracks;
		if (g_slist_length (_tmp7_) > ((guint) 0)) {
			GSList* _tmp8_;
			gconstpointer _tmp9_;
			gchar* _tmp10_;
			_tmp8_ = tracks;
			_tmp9_ = g_slist_nth_data (_tmp8_, (guint) 0);
			_tmp10_ = g_strdup ((const gchar*) _tmp9_);
			_g_free0 (file_uri);
			file_uri = _tmp10_;
		} else {
			g_warning ("rhythmbox-scope.vala:168: Album '%s' has no tracks, unable to get uri", uri);
		}
		(tracks == NULL) ? NULL : (tracks = (g_slist_free (tracks), NULL));
		_g_free0 (album_key);
	} else {
		gchar* _tmp11_;
		_tmp11_ = g_strdup (uri);
		_g_free0 (file_uri);
		file_uri = _tmp11_;
	}
	_tmp12_ = file_uri;
	if (_tmp12_ != NULL) {
		const gchar* _tmp13_;
		UnityActivationResponse* _tmp14_;
		_tmp13_ = file_uri;
		unity_extras_show_in_folder (_tmp13_, NULL, NULL);
		_tmp14_ = unity_activation_response_new (UNITY_HANDLED_TYPE_HIDE_DASH, "");
		result = _tmp14_;
		_g_free0 (file_uri);
		return result;
	}
	_tmp15_ = unity_activation_response_new (UNITY_HANDLED_TYPE_NOT_HANDLED, "");
	result = _tmp15_;
	_g_free0 (file_uri);
	return result;
}

static UnityActivationResponse*
unity_music_lens_rhythmbox_scope_play_track_in_rhythmbox (UnityMusicLensRhythmboxScope* self,
                                                          const gchar* uri)
{
	UnityActivationResponse* _tmp0_;
	UnityActivationResponse* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (uri != NULL, NULL);
	_tmp0_ = unity_music_lens_rhythmbox_scope_activate (self, uri);
	result = _tmp0_;
	return result;
}

static UnityActivationResponse*
unity_music_lens_rhythmbox_scope_play_album_preview (UnityMusicLensRhythmboxScope* self,
                                                     const gchar* uri)
{
	UnityActivationResponse* _tmp0_;
	UnityActivationResponse* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (uri != NULL, NULL);
	_tmp0_ = unity_music_lens_rhythmbox_scope_activate (self, uri);
	result = _tmp0_;
	return result;
}

/**
     * Tells rhythmbox to play the selected uri(s)
     */
static void
_vala_array_add1 (gchar** * array,
                  gint* length,
                  gint* size,
                  gchar* value)
{
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}

static void
_vala_array_add2 (gchar** * array,
                  gint* length,
                  gint* size,
                  gchar* value)
{
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}

static void
_vala_array_add3 (gchar** * array,
                  gint* length,
                  gint* size,
                  gchar* value)
{
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}

static void
_vala_array_add4 (gchar** * array,
                  gint* length,
                  gint* size,
                  gchar* value)
{
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}

static void
_vala_array_add5 (gchar** * array,
                  gint* length,
                  gint* size,
                  gchar* value)
{
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}

static void
_vala_array_add6 (gchar** * array,
                  gint* length,
                  gint* size,
                  gchar* value)
{
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}

static gchar*
_vala_g_strjoinv (const gchar* separator,
                  gchar** str_array,
                  gint str_array_length1)
{
	gboolean _tmp0_ = FALSE;
	gchar* result;
	if (separator == NULL) {
		separator = "";
	}
	if (str_array != NULL) {
		gboolean _tmp1_ = FALSE;
		if (str_array_length1 > 0) {
			_tmp1_ = TRUE;
		} else {
			gboolean _tmp2_ = FALSE;
			if (str_array_length1 == -1) {
				const gchar* _tmp3_;
				_tmp3_ = str_array[0];
				_tmp2_ = _tmp3_ != NULL;
			} else {
				_tmp2_ = FALSE;
			}
			_tmp1_ = _tmp2_;
		}
		_tmp0_ = _tmp1_;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		gint i = 0;
		gsize len = 0UL;
		gint _tmp16_;
		gint _tmp17_;
		const gchar* res = NULL;
		void* _tmp18_;
		const gchar* _tmp19_ = NULL;
		const gchar* _tmp20_;
		void* ptr = NULL;
		const gchar* _tmp22_;
		void* _tmp23_;
		const gchar* _tmp33_;
		len = (gsize) 1;
		{
			gboolean _tmp4_ = FALSE;
			i = 0;
			_tmp4_ = TRUE;
			while (TRUE) {
				gboolean _tmp6_ = FALSE;
				gboolean _tmp7_ = FALSE;
				gint _tmp10_ = 0;
				const gchar* _tmp11_;
				if (!_tmp4_) {
					gint _tmp5_;
					_tmp5_ = i;
					i = _tmp5_ + 1;
				}
				_tmp4_ = FALSE;
				if (str_array_length1 != -1) {
					_tmp7_ = i < str_array_length1;
				} else {
					_tmp7_ = FALSE;
				}
				if (_tmp7_) {
					_tmp6_ = TRUE;
				} else {
					gboolean _tmp8_ = FALSE;
					if (str_array_length1 == -1) {
						const gchar* _tmp9_;
						_tmp9_ = str_array[i];
						_tmp8_ = _tmp9_ != NULL;
					} else {
						_tmp8_ = FALSE;
					}
					_tmp6_ = _tmp8_;
				}
				if (!_tmp6_) {
					break;
				}
				_tmp11_ = str_array[i];
				if (_tmp11_ != NULL) {
					const gchar* _tmp12_;
					gint _tmp13_;
					gint _tmp14_;
					_tmp12_ = str_array[i];
					_tmp13_ = strlen ((const gchar*) _tmp12_);
					_tmp14_ = _tmp13_;
					_tmp10_ = _tmp14_;
				} else {
					_tmp10_ = 0;
				}
				len += (gsize) _tmp10_;
			}
		}
		if (i == 0) {
			gchar* _tmp15_;
			_tmp15_ = g_strdup ("");
			result = _tmp15_;
			return result;
		}
		str_array_length1 = i;
		_tmp16_ = strlen ((const gchar*) separator);
		_tmp17_ = _tmp16_;
		len += (gsize) (_tmp17_ * (i - 1));
		_tmp18_ = g_malloc (len);
		res = _tmp18_;
		_tmp20_ = str_array[0];
		if (_tmp20_ != NULL) {
			const gchar* _tmp21_;
			_tmp21_ = str_array[0];
			_tmp19_ = (const gchar*) _tmp21_;
		} else {
			_tmp19_ = "";
		}
		_tmp22_ = res;
		_tmp23_ = g_stpcpy ((void*) _tmp22_, _tmp19_);
		ptr = _tmp23_;
		{
			gboolean _tmp24_ = FALSE;
			i = 1;
			_tmp24_ = TRUE;
			while (TRUE) {
				void* _tmp26_;
				void* _tmp27_;
				const gchar* _tmp28_ = NULL;
				const gchar* _tmp29_;
				void* _tmp31_;
				void* _tmp32_;
				if (!_tmp24_) {
					gint _tmp25_;
					_tmp25_ = i;
					i = _tmp25_ + 1;
				}
				_tmp24_ = FALSE;
				if (!(i < str_array_length1)) {
					break;
				}
				_tmp26_ = ptr;
				_tmp27_ = g_stpcpy (_tmp26_, (const gchar*) separator);
				ptr = _tmp27_;
				_tmp29_ = str_array[i];
				if (_tmp29_ != NULL) {
					const gchar* _tmp30_;
					_tmp30_ = str_array[i];
					_tmp28_ = (const gchar*) _tmp30_;
				} else {
					_tmp28_ = "";
				}
				_tmp31_ = ptr;
				_tmp32_ = g_stpcpy (_tmp31_, _tmp28_);
				ptr = _tmp32_;
			}
		}
		_tmp33_ = res;
		res = NULL;
		result = (gchar*) _tmp33_;
		return result;
	} else {
		gchar* _tmp34_;
		_tmp34_ = g_strdup ("");
		result = _tmp34_;
		return result;
	}
}

UnityActivationResponse*
unity_music_lens_rhythmbox_scope_activate (UnityMusicLensRhythmboxScope* self,
                                           const gchar* uri)
{
	gchar** exec = NULL;
	gchar* _tmp0_;
	gchar** _tmp1_;
	gint exec_length1;
	gint _exec_size_;
	GError* _inner_error0_ = NULL;
	UnityActivationResponse* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (uri != NULL, NULL);
	_tmp0_ = g_strdup ("rhythmbox-client");
	_tmp1_ = g_new0 (gchar*, 1 + 1);
	_tmp1_[0] = _tmp0_;
	exec = _tmp1_;
	exec_length1 = 1;
	_exec_size_ = exec_length1;
	{
		gchar* _tmp2_;
		gchar* _tmp3_;
		gboolean _tmp4_;
		gchar** _tmp16_;
		gint _tmp16__length1;
		gchar* _tmp17_;
		gchar* _tmp18_;
		gchar** _tmp19_;
		gint _tmp19__length1;
		UnityActivationResponse* _tmp20_;
		_tmp2_ = g_uri_parse_scheme (uri);
		_tmp3_ = _tmp2_;
		_tmp4_ = g_strcmp0 (_tmp3_, "album") == 0;
		_g_free0 (_tmp3_);
		if (_tmp4_) {
			gchar* _tmp5_;
			gchar* album_key = NULL;
			gchar* _tmp6_;
			UnityMusicLensRhythmboxCollection* _tmp7_;
			const gchar* _tmp8_;
			GSList* _tmp9_;
			gchar** _tmp12_;
			gint _tmp12__length1;
			UnityActivationResponse* _tmp13_;
			_tmp5_ = g_strdup ("--enqueue");
			_vala_array_add1 (&exec, &exec_length1, &_exec_size_, _tmp5_);
			_tmp6_ = string_substring (uri, (glong) 8, (glong) -1);
			album_key = _tmp6_;
			_tmp7_ = self->priv->collection;
			_tmp8_ = album_key;
			_tmp9_ = unity_music_lens_rhythmbox_collection_get_album_tracks (_tmp7_, _tmp8_);
			{
				GSList* track_uri_collection = NULL;
				GSList* track_uri_it = NULL;
				track_uri_collection = _tmp9_;
				for (track_uri_it = track_uri_collection; track_uri_it != NULL; track_uri_it = track_uri_it->next) {
					const gchar* track_uri = NULL;
					track_uri = (const gchar*) track_uri_it->data;
					{
						const gchar* _tmp10_;
						gchar* _tmp11_;
						_tmp10_ = track_uri;
						_tmp11_ = g_strdup (_tmp10_);
						_vala_array_add2 (&exec, &exec_length1, &_exec_size_, _tmp11_);
					}
				}
				(track_uri_collection == NULL) ? NULL : (track_uri_collection = (g_slist_free (track_uri_collection), NULL));
			}
			_vala_array_add3 (&exec, &exec_length1, &_exec_size_, NULL);
			_tmp12_ = exec;
			_tmp12__length1 = exec_length1;
			unity_music_lens_rhythmbox_scope_prepare_rhythmbox_play_queue (self, _tmp12_, (gint) _tmp12__length1, NULL, NULL);
			_tmp13_ = unity_activation_response_new (UNITY_HANDLED_TYPE_HIDE_DASH, "");
			result = _tmp13_;
			_g_free0 (album_key);
			exec = (_vala_array_free (exec, exec_length1, (GDestroyNotify) g_free), NULL);
			return result;
		} else {
			gchar* _tmp14_;
			gchar* _tmp15_;
			_tmp14_ = g_strdup ("--play-uri");
			_vala_array_add4 (&exec, &exec_length1, &_exec_size_, _tmp14_);
			_tmp15_ = g_strdup (uri);
			_vala_array_add5 (&exec, &exec_length1, &_exec_size_, _tmp15_);
		}
		_vala_array_add6 (&exec, &exec_length1, &_exec_size_, NULL);
		_tmp16_ = exec;
		_tmp16__length1 = exec_length1;
		_tmp17_ = _vala_g_strjoinv (" ", _tmp16_, (gint) _tmp16__length1);
		_tmp18_ = _tmp17_;
		g_debug ("rhythmbox-scope.vala:225: Spawning rb '%s'", _tmp18_);
		_g_free0 (_tmp18_);
		_tmp19_ = exec;
		_tmp19__length1 = exec_length1;
		g_spawn_async (NULL, _tmp19_, NULL, G_SPAWN_SEARCH_PATH, NULL, NULL, NULL, &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			if (_inner_error0_->domain == G_SPAWN_ERROR) {
				goto __catch0_g_spawn_error;
			}
			exec = (_vala_array_free (exec, exec_length1, (GDestroyNotify) g_free), NULL);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return NULL;
		}
		_tmp20_ = unity_activation_response_new (UNITY_HANDLED_TYPE_HIDE_DASH, "");
		result = _tmp20_;
		exec = (_vala_array_free (exec, exec_length1, (GDestroyNotify) g_free), NULL);
		return result;
	}
	goto __finally0;
	__catch0_g_spawn_error:
	{
		UnityActivationResponse* _tmp21_;
		g_clear_error (&_inner_error0_);
		g_warning ("rhythmbox-scope.vala:235: Failed to launch URI %s", uri);
		_tmp21_ = unity_activation_response_new (UNITY_HANDLED_TYPE_NOT_HANDLED, "");
		result = _tmp21_;
		exec = (_vala_array_free (exec, exec_length1, (GDestroyNotify) g_free), NULL);
		return result;
	}
	__finally0:
	exec = (_vala_array_free (exec, exec_length1, (GDestroyNotify) g_free), NULL);
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
	g_clear_error (&_inner_error0_);
	return NULL;
}

static inline void
_g_list_free__g_object_unref0_ (GList* self)
{
	g_list_free_full (self, (GDestroyNotify) _g_object_unref0_);
}

static void
unity_music_lens_rhythmbox_scope_real_perform_search_data_free (gpointer _data)
{
	UnityMusicLensRhythmboxScopePerformSearchData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->search);
	(_data_->filters == NULL) ? NULL : (_data_->filters = (_g_list_free__g_object_unref0_ (_data_->filters), NULL));
	_g_object_unref0 (_data_->cancellable);
	_g_object_unref0 (_data_->self);
	g_slice_free (UnityMusicLensRhythmboxScopePerformSearchData, _data_);
}

static void
unity_music_lens_rhythmbox_scope_real_perform_search (UnityMusicLensSimpleScope* base,
                                                      UnityDeprecatedScopeSearch* search,
                                                      UnitySearchType search_type,
                                                      GList* filters,
                                                      gint max_results,
                                                      GCancellable* cancellable,
                                                      GAsyncReadyCallback _callback_,
                                                      gpointer _user_data_)
{
	UnityMusicLensRhythmboxScope * self;
	UnityMusicLensRhythmboxScopePerformSearchData* _data_;
	UnityMusicLensRhythmboxScope* _tmp0_;
	UnityDeprecatedScopeSearch* _tmp1_;
	GCancellable* _tmp2_;
	g_return_if_fail (search != NULL);
	self = (UnityMusicLensRhythmboxScope*) base;
	_data_ = g_slice_new0 (UnityMusicLensRhythmboxScopePerformSearchData);
	_data_->_async_result = g_task_new (G_OBJECT (self), cancellable, _callback_, _user_data_);
	g_task_set_task_data (_data_->_async_result, _data_, unity_music_lens_rhythmbox_scope_real_perform_search_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	_tmp1_ = _g_object_ref0 (search);
	_g_object_unref0 (_data_->search);
	_data_->search = _tmp1_;
	_data_->search_type = search_type;
	(_data_->filters == NULL) ? NULL : (_data_->filters = (_g_list_free__g_object_unref0_ (_data_->filters), NULL));
	_data_->filters = filters;
	_data_->max_results = max_results;
	_tmp2_ = _g_object_ref0 (cancellable);
	_g_object_unref0 (_data_->cancellable);
	_data_->cancellable = _tmp2_;
	unity_music_lens_rhythmbox_scope_real_perform_search_co (_data_);
}

static void
unity_music_lens_rhythmbox_scope_perform_search_finish (UnityMusicLensSimpleScope* base,
                                                        GAsyncResult* _res_)
{
	UnityMusicLensRhythmboxScopePerformSearchData* _data_;
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
	if (NULL == _data_) {
		return;
	}
}

static void
_____lambda15_ (UnityMusicLensRhythmboxScope* self)
{
	self->priv->db_ready = FALSE;
}

static void
______lambda15__g_file_monitor_changed (GFileMonitor* _sender,
                                        GFile* file,
                                        GFile* other_file,
                                        GFileMonitorEvent event_type,
                                        gpointer self)
{
	_____lambda15_ ((UnityMusicLensRhythmboxScope*) self);
}

static gboolean
unity_music_lens_rhythmbox_scope_real_perform_search_co (UnityMusicLensRhythmboxScopePerformSearchData* _data_)
{
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->category_override = -1;
	if (_data_->search_type == UNITY_SEARCH_TYPE_GLOBAL) {
		_data_->category_override = (gint) UNITY_MUSIC_LENS_CATEGORY_MUSIC;
		if (unity_music_lens_simple_scope_is_search_empty ((UnityMusicLensSimpleScope*) _data_->self, _data_->search)) {
			(_data_->filters == NULL) ? NULL : (_data_->filters = (_g_list_free__g_object_unref0_ (_data_->filters), NULL));
			g_task_return_pointer (_data_->_async_result, _data_, NULL);
			if (_data_->_state_ != 0) {
				while (!g_task_get_completed (_data_->_async_result)) {
					g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
				}
			}
			g_object_unref (_data_->_async_result);
			return FALSE;
		}
	}
	if (!_data_->self->priv->db_ready) {
		_data_->_tmp0_ = g_get_user_cache_dir ();
		_data_->_tmp1_ = g_build_filename (_data_->_tmp0_, "rhythmbox", "album-art", "store.tdb", NULL);
		_data_->tdb_path = _data_->_tmp1_;
		_data_->_tmp2_ = _data_->self->priv->collection;
		_data_->_tmp3_ = _data_->tdb_path;
		unity_music_lens_rhythmbox_collection_parse_metadata_file (_data_->_tmp2_, _data_->_tmp3_);
		_data_->_tmp4_ = g_get_user_data_dir ();
		_data_->_tmp5_ = g_build_filename (_data_->_tmp4_, "rhythmbox", "rhythmdb.xml", NULL);
		_data_->xml_path = _data_->_tmp5_;
		_data_->_tmp6_ = _data_->self->priv->collection;
		_data_->_tmp7_ = _data_->xml_path;
		unity_music_lens_rhythmbox_collection_parse_file (_data_->_tmp6_, _data_->_tmp7_);
		_data_->_tmp8_ = _data_->self->priv->rb_xml_monitor;
		if (_data_->_tmp8_ == NULL) {
			_data_->_tmp9_ = _data_->xml_path;
			_data_->_tmp10_ = g_file_new_for_path (_data_->_tmp9_);
			_data_->xml_file = _data_->_tmp10_;
			{
				_data_->_tmp12_ = _data_->xml_file;
				_data_->_tmp13_ = g_file_monitor (_data_->_tmp12_, G_FILE_MONITOR_NONE, NULL, &_data_->_inner_error0_);
				_data_->_tmp11_ = _data_->_tmp13_;
				if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
					goto __catch0_g_error;
				}
				_data_->_tmp14_ = _data_->_tmp11_;
				_data_->_tmp11_ = NULL;
				_g_object_unref0 (_data_->self->priv->rb_xml_monitor);
				_data_->self->priv->rb_xml_monitor = _data_->_tmp14_;
				_data_->_tmp15_ = _data_->self->priv->rb_xml_monitor;
				g_signal_connect_object (_data_->_tmp15_, "changed", (GCallback) ______lambda15__g_file_monitor_changed, _data_->self, 0);
				_g_object_unref0 (_data_->_tmp11_);
			}
			goto __finally0;
			__catch0_g_error:
			{
				_data_->err = _data_->_inner_error0_;
				_data_->_inner_error0_ = NULL;
				_data_->_tmp16_ = _data_->err;
				_data_->_tmp17_ = _data_->_tmp16_->message;
				g_warning ("rhythmbox-scope.vala:276: %s", _data_->_tmp17_);
				_g_error_free0 (_data_->err);
			}
			__finally0:
			if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
				_g_object_unref0 (_data_->xml_file);
				_g_free0 (_data_->xml_path);
				_g_free0 (_data_->tdb_path);
				(_data_->filters == NULL) ? NULL : (_data_->filters = (_g_list_free__g_object_unref0_ (_data_->filters), NULL));
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error0_->message, g_quark_to_string (_data_->_inner_error0_->domain), _data_->_inner_error0_->code);
				g_clear_error (&_data_->_inner_error0_);
				g_object_unref (_data_->_async_result);
				return FALSE;
			}
			_g_object_unref0 (_data_->xml_file);
		}
		_data_->self->priv->db_ready = TRUE;
		_g_free0 (_data_->xml_path);
		_g_free0 (_data_->tdb_path);
	}
	_data_->_tmp18_ = _data_->self->priv->collection;
	unity_music_lens_rhythmbox_collection_search (_data_->_tmp18_, _data_->search, _data_->search_type, _data_->filters, _data_->max_results, _data_->category_override);
	(_data_->filters == NULL) ? NULL : (_data_->filters = (_g_list_free__g_object_unref0_ (_data_->filters), NULL));
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
	if (_data_->_state_ != 0) {
		while (!g_task_get_completed (_data_->_async_result)) {
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
		}
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}

static gint
unity_music_lens_rhythmbox_scope_real_get_num_results_without_search (UnityMusicLensSimpleScope* base)
{
	gint result;
	UnityMusicLensRhythmboxScope* self;
	self = (UnityMusicLensRhythmboxScope*) base;
	result = 100;
	return result;
}

static gint
unity_music_lens_rhythmbox_scope_real_get_num_results_global_search (UnityMusicLensSimpleScope* base)
{
	gint result;
	UnityMusicLensRhythmboxScope* self;
	self = (UnityMusicLensRhythmboxScope*) base;
	result = 20;
	return result;
}

static gint
unity_music_lens_rhythmbox_scope_real_get_num_results_lens_search (UnityMusicLensSimpleScope* base)
{
	gint result;
	UnityMusicLensRhythmboxScope* self;
	self = (UnityMusicLensRhythmboxScope*) base;
	result = 50;
	return result;
}

static void
unity_music_lens_rhythmbox_scope_class_init (UnityMusicLensRhythmboxScopeClass * klass,
                                             gpointer klass_data)
{
	unity_music_lens_rhythmbox_scope_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &UnityMusicLensRhythmboxScope_private_offset);
	((UnityMusicLensSimpleScopeClass *) klass)->perform_search = (void (*) (UnityMusicLensSimpleScope*, UnityDeprecatedScopeSearch*, UnitySearchType, GList*, gint, GCancellable*, GAsyncReadyCallback, gpointer)) unity_music_lens_rhythmbox_scope_real_perform_search;
	((UnityMusicLensSimpleScopeClass *) klass)->perform_search_finish = (void (*) (UnityMusicLensSimpleScope*, GAsyncResult*)) unity_music_lens_rhythmbox_scope_perform_search_finish;
	UNITY_MUSIC_LENS_SIMPLE_SCOPE_CLASS (klass)->get_num_results_without_search = (gint (*) (UnityMusicLensSimpleScope*)) unity_music_lens_rhythmbox_scope_real_get_num_results_without_search;
	UNITY_MUSIC_LENS_SIMPLE_SCOPE_CLASS (klass)->get_num_results_global_search = (gint (*) (UnityMusicLensSimpleScope*)) unity_music_lens_rhythmbox_scope_real_get_num_results_global_search;
	UNITY_MUSIC_LENS_SIMPLE_SCOPE_CLASS (klass)->get_num_results_lens_search = (gint (*) (UnityMusicLensSimpleScope*)) unity_music_lens_rhythmbox_scope_real_get_num_results_lens_search;
	G_OBJECT_CLASS (klass)->get_property = _vala_unity_music_lens_rhythmbox_scope_get_property;
	G_OBJECT_CLASS (klass)->finalize = unity_music_lens_rhythmbox_scope_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), UNITY_MUSIC_LENS_RHYTHMBOX_SCOPE_NUM_RESULTS_WITHOUT_SEARCH_PROPERTY, unity_music_lens_rhythmbox_scope_properties[UNITY_MUSIC_LENS_RHYTHMBOX_SCOPE_NUM_RESULTS_WITHOUT_SEARCH_PROPERTY] = g_param_spec_int ("num-results-without-search", "num-results-without-search", "num-results-without-search", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), UNITY_MUSIC_LENS_RHYTHMBOX_SCOPE_NUM_RESULTS_GLOBAL_SEARCH_PROPERTY, unity_music_lens_rhythmbox_scope_properties[UNITY_MUSIC_LENS_RHYTHMBOX_SCOPE_NUM_RESULTS_GLOBAL_SEARCH_PROPERTY] = g_param_spec_int ("num-results-global-search", "num-results-global-search", "num-results-global-search", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), UNITY_MUSIC_LENS_RHYTHMBOX_SCOPE_NUM_RESULTS_LENS_SEARCH_PROPERTY, unity_music_lens_rhythmbox_scope_properties[UNITY_MUSIC_LENS_RHYTHMBOX_SCOPE_NUM_RESULTS_LENS_SEARCH_PROPERTY] = g_param_spec_int ("num-results-lens-search", "num-results-lens-search", "num-results-lens-search", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
}

static void
unity_music_lens_rhythmbox_scope_instance_init (UnityMusicLensRhythmboxScope * self,
                                                gpointer klass)
{
	self->priv = unity_music_lens_rhythmbox_scope_get_instance_private (self);
}

static void
unity_music_lens_rhythmbox_scope_finalize (GObject * obj)
{
	UnityMusicLensRhythmboxScope * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, UNITY_MUSIC_LENS_TYPE_RHYTHMBOX_SCOPE, UnityMusicLensRhythmboxScope);
	_g_object_unref0 (self->priv->collection);
	_g_object_unref0 (self->priv->rb_xml_monitor);
	_g_object_unref0 (self->priv->music_preview);
	G_OBJECT_CLASS (unity_music_lens_rhythmbox_scope_parent_class)->finalize (obj);
}

static GType
unity_music_lens_rhythmbox_scope_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (UnityMusicLensRhythmboxScopeClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) unity_music_lens_rhythmbox_scope_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (UnityMusicLensRhythmboxScope), 0, (GInstanceInitFunc) unity_music_lens_rhythmbox_scope_instance_init, NULL };
	GType unity_music_lens_rhythmbox_scope_type_id;
	unity_music_lens_rhythmbox_scope_type_id = g_type_register_static (UNITY_MUSIC_LENS_TYPE_SIMPLE_SCOPE, "UnityMusicLensRhythmboxScope", &g_define_type_info, 0);
	UnityMusicLensRhythmboxScope_private_offset = g_type_add_instance_private (unity_music_lens_rhythmbox_scope_type_id, sizeof (UnityMusicLensRhythmboxScopePrivate));
	return unity_music_lens_rhythmbox_scope_type_id;
}

GType
unity_music_lens_rhythmbox_scope_get_type (void)
{
	static volatile gsize unity_music_lens_rhythmbox_scope_type_id__once = 0;
	if (g_once_init_enter (&unity_music_lens_rhythmbox_scope_type_id__once)) {
		GType unity_music_lens_rhythmbox_scope_type_id;
		unity_music_lens_rhythmbox_scope_type_id = unity_music_lens_rhythmbox_scope_get_type_once ();
		g_once_init_leave (&unity_music_lens_rhythmbox_scope_type_id__once, unity_music_lens_rhythmbox_scope_type_id);
	}
	return unity_music_lens_rhythmbox_scope_type_id__once;
}

static void
_vala_unity_music_lens_rhythmbox_scope_get_property (GObject * object,
                                                     guint property_id,
                                                     GValue * value,
                                                     GParamSpec * pspec)
{
	UnityMusicLensRhythmboxScope * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, UNITY_MUSIC_LENS_TYPE_RHYTHMBOX_SCOPE, UnityMusicLensRhythmboxScope);
	switch (property_id) {
		case UNITY_MUSIC_LENS_RHYTHMBOX_SCOPE_NUM_RESULTS_WITHOUT_SEARCH_PROPERTY:
		g_value_set_int (value, unity_music_lens_simple_scope_get_num_results_without_search ((UnityMusicLensSimpleScope*) self));
		break;
		case UNITY_MUSIC_LENS_RHYTHMBOX_SCOPE_NUM_RESULTS_GLOBAL_SEARCH_PROPERTY:
		g_value_set_int (value, unity_music_lens_simple_scope_get_num_results_global_search ((UnityMusicLensSimpleScope*) self));
		break;
		case UNITY_MUSIC_LENS_RHYTHMBOX_SCOPE_NUM_RESULTS_LENS_SEARCH_PROPERTY:
		g_value_set_int (value, unity_music_lens_simple_scope_get_num_results_lens_search ((UnityMusicLensSimpleScope*) self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_vala_array_destroy (gpointer array,
                     gssize array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gssize i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gssize array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

