.TH pygeis 1 "February 12, 2013" "" "pygeis"

.SH NAME
pygeis \- test operation of the GEIS API Python bindings

.SH SYNOPSIS
.B pygeis [ 
.B \-V
.B ]
.br

.SH DESCRIPTION
This manual page explains the
.B pygeis
program. This program is a test driver for verifying the recognition and
propagation of gestures through the GEIS API Python bindings.

Hitting any key on the keyboard will exit the program gracefully.

.SH OPTIONS
.IP \-V
Prints the version number of the program and exits.

.SH ENVIRONMENT
.IP GEIS_DEBUG
Enables GEIS library diagnostic messages on stderr.

.SH "SEE ALSO"
gesturetest(1)
