/* Generated by dbus-binding-tool; do not edit! */

#include <glib.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef _DBUS_GLIB_ASYNC_DATA_FREE
#define _DBUS_GLIB_ASYNC_DATA_FREE
static inline void
_dbus_glib_async_data_free (gpointer stuff)
{
	g_slice_free (DBusGAsyncData, stuff);
}
#endif

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_org_kde_StatusNotifierWatcher
#define DBUS_GLIB_CLIENT_WRAPPERS_org_kde_StatusNotifierWatcher

static inline gboolean
org_kde_StatusNotifierWatcher_register_status_notifier_item (DBusGProxy *proxy, const char * IN_service, GError **error)

{
  return dbus_g_proxy_call (proxy, "RegisterStatusNotifierItem", error, G_TYPE_STRING, IN_service, G_TYPE_INVALID, G_TYPE_INVALID);
}

typedef void (*org_kde_StatusNotifierWatcher_register_status_notifier_item_reply) (DBusGProxy *proxy, GError *error, gpointer userdata);

static void
org_kde_StatusNotifierWatcher_register_status_notifier_item_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INVALID);
  (*(org_kde_StatusNotifierWatcher_register_status_notifier_item_reply)data->cb) (proxy, error, data->userdata);
  return;
}

static inline DBusGProxyCall*
org_kde_StatusNotifierWatcher_register_status_notifier_item_async (DBusGProxy *proxy, const char * IN_service, org_kde_StatusNotifierWatcher_register_status_notifier_item_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "RegisterStatusNotifierItem", org_kde_StatusNotifierWatcher_register_status_notifier_item_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_STRING, IN_service, G_TYPE_INVALID);
}
static inline gboolean
org_kde_StatusNotifierWatcher_register_status_notifier_host (DBusGProxy *proxy, const char * IN_service, GError **error)

{
  return dbus_g_proxy_call (proxy, "RegisterStatusNotifierHost", error, G_TYPE_STRING, IN_service, G_TYPE_INVALID, G_TYPE_INVALID);
}

typedef void (*org_kde_StatusNotifierWatcher_register_status_notifier_host_reply) (DBusGProxy *proxy, GError *error, gpointer userdata);

static void
org_kde_StatusNotifierWatcher_register_status_notifier_host_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INVALID);
  (*(org_kde_StatusNotifierWatcher_register_status_notifier_host_reply)data->cb) (proxy, error, data->userdata);
  return;
}

static inline DBusGProxyCall*
org_kde_StatusNotifierWatcher_register_status_notifier_host_async (DBusGProxy *proxy, const char * IN_service, org_kde_StatusNotifierWatcher_register_status_notifier_host_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "RegisterStatusNotifierHost", org_kde_StatusNotifierWatcher_register_status_notifier_host_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_STRING, IN_service, G_TYPE_INVALID);
}
#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_org_kde_StatusNotifierWatcher */

G_END_DECLS
