/* test-xapian-utils.c generated by valac 0.56.19, the Vala compiler
 * generated from test-xapian-utils.vala, do not modify */

/*
 * Copyright (C) 2012 Canonical Ltd
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Authored by Pawel Stolowski <pawel.stolowski@canonical.com>
 */

#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <unity.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

static gint unity_applications_lens_main (gchar** args,
                                   gint args_length1);
VALA_EXTERN void unity_applications_lens_test_empty_search_query (void);
static void _unity_applications_lens_test_empty_search_query_gtest_data_func (gpointer self);
VALA_EXTERN void unity_applications_lens_test_empty_search_with_single_cat_filter (void);
static void _unity_applications_lens_test_empty_search_with_single_cat_filter_gtest_data_func (gpointer self);
VALA_EXTERN void unity_applications_lens_test_empty_search_with_multi_cat_filter (void);
static void _unity_applications_lens_test_empty_search_with_multi_cat_filter_gtest_data_func (gpointer self);
VALA_EXTERN void unity_applications_lens_test_search_query_no_filters (void);
static void _unity_applications_lens_test_search_query_no_filters_gtest_data_func (gpointer self);
VALA_EXTERN void unity_applications_lens_test_search_query_with_single_cat_filter (void);
static void _unity_applications_lens_test_search_query_with_single_cat_filter_gtest_data_func (gpointer self);
VALA_EXTERN void unity_applications_lens_test_search_query_with_multi_cat_filter (void);
static void _unity_applications_lens_test_search_query_with_multi_cat_filter_gtest_data_func (gpointer self);
VALA_EXTERN void unity_applications_lens_test_zg_empty_search_query (void);
static void _unity_applications_lens_test_zg_empty_search_query_gtest_data_func (gpointer self);
VALA_EXTERN void unity_applications_lens_test_zg_empty_search_with_single_cat_filter (void);
static void _unity_applications_lens_test_zg_empty_search_with_single_cat_filter_gtest_data_func (gpointer self);
VALA_EXTERN void unity_applications_lens_test_zg_empty_search_with_multi_cat_filter (void);
static void _unity_applications_lens_test_zg_empty_search_with_multi_cat_filter_gtest_data_func (gpointer self);
VALA_EXTERN void unity_applications_lens_test_zg_search_query_no_filters (void);
static void _unity_applications_lens_test_zg_search_query_no_filters_gtest_data_func (gpointer self);
VALA_EXTERN void unity_applications_lens_test_zg_search_query_with_single_cat_filter (void);
static void _unity_applications_lens_test_zg_search_query_with_single_cat_filter_gtest_data_func (gpointer self);
VALA_EXTERN void unity_applications_lens_test_zg_search_query_with_multi_cat_filter (void);
static void _unity_applications_lens_test_zg_search_query_with_multi_cat_filter_gtest_data_func (gpointer self);
VALA_EXTERN gchar* unity_applications_lens_xapian_utils_prepare_pkg_search_string (const gchar* search_string,
                                                                       UnityOptionsFilter* options);
VALA_EXTERN gchar* unity_applications_lens_xapian_utils_prepare_zg_search_string (const gchar* search_string,
                                                                      UnityOptionsFilter* options);

static void
_unity_applications_lens_test_empty_search_query_gtest_data_func (gpointer self)
{
	unity_applications_lens_test_empty_search_query ();
}

static void
_unity_applications_lens_test_empty_search_with_single_cat_filter_gtest_data_func (gpointer self)
{
	unity_applications_lens_test_empty_search_with_single_cat_filter ();
}

static void
_unity_applications_lens_test_empty_search_with_multi_cat_filter_gtest_data_func (gpointer self)
{
	unity_applications_lens_test_empty_search_with_multi_cat_filter ();
}

static void
_unity_applications_lens_test_search_query_no_filters_gtest_data_func (gpointer self)
{
	unity_applications_lens_test_search_query_no_filters ();
}

static void
_unity_applications_lens_test_search_query_with_single_cat_filter_gtest_data_func (gpointer self)
{
	unity_applications_lens_test_search_query_with_single_cat_filter ();
}

static void
_unity_applications_lens_test_search_query_with_multi_cat_filter_gtest_data_func (gpointer self)
{
	unity_applications_lens_test_search_query_with_multi_cat_filter ();
}

static void
_unity_applications_lens_test_zg_empty_search_query_gtest_data_func (gpointer self)
{
	unity_applications_lens_test_zg_empty_search_query ();
}

static void
_unity_applications_lens_test_zg_empty_search_with_single_cat_filter_gtest_data_func (gpointer self)
{
	unity_applications_lens_test_zg_empty_search_with_single_cat_filter ();
}

static void
_unity_applications_lens_test_zg_empty_search_with_multi_cat_filter_gtest_data_func (gpointer self)
{
	unity_applications_lens_test_zg_empty_search_with_multi_cat_filter ();
}

static void
_unity_applications_lens_test_zg_search_query_no_filters_gtest_data_func (gpointer self)
{
	unity_applications_lens_test_zg_search_query_no_filters ();
}

static void
_unity_applications_lens_test_zg_search_query_with_single_cat_filter_gtest_data_func (gpointer self)
{
	unity_applications_lens_test_zg_search_query_with_single_cat_filter ();
}

static void
_unity_applications_lens_test_zg_search_query_with_multi_cat_filter_gtest_data_func (gpointer self)
{
	unity_applications_lens_test_zg_search_query_with_multi_cat_filter ();
}

static gint
unity_applications_lens_main (gchar** args,
                              gint args_length1)
{
	gint result;
	g_test_init ((gint*) (&args_length1), &args, NULL);
	g_test_add_data_func ("/Unit/EmptySearchQuery", NULL, _unity_applications_lens_test_empty_search_query_gtest_data_func);
	g_test_add_data_func ("/Unit/EmptySearchWithSingleCategoryFilter", NULL, _unity_applications_lens_test_empty_search_with_single_cat_filter_gtest_data_func);
	g_test_add_data_func ("/Unit/EmptySearchWithMultipleCategoryFilter", NULL, _unity_applications_lens_test_empty_search_with_multi_cat_filter_gtest_data_func);
	g_test_add_data_func ("/Unit/SearchQueryWithNoFilters", NULL, _unity_applications_lens_test_search_query_no_filters_gtest_data_func);
	g_test_add_data_func ("/Unit/SearchQueryWithSingleCategoryFilter", NULL, _unity_applications_lens_test_search_query_with_single_cat_filter_gtest_data_func);
	g_test_add_data_func ("/Unit/SearchQueryWithMultipleCategoryFilter", NULL, _unity_applications_lens_test_search_query_with_multi_cat_filter_gtest_data_func);
	g_test_add_data_func ("/Unit/ZgEmptySearchQuery", NULL, _unity_applications_lens_test_zg_empty_search_query_gtest_data_func);
	g_test_add_data_func ("/Unit/ZgEmptySearchWithSingleCategoryFilter", NULL, _unity_applications_lens_test_zg_empty_search_with_single_cat_filter_gtest_data_func);
	g_test_add_data_func ("/Unit/ZgEmptySearchWithMultipleCategoryFilter", NULL, _unity_applications_lens_test_zg_empty_search_with_multi_cat_filter_gtest_data_func);
	g_test_add_data_func ("/Unit/ZgSearchQuery", NULL, _unity_applications_lens_test_zg_search_query_no_filters_gtest_data_func);
	g_test_add_data_func ("/Unit/ZgSearchQueryWithSingleCategoryFilter", NULL, _unity_applications_lens_test_zg_search_query_with_single_cat_filter_gtest_data_func);
	g_test_add_data_func ("/Unit/ZgSearchQueryWithMultipleCategoryFilter", NULL, _unity_applications_lens_test_zg_search_query_with_multi_cat_filter_gtest_data_func);
	g_test_run ();
	result = 0;
	return result;
}

int
main (int argc,
      char ** argv)
{
	return unity_applications_lens_main (argv, argc);
}

void
unity_applications_lens_test_empty_search_query (void)
{
	gchar* query = NULL;
	gchar* _tmp0_;
	_tmp0_ = unity_applications_lens_xapian_utils_prepare_pkg_search_string ("", NULL);
	query = _tmp0_;
	_vala_assert (g_strcmp0 (query, "(type:Application OR type:Scope)") == 0, "query == \"(type:Application OR type:Scope)\"");
	_g_free0 (query);
}

void
unity_applications_lens_test_empty_search_with_single_cat_filter (void)
{
	UnityCheckOptionFilter* filter = NULL;
	UnityCheckOptionFilter* _tmp0_;
	UnityFilterOption* _tmp1_;
	UnityFilterOption* _tmp2_;
	UnityFilterOption* _tmp3_;
	UnityFilterOption* _tmp4_;
	gchar* query = NULL;
	gchar* _tmp5_;
	_tmp0_ = unity_check_option_filter_new ("filter", "Filter", NULL, FALSE);
	filter = _tmp0_;
	unity_filter_set_filtering ((UnityFilter*) filter, TRUE);
	_tmp1_ = unity_options_filter_add_option ((UnityOptionsFilter*) filter, "media", "Media", NULL);
	_tmp2_ = _tmp1_;
	unity_filter_option_set_active (_tmp2_, TRUE);
	_g_object_unref0 (_tmp2_);
	_tmp3_ = unity_options_filter_add_option ((UnityOptionsFilter*) filter, "internet", "Internet", NULL);
	_tmp4_ = _tmp3_;
	_g_object_unref0 (_tmp4_);
	_tmp5_ = unity_applications_lens_xapian_utils_prepare_pkg_search_string ("", (UnityOptionsFilter*) filter);
	query = _tmp5_;
	_vala_assert (g_strcmp0 (query, "(type:Application OR type:Scope) AND (category:AudioVideo)") == 0, "query == \"(type:Application OR type:Scope) AND (category:AudioVideo)\"");
	_g_free0 (query);
	_g_object_unref0 (filter);
}

void
unity_applications_lens_test_empty_search_with_multi_cat_filter (void)
{
	UnityCheckOptionFilter* filter = NULL;
	UnityCheckOptionFilter* _tmp0_;
	UnityFilterOption* _tmp1_;
	UnityFilterOption* _tmp2_;
	UnityFilterOption* _tmp3_;
	UnityFilterOption* _tmp4_;
	UnityFilterOption* _tmp5_;
	UnityFilterOption* _tmp6_;
	gchar* query = NULL;
	gchar* _tmp7_;
	_tmp0_ = unity_check_option_filter_new ("filter", "Filter", NULL, FALSE);
	filter = _tmp0_;
	unity_filter_set_filtering ((UnityFilter*) filter, TRUE);
	_tmp1_ = unity_options_filter_add_option ((UnityOptionsFilter*) filter, "media", "Media", NULL);
	_tmp2_ = _tmp1_;
	unity_filter_option_set_active (_tmp2_, TRUE);
	_g_object_unref0 (_tmp2_);
	_tmp3_ = unity_options_filter_add_option ((UnityOptionsFilter*) filter, "internet", "Internet", NULL);
	_tmp4_ = _tmp3_;
	_g_object_unref0 (_tmp4_);
	_tmp5_ = unity_options_filter_add_option ((UnityOptionsFilter*) filter, "game", "Game", NULL);
	_tmp6_ = _tmp5_;
	unity_filter_option_set_active (_tmp6_, TRUE);
	_g_object_unref0 (_tmp6_);
	_tmp7_ = unity_applications_lens_xapian_utils_prepare_pkg_search_string ("", (UnityOptionsFilter*) filter);
	query = _tmp7_;
	_vala_assert (g_strcmp0 (query, "(type:Application OR type:Scope) AND (category:Game OR category:AudioV" \
"ideo)") == 0, "query == \"(type:Application OR type:Scope) AND (category:Game OR category:AudioVideo)\"");
	_g_free0 (query);
	_g_object_unref0 (filter);
}

void
unity_applications_lens_test_search_query_no_filters (void)
{
	gchar* query = NULL;
	gchar* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	const gchar* _tmp3_;
	_tmp0_ = unity_applications_lens_xapian_utils_prepare_pkg_search_string (" foo ", NULL);
	query = _tmp0_;
	_tmp1_ = query;
	_vala_assert (g_strcmp0 (_tmp1_, "(type:Application OR type:Scope) AND foo") == 0, "query == \"(type:Application OR type:Scope) AND foo\"");
	_tmp2_ = unity_applications_lens_xapian_utils_prepare_pkg_search_string ("foo", NULL);
	_g_free0 (query);
	query = _tmp2_;
	_tmp3_ = query;
	_vala_assert (g_strcmp0 (_tmp3_, "(type:Application OR type:Scope) AND foo") == 0, "query == \"(type:Application OR type:Scope) AND foo\"");
	_g_free0 (query);
}

void
unity_applications_lens_test_search_query_with_single_cat_filter (void)
{
	UnityCheckOptionFilter* filter = NULL;
	UnityCheckOptionFilter* _tmp0_;
	UnityFilterOption* _tmp1_;
	UnityFilterOption* _tmp2_;
	UnityFilterOption* _tmp3_;
	UnityFilterOption* _tmp4_;
	gchar* query = NULL;
	gchar* _tmp5_;
	_tmp0_ = unity_check_option_filter_new ("filter", "Filter", NULL, FALSE);
	filter = _tmp0_;
	unity_filter_set_filtering ((UnityFilter*) filter, TRUE);
	_tmp1_ = unity_options_filter_add_option ((UnityOptionsFilter*) filter, "media", "Media", NULL);
	_tmp2_ = _tmp1_;
	_g_object_unref0 (_tmp2_);
	_tmp3_ = unity_options_filter_add_option ((UnityOptionsFilter*) filter, "internet", "Internet", NULL);
	_tmp4_ = _tmp3_;
	unity_filter_option_set_active (_tmp4_, TRUE);
	_g_object_unref0 (_tmp4_);
	_tmp5_ = unity_applications_lens_xapian_utils_prepare_pkg_search_string ("foo", (UnityOptionsFilter*) filter);
	query = _tmp5_;
	_vala_assert (g_strcmp0 (query, "(type:Application OR type:Scope) AND (category:Network) AND foo") == 0, "query == \"(type:Application OR type:Scope) AND (category:Network) AND foo\"");
	_g_free0 (query);
	_g_object_unref0 (filter);
}

void
unity_applications_lens_test_search_query_with_multi_cat_filter (void)
{
	UnityCheckOptionFilter* filter = NULL;
	UnityCheckOptionFilter* _tmp0_;
	UnityFilterOption* _tmp1_;
	UnityFilterOption* _tmp2_;
	UnityFilterOption* _tmp3_;
	UnityFilterOption* _tmp4_;
	UnityFilterOption* _tmp5_;
	UnityFilterOption* _tmp6_;
	gchar* query = NULL;
	gchar* _tmp7_;
	_tmp0_ = unity_check_option_filter_new ("filter", "Filter", NULL, FALSE);
	filter = _tmp0_;
	unity_filter_set_filtering ((UnityFilter*) filter, TRUE);
	_tmp1_ = unity_options_filter_add_option ((UnityOptionsFilter*) filter, "media", "Media", NULL);
	_tmp2_ = _tmp1_;
	_g_object_unref0 (_tmp2_);
	_tmp3_ = unity_options_filter_add_option ((UnityOptionsFilter*) filter, "internet", "Internet", NULL);
	_tmp4_ = _tmp3_;
	unity_filter_option_set_active (_tmp4_, TRUE);
	_g_object_unref0 (_tmp4_);
	_tmp5_ = unity_options_filter_add_option ((UnityOptionsFilter*) filter, "game", "Game", NULL);
	_tmp6_ = _tmp5_;
	unity_filter_option_set_active (_tmp6_, TRUE);
	_g_object_unref0 (_tmp6_);
	_tmp7_ = unity_applications_lens_xapian_utils_prepare_pkg_search_string ("foo", (UnityOptionsFilter*) filter);
	query = _tmp7_;
	_vala_assert (g_strcmp0 (query, "(type:Application OR type:Scope) AND (category:Game OR category:Networ" \
"k) AND foo") == 0, "query == \"(type:Application OR type:Scope) AND (category:Game OR category:Network) AND foo\"");
	_g_free0 (query);
	_g_object_unref0 (filter);
}

void
unity_applications_lens_test_zg_empty_search_query (void)
{
	gchar* query = NULL;
	gchar* _tmp0_;
	_tmp0_ = unity_applications_lens_xapian_utils_prepare_zg_search_string ("", NULL);
	query = _tmp0_;
	_vala_assert (g_strcmp0 (query, "NOT category:XYZ") == 0, "query == \"NOT category:XYZ\"");
	_g_free0 (query);
}

void
unity_applications_lens_test_zg_empty_search_with_single_cat_filter (void)
{
	UnityCheckOptionFilter* filter = NULL;
	UnityCheckOptionFilter* _tmp0_;
	UnityFilterOption* _tmp1_;
	UnityFilterOption* _tmp2_;
	UnityFilterOption* _tmp3_;
	UnityFilterOption* _tmp4_;
	gchar* query = NULL;
	gchar* _tmp5_;
	_tmp0_ = unity_check_option_filter_new ("filter", "Filter", NULL, FALSE);
	filter = _tmp0_;
	unity_filter_set_filtering ((UnityFilter*) filter, TRUE);
	_tmp1_ = unity_options_filter_add_option ((UnityOptionsFilter*) filter, "media", "Media", NULL);
	_tmp2_ = _tmp1_;
	_g_object_unref0 (_tmp2_);
	_tmp3_ = unity_options_filter_add_option ((UnityOptionsFilter*) filter, "office", "Office", NULL);
	_tmp4_ = _tmp3_;
	unity_filter_option_set_active (_tmp4_, TRUE);
	_g_object_unref0 (_tmp4_);
	_tmp5_ = unity_applications_lens_xapian_utils_prepare_zg_search_string ("", (UnityOptionsFilter*) filter);
	query = _tmp5_;
	_vala_assert (g_strcmp0 (query, "(category:Office)") == 0, "query == \"(category:Office)\"");
	_g_free0 (query);
	_g_object_unref0 (filter);
}

void
unity_applications_lens_test_zg_empty_search_with_multi_cat_filter (void)
{
	UnityCheckOptionFilter* filter = NULL;
	UnityCheckOptionFilter* _tmp0_;
	UnityFilterOption* _tmp1_;
	UnityFilterOption* _tmp2_;
	UnityFilterOption* _tmp3_;
	UnityFilterOption* _tmp4_;
	UnityFilterOption* _tmp5_;
	UnityFilterOption* _tmp6_;
	gchar* query = NULL;
	gchar* _tmp7_;
	_tmp0_ = unity_check_option_filter_new ("filter", "Filter", NULL, FALSE);
	filter = _tmp0_;
	unity_filter_set_filtering ((UnityFilter*) filter, TRUE);
	_tmp1_ = unity_options_filter_add_option ((UnityOptionsFilter*) filter, "media", "Media", NULL);
	_tmp2_ = _tmp1_;
	_g_object_unref0 (_tmp2_);
	_tmp3_ = unity_options_filter_add_option ((UnityOptionsFilter*) filter, "office", "Office", NULL);
	_tmp4_ = _tmp3_;
	unity_filter_option_set_active (_tmp4_, TRUE);
	_g_object_unref0 (_tmp4_);
	_tmp5_ = unity_options_filter_add_option ((UnityOptionsFilter*) filter, "customization", "Customization", NULL);
	_tmp6_ = _tmp5_;
	unity_filter_option_set_active (_tmp6_, TRUE);
	_g_object_unref0 (_tmp6_);
	_tmp7_ = unity_applications_lens_xapian_utils_prepare_zg_search_string ("", (UnityOptionsFilter*) filter);
	query = _tmp7_;
	_vala_assert (g_strcmp0 (query, "(category:Office OR category:Settings)") == 0, "query == \"(category:Office OR category:Settings)\"");
	_g_free0 (query);
	_g_object_unref0 (filter);
}

void
unity_applications_lens_test_zg_search_query_no_filters (void)
{
	gchar* query = NULL;
	gchar* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	const gchar* _tmp3_;
	_tmp0_ = unity_applications_lens_xapian_utils_prepare_zg_search_string (" foo ", NULL);
	query = _tmp0_;
	_tmp1_ = query;
	_vala_assert (g_strcmp0 (_tmp1_, "app:(foo*)") == 0, "query == \"app:(foo*)\"");
	_tmp2_ = unity_applications_lens_xapian_utils_prepare_zg_search_string (" foo*", NULL);
	_g_free0 (query);
	query = _tmp2_;
	_tmp3_ = query;
	_vala_assert (g_strcmp0 (_tmp3_, "app:(foo*)") == 0, "query == \"app:(foo*)\"");
	_g_free0 (query);
}

void
unity_applications_lens_test_zg_search_query_with_single_cat_filter (void)
{
	UnityCheckOptionFilter* filter = NULL;
	UnityCheckOptionFilter* _tmp0_;
	UnityFilterOption* _tmp1_;
	UnityFilterOption* _tmp2_;
	UnityFilterOption* _tmp3_;
	UnityFilterOption* _tmp4_;
	gchar* query = NULL;
	gchar* _tmp5_;
	_tmp0_ = unity_check_option_filter_new ("filter", "Filter", NULL, FALSE);
	filter = _tmp0_;
	unity_filter_set_filtering ((UnityFilter*) filter, TRUE);
	_tmp1_ = unity_options_filter_add_option ((UnityOptionsFilter*) filter, "media", "Media", NULL);
	_tmp2_ = _tmp1_;
	_g_object_unref0 (_tmp2_);
	_tmp3_ = unity_options_filter_add_option ((UnityOptionsFilter*) filter, "internet", "Internet", NULL);
	_tmp4_ = _tmp3_;
	unity_filter_option_set_active (_tmp4_, TRUE);
	_g_object_unref0 (_tmp4_);
	_tmp5_ = unity_applications_lens_xapian_utils_prepare_zg_search_string (" foo* ", (UnityOptionsFilter*) filter);
	query = _tmp5_;
	_vala_assert (g_strcmp0 (query, "app:(foo*) AND (category:Network)") == 0, "query == \"app:(foo*) AND (category:Network)\"");
	_g_free0 (query);
	_g_object_unref0 (filter);
}

void
unity_applications_lens_test_zg_search_query_with_multi_cat_filter (void)
{
	UnityCheckOptionFilter* filter = NULL;
	UnityCheckOptionFilter* _tmp0_;
	UnityFilterOption* _tmp1_;
	UnityFilterOption* _tmp2_;
	UnityFilterOption* _tmp3_;
	UnityFilterOption* _tmp4_;
	UnityFilterOption* _tmp5_;
	UnityFilterOption* _tmp6_;
	gchar* query = NULL;
	gchar* _tmp7_;
	_tmp0_ = unity_check_option_filter_new ("filter", "Filter", NULL, FALSE);
	filter = _tmp0_;
	unity_filter_set_filtering ((UnityFilter*) filter, TRUE);
	_tmp1_ = unity_options_filter_add_option ((UnityOptionsFilter*) filter, "media", "Media", NULL);
	_tmp2_ = _tmp1_;
	_g_object_unref0 (_tmp2_);
	_tmp3_ = unity_options_filter_add_option ((UnityOptionsFilter*) filter, "internet", "Internet", NULL);
	_tmp4_ = _tmp3_;
	unity_filter_option_set_active (_tmp4_, TRUE);
	_g_object_unref0 (_tmp4_);
	_tmp5_ = unity_options_filter_add_option ((UnityOptionsFilter*) filter, "game", "Game", NULL);
	_tmp6_ = _tmp5_;
	unity_filter_option_set_active (_tmp6_, TRUE);
	_g_object_unref0 (_tmp6_);
	_tmp7_ = unity_applications_lens_xapian_utils_prepare_zg_search_string (" foo* ", (UnityOptionsFilter*) filter);
	query = _tmp7_;
	_vala_assert (g_strcmp0 (query, "app:(foo*) AND (category:Game OR category:Network)") == 0, "query == \"app:(foo*) AND (category:Game OR category:Network)\"");
	_g_free0 (query);
	_g_object_unref0 (filter);
}

