/* test-software-center-utils.c generated by valac 0.56.19, the Vala compiler
 * generated from test-software-center-utils.vala, do not modify */

/*
 * Copyright (C) 2012 Canonical Ltd
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Authored by Pawel Stolowski <pawel.stolowski@canonical.com>
 */

#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <glib-object.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define UNITY_APPLICATIONS_LENS_SOFTWARE_CENTER_UTILS_TYPE_MANGLED_DESKTOP_FILE_LOOKUP (unity_applications_lens_software_center_utils_mangled_desktop_file_lookup_get_type ())
#define UNITY_APPLICATIONS_LENS_SOFTWARE_CENTER_UTILS_MANGLED_DESKTOP_FILE_LOOKUP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), UNITY_APPLICATIONS_LENS_SOFTWARE_CENTER_UTILS_TYPE_MANGLED_DESKTOP_FILE_LOOKUP, UnityApplicationsLensSoftwareCenterUtilsMangledDesktopFileLookup))
#define UNITY_APPLICATIONS_LENS_SOFTWARE_CENTER_UTILS_MANGLED_DESKTOP_FILE_LOOKUP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), UNITY_APPLICATIONS_LENS_SOFTWARE_CENTER_UTILS_TYPE_MANGLED_DESKTOP_FILE_LOOKUP, UnityApplicationsLensSoftwareCenterUtilsMangledDesktopFileLookupClass))
#define UNITY_APPLICATIONS_LENS_SOFTWARE_CENTER_UTILS_IS_MANGLED_DESKTOP_FILE_LOOKUP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), UNITY_APPLICATIONS_LENS_SOFTWARE_CENTER_UTILS_TYPE_MANGLED_DESKTOP_FILE_LOOKUP))
#define UNITY_APPLICATIONS_LENS_SOFTWARE_CENTER_UTILS_IS_MANGLED_DESKTOP_FILE_LOOKUP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), UNITY_APPLICATIONS_LENS_SOFTWARE_CENTER_UTILS_TYPE_MANGLED_DESKTOP_FILE_LOOKUP))
#define UNITY_APPLICATIONS_LENS_SOFTWARE_CENTER_UTILS_MANGLED_DESKTOP_FILE_LOOKUP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), UNITY_APPLICATIONS_LENS_SOFTWARE_CENTER_UTILS_TYPE_MANGLED_DESKTOP_FILE_LOOKUP, UnityApplicationsLensSoftwareCenterUtilsMangledDesktopFileLookupClass))

typedef struct _UnityApplicationsLensSoftwareCenterUtilsMangledDesktopFileLookup UnityApplicationsLensSoftwareCenterUtilsMangledDesktopFileLookup;
typedef struct _UnityApplicationsLensSoftwareCenterUtilsMangledDesktopFileLookupClass UnityApplicationsLensSoftwareCenterUtilsMangledDesktopFileLookupClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _unity_applications_lens_software_center_utils_mangled_desktop_file_lookup_unref0(var) ((var == NULL) ? NULL : (var = (unity_applications_lens_software_center_utils_mangled_desktop_file_lookup_unref (var), NULL)))
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

static gint unity_applications_lens_main (gchar** args,
                                   gint args_length1);
VALA_EXTERN void unity_applications_lens_test_desktop_file_lookup_with_unmangling (void);
static void _unity_applications_lens_test_desktop_file_lookup_with_unmangling_gtest_data_func (gpointer self);
VALA_EXTERN void unity_applications_lens_test_desktop_file_lookup_without_unmangling (void);
static void _unity_applications_lens_test_desktop_file_lookup_without_unmangling_gtest_data_func (gpointer self);
VALA_EXTERN gpointer unity_applications_lens_software_center_utils_mangled_desktop_file_lookup_ref (gpointer instance);
VALA_EXTERN void unity_applications_lens_software_center_utils_mangled_desktop_file_lookup_unref (gpointer instance);
VALA_EXTERN GParamSpec* unity_applications_lens_software_center_utils_param_spec_mangled_desktop_file_lookup (const gchar* name,
                                                                                                  const gchar* nick,
                                                                                                  const gchar* blurb,
                                                                                                  GType object_type,
                                                                                                  GParamFlags flags);
VALA_EXTERN void unity_applications_lens_software_center_utils_value_set_mangled_desktop_file_lookup (GValue* value,
                                                                                          gpointer v_object);
VALA_EXTERN void unity_applications_lens_software_center_utils_value_take_mangled_desktop_file_lookup (GValue* value,
                                                                                           gpointer v_object);
VALA_EXTERN gpointer unity_applications_lens_software_center_utils_value_get_mangled_desktop_file_lookup (const GValue* value);
VALA_EXTERN GType unity_applications_lens_software_center_utils_mangled_desktop_file_lookup_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (UnityApplicationsLensSoftwareCenterUtilsMangledDesktopFileLookup, unity_applications_lens_software_center_utils_mangled_desktop_file_lookup_unref)
VALA_EXTERN UnityApplicationsLensSoftwareCenterUtilsMangledDesktopFileLookup* unity_applications_lens_software_center_utils_mangled_desktop_file_lookup_new (void);
VALA_EXTERN UnityApplicationsLensSoftwareCenterUtilsMangledDesktopFileLookup* unity_applications_lens_software_center_utils_mangled_desktop_file_lookup_construct (GType object_type);
VALA_EXTERN gchar* unity_applications_lens_software_center_utils_mangled_desktop_file_lookup_extract_desktop_id (UnityApplicationsLensSoftwareCenterUtilsMangledDesktopFileLookup* self,
                                                                                                     const gchar* desktop_file,
                                                                                                     gboolean unmangle);
VALA_EXTERN gboolean unity_applications_lens_software_center_utils_mangled_desktop_file_lookup_contains (UnityApplicationsLensSoftwareCenterUtilsMangledDesktopFileLookup* self,
                                                                                             const gchar* desktop_file);
VALA_EXTERN gchar* unity_applications_lens_software_center_utils_mangled_desktop_file_lookup_get (UnityApplicationsLensSoftwareCenterUtilsMangledDesktopFileLookup* self,
                                                                                      const gchar* desktop_file);

static void
_unity_applications_lens_test_desktop_file_lookup_with_unmangling_gtest_data_func (gpointer self)
{
	unity_applications_lens_test_desktop_file_lookup_with_unmangling ();
}

static void
_unity_applications_lens_test_desktop_file_lookup_without_unmangling_gtest_data_func (gpointer self)
{
	unity_applications_lens_test_desktop_file_lookup_without_unmangling ();
}

static gint
unity_applications_lens_main (gchar** args,
                              gint args_length1)
{
	gint result;
	g_test_init ((gint*) (&args_length1), &args, NULL);
	g_test_add_data_func ("/Unit/DesktopIdLookupWithMangling", NULL, _unity_applications_lens_test_desktop_file_lookup_with_unmangling_gtest_data_func);
	g_test_add_data_func ("/Unit/DesktopIdLookupWithoutMangling", NULL, _unity_applications_lens_test_desktop_file_lookup_without_unmangling_gtest_data_func);
	g_test_run ();
	result = 0;
	return result;
}

int
main (int argc,
      char ** argv)
{
	return unity_applications_lens_main (argv, argc);
}

void
unity_applications_lens_test_desktop_file_lookup_with_unmangling (void)
{
	UnityApplicationsLensSoftwareCenterUtilsMangledDesktopFileLookup* lookup = NULL;
	UnityApplicationsLensSoftwareCenterUtilsMangledDesktopFileLookup* _tmp0_;
	gchar* desktop_file = NULL;
	gchar* _tmp1_;
	gchar* _result_ = NULL;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	_tmp0_ = unity_applications_lens_software_center_utils_mangled_desktop_file_lookup_new ();
	lookup = _tmp0_;
	_tmp1_ = g_strdup ("/foo/bar/kde4:kde4__KCharSelect.desktop");
	desktop_file = _tmp1_;
	_tmp2_ = unity_applications_lens_software_center_utils_mangled_desktop_file_lookup_extract_desktop_id (lookup, desktop_file, TRUE);
	_result_ = _tmp2_;
	_vala_assert (g_strcmp0 (_result_, "kde4-KCharSelect.desktop") == 0, "result == \"kde4-KCharSelect.desktop\"");
	_vala_assert (unity_applications_lens_software_center_utils_mangled_desktop_file_lookup_contains (lookup, _result_) == TRUE, "lookup.contains (result) == true");
	_tmp3_ = unity_applications_lens_software_center_utils_mangled_desktop_file_lookup_get (lookup, _result_);
	_tmp4_ = _tmp3_;
	_vala_assert (g_strcmp0 (_tmp4_, "kde4__KCharSelect.desktop") == 0, "lookup.get (result) == \"kde4__KCharSelect.desktop\"");
	_g_free0 (_tmp4_);
	_g_free0 (_result_);
	_g_free0 (desktop_file);
	_unity_applications_lens_software_center_utils_mangled_desktop_file_lookup_unref0 (lookup);
}

void
unity_applications_lens_test_desktop_file_lookup_without_unmangling (void)
{
	UnityApplicationsLensSoftwareCenterUtilsMangledDesktopFileLookup* lookup = NULL;
	UnityApplicationsLensSoftwareCenterUtilsMangledDesktopFileLookup* _tmp0_;
	gchar* desktop_file = NULL;
	gchar* _tmp1_;
	gchar* _result_ = NULL;
	gchar* _tmp2_;
	_tmp0_ = unity_applications_lens_software_center_utils_mangled_desktop_file_lookup_new ();
	lookup = _tmp0_;
	_tmp1_ = g_strdup ("/foo/bar/evince.desktop");
	desktop_file = _tmp1_;
	_tmp2_ = unity_applications_lens_software_center_utils_mangled_desktop_file_lookup_extract_desktop_id (lookup, desktop_file, FALSE);
	_result_ = _tmp2_;
	_vala_assert (g_strcmp0 (_result_, "evince.desktop") == 0, "result == \"evince.desktop\"");
	_vala_assert (unity_applications_lens_software_center_utils_mangled_desktop_file_lookup_contains (lookup, _result_) == FALSE, "lookup.contains (result) == false");
	_g_free0 (_result_);
	_g_free0 (desktop_file);
	_unity_applications_lens_software_center_utils_mangled_desktop_file_lookup_unref0 (lookup);
}

