/* running-apps-search.c generated by valac 0.56.19, the Vala compiler
 * generated from running-apps-search.vala, do not modify */

/* -*- mode: vala; c-basic-offset: 2; indent-tabs-mode: nil -*- */
/*
 * Copyright (C) 2013 Canonical Ltd
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Authored by Pawel Stolowski <pawel.stolowski@canonical.com>
 *
 */

#include <unity.h>
#include <glib-object.h>
#include <dee-icu.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>
#include <gio/gio.h>
#include <gio/gdesktopappinfo.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define UNITY_APPLICATIONS_LENS_TYPE_RUNNING_APPS_SEARCH (unity_applications_lens_running_apps_search_get_type ())
#define UNITY_APPLICATIONS_LENS_RUNNING_APPS_SEARCH(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), UNITY_APPLICATIONS_LENS_TYPE_RUNNING_APPS_SEARCH, UnityApplicationsLensRunningAppsSearch))
#define UNITY_APPLICATIONS_LENS_RUNNING_APPS_SEARCH_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), UNITY_APPLICATIONS_LENS_TYPE_RUNNING_APPS_SEARCH, UnityApplicationsLensRunningAppsSearchClass))
#define UNITY_APPLICATIONS_LENS_IS_RUNNING_APPS_SEARCH(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), UNITY_APPLICATIONS_LENS_TYPE_RUNNING_APPS_SEARCH))
#define UNITY_APPLICATIONS_LENS_IS_RUNNING_APPS_SEARCH_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), UNITY_APPLICATIONS_LENS_TYPE_RUNNING_APPS_SEARCH))
#define UNITY_APPLICATIONS_LENS_RUNNING_APPS_SEARCH_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), UNITY_APPLICATIONS_LENS_TYPE_RUNNING_APPS_SEARCH, UnityApplicationsLensRunningAppsSearchClass))

typedef struct _UnityApplicationsLensRunningAppsSearch UnityApplicationsLensRunningAppsSearch;
typedef struct _UnityApplicationsLensRunningAppsSearchClass UnityApplicationsLensRunningAppsSearchClass;
typedef struct _UnityApplicationsLensRunningAppsSearchPrivate UnityApplicationsLensRunningAppsSearchPrivate;

#define UNITY_APPLICATIONS_LENS_TYPE_WIN_STACK (unity_applications_lens_win_stack_get_type ())
#define UNITY_APPLICATIONS_LENS_WIN_STACK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), UNITY_APPLICATIONS_LENS_TYPE_WIN_STACK, UnityApplicationsLensWinStack))
#define UNITY_APPLICATIONS_LENS_WIN_STACK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), UNITY_APPLICATIONS_LENS_TYPE_WIN_STACK, UnityApplicationsLensWinStackClass))
#define UNITY_APPLICATIONS_LENS_IS_WIN_STACK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), UNITY_APPLICATIONS_LENS_TYPE_WIN_STACK))
#define UNITY_APPLICATIONS_LENS_IS_WIN_STACK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), UNITY_APPLICATIONS_LENS_TYPE_WIN_STACK))
#define UNITY_APPLICATIONS_LENS_WIN_STACK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), UNITY_APPLICATIONS_LENS_TYPE_WIN_STACK, UnityApplicationsLensWinStackClass))

typedef struct _UnityApplicationsLensWinStack UnityApplicationsLensWinStack;
typedef struct _UnityApplicationsLensWinStackClass UnityApplicationsLensWinStackClass;

#define UNITY_APPLICATIONS_LENS_TYPE_CATEGORY_LIST (unity_applications_lens_category_list_get_type ())
typedef struct _UnityApplicationsLensCategoryList UnityApplicationsLensCategoryList;
enum  {
	UNITY_APPLICATIONS_LENS_RUNNING_APPS_SEARCH_0_PROPERTY,
	UNITY_APPLICATIONS_LENS_RUNNING_APPS_SEARCH_NUM_PROPERTIES
};
static GParamSpec* unity_applications_lens_running_apps_search_properties[UNITY_APPLICATIONS_LENS_RUNNING_APPS_SEARCH_NUM_PROPERTIES];
#define _g_hash_table_unref0(var) ((var == NULL) ? NULL : (var = (g_hash_table_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define UNITY_APPLICATIONS_LENS_WIN_STACK_TYPE_WINDOW (unity_applications_lens_win_stack_window_get_type ())
typedef struct _UnityApplicationsLensWinStackWindow UnityApplicationsLensWinStackWindow;
#define _unity_applications_lens_win_stack_window_free0(var) ((var == NULL) ? NULL : (var = (unity_applications_lens_win_stack_window_free (var), NULL)))

struct _UnityApplicationsLensRunningAppsSearch {
	UnityScopeSearchBase parent_instance;
	UnityApplicationsLensRunningAppsSearchPrivate * priv;
};

struct _UnityApplicationsLensRunningAppsSearchClass {
	UnityScopeSearchBaseClass parent_class;
};

struct _UnityApplicationsLensCategoryList {
	GeeSet* categories;
	GeeSet* exclude_categories;
};

struct _UnityApplicationsLensRunningAppsSearchPrivate {
	UnityApplicationsLensWinStack* windows;
	DeeICUTermFilter* icu;
	GHashTable* category_map;
};

struct _UnityApplicationsLensWinStackWindow {
	guint window_id;
	gchar* app_id;
};

static gint UnityApplicationsLensRunningAppsSearch_private_offset;
static gpointer unity_applications_lens_running_apps_search_parent_class = NULL;

VALA_EXTERN GType unity_applications_lens_running_apps_search_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (UnityApplicationsLensRunningAppsSearch, g_object_unref)
VALA_EXTERN gpointer unity_applications_lens_win_stack_ref (gpointer instance);
VALA_EXTERN void unity_applications_lens_win_stack_unref (gpointer instance);
VALA_EXTERN GParamSpec* unity_applications_lens_param_spec_win_stack (const gchar* name,
                                                          const gchar* nick,
                                                          const gchar* blurb,
                                                          GType object_type,
                                                          GParamFlags flags);
VALA_EXTERN void unity_applications_lens_value_set_win_stack (GValue* value,
                                                  gpointer v_object);
VALA_EXTERN void unity_applications_lens_value_take_win_stack (GValue* value,
                                                   gpointer v_object);
VALA_EXTERN gpointer unity_applications_lens_value_get_win_stack (const GValue* value);
VALA_EXTERN GType unity_applications_lens_win_stack_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (UnityApplicationsLensWinStack, unity_applications_lens_win_stack_unref)
VALA_EXTERN GType unity_applications_lens_category_list_get_type (void) G_GNUC_CONST ;
VALA_EXTERN UnityApplicationsLensCategoryList* unity_applications_lens_category_list_dup (const UnityApplicationsLensCategoryList* self);
VALA_EXTERN void unity_applications_lens_category_list_free (UnityApplicationsLensCategoryList* self);
VALA_EXTERN void unity_applications_lens_category_list_copy (const UnityApplicationsLensCategoryList* self,
                                                 UnityApplicationsLensCategoryList* dest);
VALA_EXTERN void unity_applications_lens_category_list_destroy (UnityApplicationsLensCategoryList* self);
G_DEFINE_AUTO_CLEANUP_CLEAR_FUNC (UnityApplicationsLensCategoryList, unity_applications_lens_category_list_destroy)
VALA_EXTERN UnityApplicationsLensRunningAppsSearch* unity_applications_lens_running_apps_search_new (UnityApplicationsLensWinStack* windows,
                                                                                         DeeICUTermFilter* icu,
                                                                                         GHashTable* category_map);
VALA_EXTERN UnityApplicationsLensRunningAppsSearch* unity_applications_lens_running_apps_search_construct (GType object_type,
                                                                                               UnityApplicationsLensWinStack* windows,
                                                                                               DeeICUTermFilter* icu,
                                                                                               GHashTable* category_map);
static gboolean unity_applications_lens_running_apps_search_category_matches (UnityApplicationsLensRunningAppsSearch* self,
                                                                       gchar** desktop_file_categories,
                                                                       gint desktop_file_categories_length1,
                                                                       GeeSet* selected_categories);
static gboolean _vala_string_array_contains (gchar* * stack,
                                      gssize stack_length,
                                      const gchar* needle);
static GeeSet* unity_applications_lens_running_apps_search_get_selected_categories (UnityApplicationsLensRunningAppsSearch* self,
                                                                             UnityOptionsFilter* filter);
static void unity_applications_lens_running_apps_search_real_run_async (UnityScopeSearchBase* base,
                                                                 UnityScopeSearchBaseCallback async_callback,
                                                                 gpointer async_callback_target);
static void unity_applications_lens_running_apps_search_real_run (UnityScopeSearchBase* base);
VALA_EXTERN GType unity_applications_lens_win_stack_window_get_type (void) G_GNUC_CONST ;
VALA_EXTERN UnityApplicationsLensWinStackWindow* unity_applications_lens_win_stack_window_dup (const UnityApplicationsLensWinStackWindow* self);
VALA_EXTERN void unity_applications_lens_win_stack_window_free (UnityApplicationsLensWinStackWindow* self);
VALA_EXTERN void unity_applications_lens_win_stack_window_copy (const UnityApplicationsLensWinStackWindow* self,
                                                    UnityApplicationsLensWinStackWindow* dest);
VALA_EXTERN void unity_applications_lens_win_stack_window_destroy (UnityApplicationsLensWinStackWindow* self);
G_DEFINE_AUTO_CLEANUP_CLEAR_FUNC (UnityApplicationsLensWinStackWindow, unity_applications_lens_win_stack_window_destroy)
VALA_EXTERN GeeIterator* unity_applications_lens_win_stack_iterator (UnityApplicationsLensWinStack* self);
static void _g_free0_ (gpointer var);
static void _g_variant_unref0_ (gpointer var);
static void unity_applications_lens_running_apps_search_finalize (GObject * obj);
static GType unity_applications_lens_running_apps_search_get_type_once (void);
static void _vala_array_destroy (gpointer array,
                          gssize array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gssize array_length,
                       GDestroyNotify destroy_func);
static gssize _vala_array_length (gpointer array);

static inline gpointer
unity_applications_lens_running_apps_search_get_instance_private (UnityApplicationsLensRunningAppsSearch* self)
{
	return G_STRUCT_MEMBER_P (self, UnityApplicationsLensRunningAppsSearch_private_offset);
}

static gpointer
_g_hash_table_ref0 (gpointer self)
{
	return self ? g_hash_table_ref (self) : NULL;
}

UnityApplicationsLensRunningAppsSearch*
unity_applications_lens_running_apps_search_construct (GType object_type,
                                                       UnityApplicationsLensWinStack* windows,
                                                       DeeICUTermFilter* icu,
                                                       GHashTable* category_map)
{
	UnityApplicationsLensRunningAppsSearch * self = NULL;
	GHashTable* _tmp0_;
	g_return_val_if_fail (windows != NULL, NULL);
	g_return_val_if_fail (icu != NULL, NULL);
	g_return_val_if_fail (category_map != NULL, NULL);
	self = (UnityApplicationsLensRunningAppsSearch*) unity_scope_search_base_construct (object_type);
	self->priv->windows = windows;
	self->priv->icu = icu;
	_tmp0_ = _g_hash_table_ref0 (category_map);
	_g_hash_table_unref0 (self->priv->category_map);
	self->priv->category_map = _tmp0_;
	return self;
}

UnityApplicationsLensRunningAppsSearch*
unity_applications_lens_running_apps_search_new (UnityApplicationsLensWinStack* windows,
                                                 DeeICUTermFilter* icu,
                                                 GHashTable* category_map)
{
	return unity_applications_lens_running_apps_search_construct (UNITY_APPLICATIONS_LENS_TYPE_RUNNING_APPS_SEARCH, windows, icu, category_map);
}

static gboolean
_vala_string_array_contains (gchar* * stack,
                             gssize stack_length,
                             const gchar* needle)
{
	gssize i;
	for (i = 0; i < stack_length; i++) {
		if (g_strcmp0 (stack[i], needle) == 0) {
			return TRUE;
		}
	}
	return FALSE;
}

static gboolean
unity_applications_lens_running_apps_search_category_matches (UnityApplicationsLensRunningAppsSearch* self,
                                                              gchar** desktop_file_categories,
                                                              gint desktop_file_categories_length1,
                                                              GeeSet* selected_categories)
{
	gboolean matches = FALSE;
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (selected_categories != NULL, FALSE);
	matches = FALSE;
	{
		GeeIterator* _sel_it = NULL;
		GeeIterator* _tmp0_;
		_tmp0_ = gee_iterable_iterator ((GeeIterable*) selected_categories);
		_sel_it = _tmp0_;
		while (TRUE) {
			GeeIterator* _tmp1_;
			gchar* sel = NULL;
			GeeIterator* _tmp2_;
			gpointer _tmp3_;
			UnityApplicationsLensCategoryList* cm = NULL;
			GHashTable* _tmp4_;
			const gchar* _tmp5_;
			gconstpointer _tmp6_;
			UnityApplicationsLensCategoryList* _tmp7_;
			_tmp1_ = _sel_it;
			if (!gee_iterator_next (_tmp1_)) {
				break;
			}
			_tmp2_ = _sel_it;
			_tmp3_ = gee_iterator_get (_tmp2_);
			sel = (gchar*) _tmp3_;
			_tmp4_ = self->priv->category_map;
			_tmp5_ = sel;
			_tmp6_ = g_hash_table_lookup (_tmp4_, _tmp5_);
			cm = (UnityApplicationsLensCategoryList*) _tmp6_;
			_tmp7_ = cm;
			if (_tmp7_ == NULL) {
				result = FALSE;
				_g_free0 (sel);
				_g_object_unref0 (_sel_it);
				return result;
			}
			{
				GeeIterator* _cat_it = NULL;
				UnityApplicationsLensCategoryList* _tmp8_;
				GeeSet* _tmp9_;
				GeeIterator* _tmp10_;
				_tmp8_ = cm;
				_tmp9_ = (*_tmp8_).categories;
				_tmp10_ = gee_iterable_iterator ((GeeIterable*) _tmp9_);
				_cat_it = _tmp10_;
				while (TRUE) {
					GeeIterator* _tmp11_;
					gchar* cat = NULL;
					GeeIterator* _tmp12_;
					gpointer _tmp13_;
					const gchar* _tmp14_;
					_tmp11_ = _cat_it;
					if (!gee_iterator_next (_tmp11_)) {
						break;
					}
					_tmp12_ = _cat_it;
					_tmp13_ = gee_iterator_get (_tmp12_);
					cat = (gchar*) _tmp13_;
					_tmp14_ = cat;
					if (_vala_string_array_contains (desktop_file_categories, desktop_file_categories_length1, _tmp14_)) {
						matches = TRUE;
						_g_free0 (cat);
						break;
					}
					_g_free0 (cat);
				}
				_g_object_unref0 (_cat_it);
			}
			if (matches == FALSE) {
				result = FALSE;
				_g_free0 (sel);
				_g_object_unref0 (_sel_it);
				return result;
			}
			{
				GeeIterator* _cat_it = NULL;
				UnityApplicationsLensCategoryList* _tmp15_;
				GeeSet* _tmp16_;
				GeeIterator* _tmp17_;
				_tmp15_ = cm;
				_tmp16_ = (*_tmp15_).exclude_categories;
				_tmp17_ = gee_iterable_iterator ((GeeIterable*) _tmp16_);
				_cat_it = _tmp17_;
				while (TRUE) {
					GeeIterator* _tmp18_;
					gchar* cat = NULL;
					GeeIterator* _tmp19_;
					gpointer _tmp20_;
					const gchar* _tmp21_;
					_tmp18_ = _cat_it;
					if (!gee_iterator_next (_tmp18_)) {
						break;
					}
					_tmp19_ = _cat_it;
					_tmp20_ = gee_iterator_get (_tmp19_);
					cat = (gchar*) _tmp20_;
					_tmp21_ = cat;
					if (_vala_string_array_contains (desktop_file_categories, desktop_file_categories_length1, _tmp21_)) {
						matches = FALSE;
						_g_free0 (cat);
						break;
					}
					_g_free0 (cat);
				}
				_g_object_unref0 (_cat_it);
			}
			_g_free0 (sel);
		}
		_g_object_unref0 (_sel_it);
	}
	result = matches;
	return result;
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

static GeeSet*
unity_applications_lens_running_apps_search_get_selected_categories (UnityApplicationsLensRunningAppsSearch* self,
                                                                     UnityOptionsFilter* filter)
{
	GeeHashSet* cats = NULL;
	GeeHashSet* _tmp0_;
	GList* _tmp1_;
	GeeSet* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (filter != NULL, NULL);
	_tmp0_ = gee_hash_set_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, NULL, NULL, NULL, NULL, NULL, NULL);
	cats = _tmp0_;
	_tmp1_ = filter->options;
	{
		GList* opt_collection = NULL;
		GList* opt_it = NULL;
		opt_collection = _tmp1_;
		for (opt_it = opt_collection; opt_it != NULL; opt_it = opt_it->next) {
			UnityFilterOption* _tmp2_;
			UnityFilterOption* opt = NULL;
			_tmp2_ = _g_object_ref0 ((UnityFilterOption*) opt_it->data);
			opt = _tmp2_;
			{
				UnityFilterOption* _tmp3_;
				gboolean _tmp4_;
				gboolean _tmp5_;
				_tmp3_ = opt;
				_tmp4_ = unity_filter_option_get_active (_tmp3_);
				_tmp5_ = _tmp4_;
				if (_tmp5_) {
					GeeHashSet* _tmp6_;
					UnityFilterOption* _tmp7_;
					const gchar* _tmp8_;
					const gchar* _tmp9_;
					_tmp6_ = cats;
					_tmp7_ = opt;
					_tmp8_ = unity_filter_option_get_id (_tmp7_);
					_tmp9_ = _tmp8_;
					gee_abstract_collection_add ((GeeAbstractCollection*) _tmp6_, _tmp9_);
				}
				_g_object_unref0 (opt);
			}
		}
	}
	result = (GeeSet*) cats;
	return result;
}

static void
unity_applications_lens_running_apps_search_real_run_async (UnityScopeSearchBase* base,
                                                            UnityScopeSearchBaseCallback async_callback,
                                                            gpointer async_callback_target)
{
	UnityApplicationsLensRunningAppsSearch * self;
	self = (UnityApplicationsLensRunningAppsSearch*) base;
	unity_scope_search_base_run ((UnityScopeSearchBase*) self);
	async_callback ((UnityScopeSearchBase*) self, async_callback_target);
}

static gchar*
string_strip (const gchar* self)
{
	gchar* _result_ = NULL;
	gchar* _tmp0_;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_strdup (self);
	_result_ = _tmp0_;
	g_strstrip (_result_);
	result = _result_;
	return result;
}

static gboolean
string_contains (const gchar* self,
                 const gchar* needle)
{
	gchar* _tmp0_;
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (needle != NULL, FALSE);
	_tmp0_ = strstr ((gchar*) self, (gchar*) needle);
	result = _tmp0_ != NULL;
	return result;
}

static void
_g_free0_ (gpointer var)
{
	var = (g_free (var), NULL);
}

static void
_g_variant_unref0_ (gpointer var)
{
	(var == NULL) ? NULL : (var = (g_variant_unref (var), NULL));
}

static void
unity_applications_lens_running_apps_search_real_run (UnityScopeSearchBase* base)
{
	UnityApplicationsLensRunningAppsSearch * self;
	UnitySearchContext* _tmp0_;
	gchar* query = NULL;
	DeeICUTermFilter* _tmp1_;
	UnitySearchContext* _tmp2_;
	const gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	UnityOptionsFilter* type_filter = NULL;
	UnitySearchContext* _tmp8_;
	UnityFilterSet* _tmp9_;
	UnityFilter* _tmp10_;
	UnityOptionsFilter* _tmp11_;
	gboolean _tmp12_ = FALSE;
	UnityOptionsFilter* _tmp13_;
	gboolean has_filter = FALSE;
	GeeSet* _tmp17_ = NULL;
	GeeSet* selected_categories = NULL;
	GeeSet* _tmp20_;
	UnityAppInfoManager* appmanager = NULL;
	UnityAppInfoManager* _tmp21_;
	GeeIterator* it = NULL;
	UnityApplicationsLensWinStack* _tmp22_;
	GeeIterator* _tmp23_;
	GError* _inner_error0_ = NULL;
	self = (UnityApplicationsLensRunningAppsSearch*) base;
	_tmp0_ = ((UnityScopeSearchBase*) self)->search_context;
	if ((*_tmp0_).search_type == UNITY_SEARCH_TYPE_GLOBAL) {
		return;
	}
	_tmp1_ = self->priv->icu;
	_tmp2_ = ((UnityScopeSearchBase*) self)->search_context;
	_tmp3_ = (*_tmp2_).search_query;
	_tmp4_ = g_utf8_strdown (_tmp3_, (gssize) -1);
	_tmp5_ = _tmp4_;
	_tmp6_ = dee_icu_term_filter_apply (_tmp1_, _tmp5_);
	_tmp7_ = _tmp6_;
	_g_free0 (_tmp5_);
	query = _tmp7_;
	_tmp8_ = ((UnityScopeSearchBase*) self)->search_context;
	_tmp9_ = (*_tmp8_).filter_state;
	_tmp10_ = unity_filter_set_get_filter_by_id (_tmp9_, "type");
	_tmp11_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp10_, UNITY_TYPE_OPTIONS_FILTER) ? ((UnityOptionsFilter*) _tmp10_) : NULL);
	type_filter = _tmp11_;
	_tmp13_ = type_filter;
	if (_tmp13_ != NULL) {
		UnityOptionsFilter* _tmp14_;
		gboolean _tmp15_;
		gboolean _tmp16_;
		_tmp14_ = type_filter;
		_tmp15_ = unity_filter_get_filtering ((UnityFilter*) _tmp14_);
		_tmp16_ = _tmp15_;
		_tmp12_ = _tmp16_;
	} else {
		_tmp12_ = FALSE;
	}
	has_filter = _tmp12_;
	if (has_filter) {
		UnityOptionsFilter* _tmp18_;
		GeeSet* _tmp19_;
		_tmp18_ = type_filter;
		_tmp19_ = unity_applications_lens_running_apps_search_get_selected_categories (self, _tmp18_);
		_g_object_unref0 (_tmp17_);
		_tmp17_ = _tmp19_;
	} else {
		_g_object_unref0 (_tmp17_);
		_tmp17_ = NULL;
	}
	_tmp20_ = _tmp17_;
	_tmp17_ = NULL;
	selected_categories = _tmp20_;
	_tmp21_ = unity_app_info_manager_get_default ();
	appmanager = _tmp21_;
	_tmp22_ = self->priv->windows;
	_tmp23_ = unity_applications_lens_win_stack_iterator (_tmp22_);
	it = _tmp23_;
	while (TRUE) {
		GeeIterator* _tmp24_;
		UnityApplicationsLensWinStackWindow* win = NULL;
		GeeIterator* _tmp25_;
		gpointer _tmp26_;
		UnityApplicationsLensWinStackWindow* _tmp27_;
		const gchar* _tmp28_;
		_tmp24_ = it;
		if (!gee_iterator_next (_tmp24_)) {
			break;
		}
		_tmp25_ = it;
		_tmp26_ = gee_iterator_get (_tmp25_);
		win = (UnityApplicationsLensWinStackWindow*) _tmp26_;
		_tmp27_ = win;
		_tmp28_ = (*_tmp27_).app_id;
		g_debug ("running-apps-search.vala:111: Window: %s", _tmp28_);
		{
			gboolean matches = FALSE;
			gchar* app_id = NULL;
			UnityApplicationsLensWinStackWindow* _tmp29_;
			const gchar* _tmp30_;
			gchar* _tmp31_;
			const gchar* _tmp32_;
			GAppInfo* app_info = NULL;
			UnityAppInfoManager* _tmp35_;
			const gchar* _tmp36_;
			GAppInfo* _tmp37_;
			gboolean _tmp38_ = FALSE;
			GAppInfo* _tmp39_;
			GDesktopAppInfo* desktop_file = NULL;
			GAppInfo* _tmp42_;
			GDesktopAppInfo* _tmp43_;
			gboolean _tmp44_ = FALSE;
			GeeSet* _tmp45_;
			UnitySearchContext* _tmp52_;
			const gchar* _tmp53_;
			gchar* _tmp54_;
			gchar* _tmp55_;
			gboolean _tmp56_;
			matches = FALSE;
			_tmp29_ = win;
			_tmp30_ = (*_tmp29_).app_id;
			_tmp31_ = g_strdup (_tmp30_);
			app_id = _tmp31_;
			_tmp32_ = app_id;
			if (!g_str_has_suffix (_tmp32_, ".desktop")) {
				const gchar* _tmp33_;
				gchar* _tmp34_;
				_tmp33_ = app_id;
				_tmp34_ = g_strconcat (_tmp33_, ".desktop", NULL);
				_g_free0 (app_id);
				app_id = _tmp34_;
			}
			_tmp35_ = appmanager;
			_tmp36_ = app_id;
			_tmp37_ = unity_app_info_manager_lookup (_tmp35_, _tmp36_);
			app_info = _tmp37_;
			_tmp39_ = app_info;
			if (_tmp39_ == NULL) {
				_tmp38_ = TRUE;
			} else {
				GAppInfo* _tmp40_;
				_tmp40_ = app_info;
				_tmp38_ = !G_TYPE_CHECK_INSTANCE_TYPE (_tmp40_, G_TYPE_DESKTOP_APP_INFO);
			}
			if (_tmp38_) {
				const gchar* _tmp41_;
				_tmp41_ = app_id;
				g_warning ("running-apps-search.vala:123: No desktop file for %s", _tmp41_);
				_g_object_unref0 (app_info);
				_g_free0 (app_id);
				_unity_applications_lens_win_stack_window_free0 (win);
				continue;
			}
			_tmp42_ = app_info;
			_tmp43_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp42_, G_TYPE_DESKTOP_APP_INFO) ? ((GDesktopAppInfo*) _tmp42_) : NULL);
			desktop_file = _tmp43_;
			_tmp45_ = selected_categories;
			if (_tmp45_ != NULL) {
				GDesktopAppInfo* _tmp46_;
				const gchar* _tmp47_;
				gchar** _tmp48_;
				gchar** _tmp49_;
				gchar** _tmp50_;
				gint _tmp50__length1;
				GeeSet* _tmp51_;
				_tmp46_ = desktop_file;
				_tmp47_ = g_desktop_app_info_get_categories (_tmp46_);
				_tmp49_ = _tmp48_ = g_strsplit (_tmp47_, ";", 0);
				_tmp50_ = _tmp49_;
				_tmp50__length1 = _vala_array_length (_tmp48_);
				_tmp51_ = selected_categories;
				_tmp44_ = !unity_applications_lens_running_apps_search_category_matches (self, _tmp50_, (gint) _vala_array_length (_tmp48_), _tmp51_);
				_tmp50_ = (_vala_array_free (_tmp50_, _tmp50__length1, (GDestroyNotify) g_free), NULL);
			} else {
				_tmp44_ = FALSE;
			}
			if (_tmp44_) {
				_g_object_unref0 (desktop_file);
				_g_object_unref0 (app_info);
				_g_free0 (app_id);
				_unity_applications_lens_win_stack_window_free0 (win);
				continue;
			}
			_tmp52_ = ((UnityScopeSearchBase*) self)->search_context;
			_tmp53_ = (*_tmp52_).search_query;
			_tmp54_ = string_strip (_tmp53_);
			_tmp55_ = _tmp54_;
			_tmp56_ = g_strcmp0 (_tmp55_, "") == 0;
			_g_free0 (_tmp55_);
			if (_tmp56_) {
				matches = TRUE;
			} else {
				gchar* display_name = NULL;
				DeeICUTermFilter* _tmp57_;
				GDesktopAppInfo* _tmp58_;
				const gchar* _tmp59_;
				gchar* _tmp60_;
				gchar* _tmp61_;
				gchar* _tmp62_;
				gchar* _tmp63_;
				const gchar* _tmp64_;
				const gchar* _tmp65_;
				_tmp57_ = self->priv->icu;
				_tmp58_ = desktop_file;
				_tmp59_ = g_app_info_get_display_name ((GAppInfo*) _tmp58_);
				_tmp60_ = g_utf8_strdown (_tmp59_, (gssize) -1);
				_tmp61_ = _tmp60_;
				_tmp62_ = dee_icu_term_filter_apply (_tmp57_, _tmp61_);
				_tmp63_ = _tmp62_;
				_g_free0 (_tmp61_);
				display_name = _tmp63_;
				_tmp64_ = display_name;
				_tmp65_ = query;
				if (string_contains (_tmp64_, _tmp65_)) {
					matches = TRUE;
				} else {
					gchar* descr = NULL;
					DeeICUTermFilter* _tmp66_;
					GDesktopAppInfo* _tmp67_;
					const gchar* _tmp68_;
					gchar* _tmp69_;
					gchar* _tmp70_;
					gchar* _tmp71_;
					gchar* _tmp72_;
					const gchar* _tmp73_;
					const gchar* _tmp74_;
					_tmp66_ = self->priv->icu;
					_tmp67_ = desktop_file;
					_tmp68_ = g_app_info_get_description ((GAppInfo*) _tmp67_);
					_tmp69_ = g_utf8_strdown (_tmp68_, (gssize) -1);
					_tmp70_ = _tmp69_;
					_tmp71_ = dee_icu_term_filter_apply (_tmp66_, _tmp70_);
					_tmp72_ = _tmp71_;
					_g_free0 (_tmp70_);
					descr = _tmp72_;
					_tmp73_ = descr;
					_tmp74_ = query;
					if (string_contains (_tmp73_, _tmp74_)) {
						matches = TRUE;
					} else {
						gchar* exec_name = NULL;
						DeeICUTermFilter* _tmp75_;
						GDesktopAppInfo* _tmp76_;
						const gchar* _tmp77_;
						gchar* _tmp78_;
						gchar* _tmp79_;
						gchar* _tmp80_;
						gchar* _tmp81_;
						const gchar* _tmp82_;
						const gchar* _tmp83_;
						_tmp75_ = self->priv->icu;
						_tmp76_ = desktop_file;
						_tmp77_ = g_app_info_get_executable ((GAppInfo*) _tmp76_);
						_tmp78_ = g_utf8_strdown (_tmp77_, (gssize) -1);
						_tmp79_ = _tmp78_;
						_tmp80_ = dee_icu_term_filter_apply (_tmp75_, _tmp79_);
						_tmp81_ = _tmp80_;
						_g_free0 (_tmp79_);
						exec_name = _tmp81_;
						_tmp82_ = exec_name;
						_tmp83_ = query;
						if (string_contains (_tmp82_, _tmp83_)) {
							matches = TRUE;
						}
						_g_free0 (exec_name);
					}
					_g_free0 (descr);
				}
				_g_free0 (display_name);
			}
			if (matches) {
				UnityScopeResult _result_ = {0};
				UnityApplicationsLensWinStackWindow* _tmp84_;
				const gchar* _tmp85_;
				gchar* _tmp86_;
				UnityApplicationsLensWinStackWindow* _tmp87_;
				const gchar* _tmp88_;
				gchar* _tmp89_;
				gchar* _tmp90_;
				GDesktopAppInfo* _tmp91_;
				const gchar* _tmp92_;
				gchar* _tmp93_;
				gchar* _tmp94_;
				UnityScopeResult _tmp95_;
				const gchar* _tmp96_;
				gchar* _tmp97_;
				GHashFunc _tmp98_;
				GEqualFunc _tmp99_;
				GHashTable* _tmp100_;
				UnitySearchContext* _tmp101_;
				UnityResultSet* _tmp102_;
				UnityScopeResult _tmp103_;
				memset (&_result_, 0, sizeof (UnityScopeResult));
				_tmp84_ = win;
				_tmp85_ = (*_tmp84_).app_id;
				_tmp86_ = g_strconcat ("application://", _tmp85_, NULL);
				_g_free0 (_result_.uri);
				_result_.uri = _tmp86_;
				_tmp87_ = win;
				_tmp88_ = (*_tmp87_).app_id;
				_tmp89_ = g_strconcat ("image://screenshot/", _tmp88_, NULL);
				_g_free0 (_result_.icon_hint);
				_result_.icon_hint = _tmp89_;
				_result_.category = (guint) 0;
				_result_.result_type = UNITY_RESULT_TYPE_PERSONAL;
				_tmp90_ = g_strdup ("application/x-desktop");
				_g_free0 (_result_.mimetype);
				_result_.mimetype = _tmp90_;
				_tmp91_ = desktop_file;
				_tmp92_ = g_app_info_get_display_name ((GAppInfo*) _tmp91_);
				_tmp93_ = g_strdup (_tmp92_);
				_g_free0 (_result_.title);
				_result_.title = _tmp93_;
				_tmp94_ = g_strdup ("");
				_g_free0 (_result_.comment);
				_result_.comment = _tmp94_;
				_tmp95_ = _result_;
				_tmp96_ = _tmp95_.uri;
				_tmp97_ = g_strdup (_tmp96_);
				_g_free0 (_result_.dnd_uri);
				_result_.dnd_uri = _tmp97_;
				_tmp98_ = g_str_hash;
				_tmp99_ = g_str_equal;
				_tmp100_ = g_hash_table_new_full (_tmp98_, _tmp99_, _g_free0_, _g_variant_unref0_);
				_g_hash_table_unref0 (_result_.metadata);
				_result_.metadata = _tmp100_;
				_tmp101_ = ((UnityScopeSearchBase*) self)->search_context;
				_tmp102_ = (*_tmp101_).result_set;
				_tmp103_ = _result_;
				unity_result_set_add_result (_tmp102_, &_tmp103_);
				unity_scope_result_destroy (&_result_);
			}
			_g_object_unref0 (desktop_file);
			_g_object_unref0 (app_info);
			_g_free0 (app_id);
		}
		goto __finally0;
		__catch0_g_error:
		{
			UnityApplicationsLensWinStackWindow* _tmp104_;
			const gchar* _tmp105_;
			g_clear_error (&_inner_error0_);
			_tmp104_ = win;
			_tmp105_ = (*_tmp104_).app_id;
			g_warning ("running-apps-search.vala:176: Error loading desktop file: %s", _tmp105_);
		}
		__finally0:
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_unity_applications_lens_win_stack_window_free0 (win);
			_g_object_unref0 (it);
			_g_object_unref0 (appmanager);
			_g_object_unref0 (selected_categories);
			_g_object_unref0 (_tmp17_);
			_g_object_unref0 (type_filter);
			_g_free0 (query);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return;
		}
		_unity_applications_lens_win_stack_window_free0 (win);
	}
	_g_object_unref0 (it);
	_g_object_unref0 (appmanager);
	_g_object_unref0 (selected_categories);
	_g_object_unref0 (_tmp17_);
	_g_object_unref0 (type_filter);
	_g_free0 (query);
}

static void
unity_applications_lens_running_apps_search_class_init (UnityApplicationsLensRunningAppsSearchClass * klass,
                                                        gpointer klass_data)
{
	unity_applications_lens_running_apps_search_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &UnityApplicationsLensRunningAppsSearch_private_offset);
	((UnityScopeSearchBaseClass *) klass)->run_async = (void (*) (UnityScopeSearchBase*, UnityScopeSearchBaseCallback, gpointer)) unity_applications_lens_running_apps_search_real_run_async;
	((UnityScopeSearchBaseClass *) klass)->run = (void (*) (UnityScopeSearchBase*)) unity_applications_lens_running_apps_search_real_run;
	G_OBJECT_CLASS (klass)->finalize = unity_applications_lens_running_apps_search_finalize;
}

static void
unity_applications_lens_running_apps_search_instance_init (UnityApplicationsLensRunningAppsSearch * self,
                                                           gpointer klass)
{
	self->priv = unity_applications_lens_running_apps_search_get_instance_private (self);
}

static void
unity_applications_lens_running_apps_search_finalize (GObject * obj)
{
	UnityApplicationsLensRunningAppsSearch * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, UNITY_APPLICATIONS_LENS_TYPE_RUNNING_APPS_SEARCH, UnityApplicationsLensRunningAppsSearch);
	_g_hash_table_unref0 (self->priv->category_map);
	G_OBJECT_CLASS (unity_applications_lens_running_apps_search_parent_class)->finalize (obj);
}

static GType
unity_applications_lens_running_apps_search_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (UnityApplicationsLensRunningAppsSearchClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) unity_applications_lens_running_apps_search_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (UnityApplicationsLensRunningAppsSearch), 0, (GInstanceInitFunc) unity_applications_lens_running_apps_search_instance_init, NULL };
	GType unity_applications_lens_running_apps_search_type_id;
	unity_applications_lens_running_apps_search_type_id = g_type_register_static (UNITY_TYPE_SCOPE_SEARCH_BASE, "UnityApplicationsLensRunningAppsSearch", &g_define_type_info, 0);
	UnityApplicationsLensRunningAppsSearch_private_offset = g_type_add_instance_private (unity_applications_lens_running_apps_search_type_id, sizeof (UnityApplicationsLensRunningAppsSearchPrivate));
	return unity_applications_lens_running_apps_search_type_id;
}

GType
unity_applications_lens_running_apps_search_get_type (void)
{
	static volatile gsize unity_applications_lens_running_apps_search_type_id__once = 0;
	if (g_once_init_enter (&unity_applications_lens_running_apps_search_type_id__once)) {
		GType unity_applications_lens_running_apps_search_type_id;
		unity_applications_lens_running_apps_search_type_id = unity_applications_lens_running_apps_search_get_type_once ();
		g_once_init_leave (&unity_applications_lens_running_apps_search_type_id__once, unity_applications_lens_running_apps_search_type_id);
	}
	return unity_applications_lens_running_apps_search_type_id__once;
}

static void
_vala_array_destroy (gpointer array,
                     gssize array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gssize i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gssize array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

static gssize
_vala_array_length (gpointer array)
{
	gssize length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}

