const char * _application_menu_renderer = 
"<?xml version=\"1.0\"?>\n"
"<node name=\"/com/canonical/AppMenu/Renderer\">\n"
"	\n"
"	<interface name=\"com.canonical.AppMenu.Renderer\">\n"
"		\n"
"		<method name=\"GetCurrentMenu\">\n"
"			\n"
"			<arg name=\"service\" type=\"s\" direction=\"out\">\n"
"				\n"
"			</arg>\n"
"			<arg name=\"menuObjectPath\" type=\"o\" direction=\"out\">\n"
"				\n"
"			</arg>\n"
"		</method>\n"
"		<method name=\"ActivateMenuItem\">\n"
"			\n"
"			<annotation name=\"com.trolltech.QtDBus.QtTypeName.In0\" value=\"QList&lt;int&gt;\"/>\n"
"			<arg name=\"menuItemPath\" type=\"ai\" direction=\"in\">\n"
"				\n"
"			</arg>\n"
"		</method>\n"
"		<method name=\"DumpCurrentMenu\">\n"
"			\n"
"			<arg name=\"json\" type=\"s\" direction=\"out\">\n"
"				\n"
"			</arg>\n"
"		</method>\n"
"		<method name=\"DumpMenu\">\n"
"			\n"
"			<arg name=\"windowId\" type=\"u\" direction=\"in\">\n"
"				\n"
"			</arg>\n"
"			<arg name=\"json\" type=\"s\" direction=\"out\">\n"
"				\n"
"			</arg>\n"
"		</method>\n"
"	</interface>\n"
"</node>\n"
;
