/* ubuntu-video-search.c generated by valac 0.56.19, the Vala compiler
 * generated from ubuntu-video-search.vala, do not modify */

/*
 * Copyright (C) 2012 Canonical Ltd
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Authored by Pawel Stolowski <pawel.stolowski@canonical.com>
 *
 */

#define _XOPEN_SOURCE

#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gee.h>
#include <glib-object.h>
#include <json-glib/json-glib.h>
#include <time.h>
#include <glib/gi18n-lib.h>

#define UNITY_VIDEO_LENS_UBUNTU_VIDEO_SEARCH_SERVER "http://videosearch.ubuntu.com/v0"
#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))

#define UNITY_VIDEO_LENS_TYPE_REMOTE_VIDEO_FILE (unity_video_lens_remote_video_file_get_type ())
typedef struct _UnityVideoLensRemoteVideoFile UnityVideoLensRemoteVideoFile;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _json_array_unref0(var) ((var == NULL) ? NULL : (var = (json_array_unref (var), NULL)))
#define __vala_JsonNode_free0(var) ((var == NULL) ? NULL : (var = (_vala_JsonNode_free (var), NULL)))
typedef struct _Block1Data Block1Data;
typedef struct _Block2Data Block2Data;

#define UNITY_VIDEO_LENS_TYPE_REMOTE_VIDEO_DETAILS (unity_video_lens_remote_video_details_get_type ())
typedef struct _UnityVideoLensRemoteVideoDetails UnityVideoLensRemoteVideoDetails;
#define _json_object_unref0(var) ((var == NULL) ? NULL : (var = (json_object_unref (var), NULL)))
typedef struct _Block3Data Block3Data;
typedef struct _Block4Data Block4Data;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _UnityVideoLensRemoteVideoFile {
	gchar* title;
	gchar* comment;
	gchar* uri;
	gchar* icon;
	gchar* details_uri;
	gchar* price;
	gint category;
};

struct _Block1Data {
	int _ref_count_;
	GString* res;
	guint len;
	gchar* separator;
};

struct _Block2Data {
	int _ref_count_;
	gchar** res;
	gint res_length1;
	gint _res_size_;
};

struct _UnityVideoLensRemoteVideoDetails {
	gchar* title;
	gchar* description;
	gchar* uri;
	gchar* image;
	gchar* source;
	gchar* release_date;
	gint duration;
	gchar** directors;
	gint directors_length1;
	gchar* starring;
	gchar** genres;
	gint genres_length1;
	gchar* uploaded_by;
	gchar* date_uploaded;
	gchar* price;
};

struct _Block3Data {
	int _ref_count_;
	GeeArrayList* results;
};

struct _Block4Data {
	int _ref_count_;
	GeeArrayList* videos;
	gint category;
};

VALA_EXTERN gint unity_video_lens_CAT_INDEX_ONLINE;
VALA_EXTERN gint unity_video_lens_CAT_INDEX_MORE;

VALA_EXTERN gchar* unity_video_lens_ubuntu_video_search_sources_uri (void);
VALA_EXTERN gchar* unity_video_lens_ubuntu_video_search_recommendations_uri (void);
VALA_EXTERN gchar* unity_video_lens_ubuntu_video_search_build_search_uri (const gchar* query,
                                                              GeeArrayList* sources,
                                                              const gchar* form_factor);
VALA_EXTERN GType unity_video_lens_remote_video_file_get_type (void) G_GNUC_CONST ;
VALA_EXTERN UnityVideoLensRemoteVideoFile* unity_video_lens_remote_video_file_dup (const UnityVideoLensRemoteVideoFile* self);
VALA_EXTERN void unity_video_lens_remote_video_file_free (UnityVideoLensRemoteVideoFile* self);
VALA_EXTERN void unity_video_lens_remote_video_file_copy (const UnityVideoLensRemoteVideoFile* self,
                                              UnityVideoLensRemoteVideoFile* dest);
VALA_EXTERN void unity_video_lens_remote_video_file_destroy (UnityVideoLensRemoteVideoFile* self);
G_DEFINE_AUTO_CLEANUP_CLEAR_FUNC (UnityVideoLensRemoteVideoFile, unity_video_lens_remote_video_file_destroy)
VALA_EXTERN GeeArrayList* unity_video_lens_ubuntu_video_search_process_search_results (const gchar* json_data,
                                                                           gboolean is_treat_yourself,
                                                                           GError** error);
static JsonNode* _vala_JsonNode_copy (JsonNode* self);
VALA_EXTERN GeeArrayList* unity_video_lens_ubuntu_video_search_process_results_array (JsonArray* results,
                                                                          gint category);
static void _vala_JsonNode_free (JsonNode* self);
VALA_EXTERN gchar* unity_video_lens_ubuntu_video_search_join_array (JsonArray* array,
                                                        const gchar* separator);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static void __lambda7_ (Block1Data* _data1_,
                 JsonArray* a,
                 guint index,
                 JsonNode* node);
static void ___lambda7__json_array_foreach (JsonArray* array,
                                     guint index_,
                                     JsonNode* element_node,
                                     gpointer self);
VALA_EXTERN gchar** unity_video_lens_ubuntu_video_search_json_array_to_str_array (JsonArray* array,
                                                                      gint* result_length1);
static Block2Data* block2_data_ref (Block2Data* _data2_);
static void block2_data_unref (void * _userdata_);
static void __lambda8_ (Block2Data* _data2_,
                 JsonArray* a,
                 guint index,
                 JsonNode* node);
static void _vala_array_add1 (gchar** * array,
                       gint* length,
                       gint* size,
                       gchar* value);
static void ___lambda8__json_array_foreach (JsonArray* array,
                                     guint index_,
                                     JsonNode* element_node,
                                     gpointer self);
static gchar** _vala_array_dup1 (gchar** self,
                          gssize length);
VALA_EXTERN GType unity_video_lens_remote_video_details_get_type (void) G_GNUC_CONST ;
VALA_EXTERN UnityVideoLensRemoteVideoDetails* unity_video_lens_remote_video_details_dup (const UnityVideoLensRemoteVideoDetails* self);
VALA_EXTERN void unity_video_lens_remote_video_details_free (UnityVideoLensRemoteVideoDetails* self);
VALA_EXTERN void unity_video_lens_remote_video_details_copy (const UnityVideoLensRemoteVideoDetails* self,
                                                 UnityVideoLensRemoteVideoDetails* dest);
VALA_EXTERN void unity_video_lens_remote_video_details_destroy (UnityVideoLensRemoteVideoDetails* self);
G_DEFINE_AUTO_CLEANUP_CLEAR_FUNC (UnityVideoLensRemoteVideoDetails, unity_video_lens_remote_video_details_destroy)
VALA_EXTERN void unity_video_lens_ubuntu_video_search_process_details_results (const gchar* json_data,
                                                                   UnityVideoLensRemoteVideoDetails* result,
                                                                   GError** error);
VALA_EXTERN GeeArrayList* unity_video_lens_ubuntu_video_search_process_sources_results (const gchar* json_data,
                                                                            GError** error);
static Block3Data* block3_data_ref (Block3Data* _data3_);
static void block3_data_unref (void * _userdata_);
static void __lambda4_ (Block3Data* _data3_,
                 JsonArray* array,
                 guint index,
                 JsonNode* node);
static void ___lambda4__json_array_foreach (JsonArray* array,
                                     guint index_,
                                     JsonNode* element_node,
                                     gpointer self);
static Block4Data* block4_data_ref (Block4Data* _data4_);
static void block4_data_unref (void * _userdata_);
static void __lambda6_ (Block4Data* _data4_,
                 JsonArray* array,
                 guint index,
                 JsonNode* node);
static void ___lambda6__json_array_foreach (JsonArray* array,
                                     guint index_,
                                     JsonNode* element_node,
                                     gpointer self);
static void _vala_array_destroy (gpointer array,
                          gssize array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gssize array_length,
                       GDestroyNotify destroy_func);

gchar*
unity_video_lens_ubuntu_video_search_sources_uri (void)
{
	gchar* _tmp0_;
	gchar* result;
	_tmp0_ = g_strdup (UNITY_VIDEO_LENS_UBUNTU_VIDEO_SEARCH_SERVER "/sources");
	result = _tmp0_;
	return result;
}

gchar*
unity_video_lens_ubuntu_video_search_recommendations_uri (void)
{
	gchar* _tmp0_;
	gchar* result;
	_tmp0_ = g_strdup (UNITY_VIDEO_LENS_UBUNTU_VIDEO_SEARCH_SERVER "/search?q=");
	result = _tmp0_;
	return result;
}

gchar*
unity_video_lens_ubuntu_video_search_build_search_uri (const gchar* query,
                                                       GeeArrayList* sources,
                                                       const gchar* form_factor)
{
	GString* uri = NULL;
	GString* _tmp0_;
	GString* _tmp1_;
	GString* _tmp2_;
	GString* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	GString* _tmp6_;
	gboolean _tmp7_ = FALSE;
	GString* _tmp24_;
	const gchar* _tmp25_;
	gchar* _tmp26_;
	gchar* result;
	g_return_val_if_fail (query != NULL, NULL);
	_tmp0_ = g_string_new ("");
	uri = _tmp0_;
	_tmp1_ = uri;
	g_string_append (_tmp1_, UNITY_VIDEO_LENS_UBUNTU_VIDEO_SEARCH_SERVER);
	_tmp2_ = uri;
	g_string_append (_tmp2_, "/search?q=");
	_tmp3_ = uri;
	_tmp4_ = g_uri_escape_string (query, "", FALSE);
	_tmp5_ = _tmp4_;
	g_string_append (_tmp3_, _tmp5_);
	_g_free0 (_tmp5_);
	_tmp6_ = uri;
	g_string_append (_tmp6_, "&split=true");
	if (sources != NULL) {
		gint _tmp8_;
		gint _tmp9_;
		_tmp8_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) sources);
		_tmp9_ = _tmp8_;
		_tmp7_ = _tmp9_ > 0;
	} else {
		_tmp7_ = FALSE;
	}
	if (_tmp7_) {
		GString* _tmp10_;
		GString* _tmp11_;
		gpointer _tmp12_;
		gchar* _tmp13_;
		_tmp10_ = uri;
		g_string_append (_tmp10_, "&sources=");
		_tmp11_ = uri;
		_tmp12_ = gee_abstract_list_get ((GeeAbstractList*) sources, 0);
		_tmp13_ = (gchar*) _tmp12_;
		g_string_append (_tmp11_, _tmp13_);
		_g_free0 (_tmp13_);
		{
			gint i = 0;
			i = 1;
			{
				gboolean _tmp14_ = FALSE;
				_tmp14_ = TRUE;
				while (TRUE) {
					gint _tmp16_;
					gint _tmp17_;
					GString* _tmp18_;
					GString* _tmp19_;
					gpointer _tmp20_;
					gchar* _tmp21_;
					if (!_tmp14_) {
						gint _tmp15_;
						_tmp15_ = i;
						i = _tmp15_ + 1;
					}
					_tmp14_ = FALSE;
					_tmp16_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) sources);
					_tmp17_ = _tmp16_;
					if (!(i < _tmp17_)) {
						break;
					}
					_tmp18_ = uri;
					g_string_append (_tmp18_, ",");
					_tmp19_ = uri;
					_tmp20_ = gee_abstract_list_get ((GeeAbstractList*) sources, i);
					_tmp21_ = (gchar*) _tmp20_;
					g_string_append (_tmp19_, _tmp21_);
					_g_free0 (_tmp21_);
				}
			}
		}
	}
	if (form_factor != NULL) {
		GString* _tmp22_;
		GString* _tmp23_;
		_tmp22_ = uri;
		g_string_append (_tmp22_, "&form_factor=");
		_tmp23_ = uri;
		g_string_append (_tmp23_, form_factor);
	}
	_tmp24_ = uri;
	_tmp25_ = _tmp24_->str;
	_tmp26_ = g_strdup (_tmp25_);
	result = _tmp26_;
	_g_string_free0 (uri);
	return result;
}

/**
   * Parses JSON data returned by search requests, returns list of videos.
   */
static JsonNode*
_vala_JsonNode_copy (JsonNode* self)
{
	return g_boxed_copy (json_node_get_type (), self);
}

static gpointer
__vala_JsonNode_copy0 (gpointer self)
{
	return self ? _vala_JsonNode_copy (self) : NULL;
}

static gpointer
_json_array_ref0 (gpointer self)
{
	return self ? json_array_ref (self) : NULL;
}

static void
_vala_JsonNode_free (JsonNode* self)
{
	g_boxed_free (json_node_get_type (), self);
}

GeeArrayList*
unity_video_lens_ubuntu_video_search_process_search_results (const gchar* json_data,
                                                             gboolean is_treat_yourself,
                                                             GError** error)
{
	JsonParser* parser = NULL;
	JsonParser* _tmp0_;
	JsonNode* root = NULL;
	JsonNode* _tmp1_;
	JsonNode* _tmp2_;
	JsonNode* _tmp3_;
	GError* _inner_error0_ = NULL;
	GeeArrayList* result;
	g_return_val_if_fail (json_data != NULL, NULL);
	_tmp0_ = json_parser_new ();
	parser = _tmp0_;
	json_parser_load_from_data (parser, json_data, (gssize) -1, &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_propagate_error (error, _inner_error0_);
		_g_object_unref0 (parser);
		return NULL;
	}
	_tmp1_ = json_parser_get_root (parser);
	_tmp2_ = __vala_JsonNode_copy0 (_tmp1_);
	root = _tmp2_;
	_tmp3_ = root;
	if (json_node_get_node_type (_tmp3_) == JSON_NODE_OBJECT) {
		JsonArray* records = NULL;
		JsonNode* _tmp4_;
		JsonObject* _tmp5_;
		JsonArray* _tmp6_;
		JsonArray* _tmp7_;
		GeeArrayList* results = NULL;
		JsonArray* _tmp8_;
		GeeArrayList* _tmp9_;
		JsonNode* _tmp10_;
		JsonObject* _tmp11_;
		JsonArray* _tmp12_;
		JsonArray* _tmp13_;
		GeeArrayList* _tmp14_;
		JsonArray* _tmp15_;
		GeeArrayList* _tmp16_;
		GeeArrayList* _tmp17_;
		_tmp4_ = root;
		_tmp5_ = json_node_get_object (_tmp4_);
		_tmp6_ = json_object_get_array_member (_tmp5_, "other");
		_tmp7_ = _json_array_ref0 (_tmp6_);
		records = _tmp7_;
		_tmp8_ = records;
		_tmp9_ = unity_video_lens_ubuntu_video_search_process_results_array (_tmp8_, unity_video_lens_CAT_INDEX_ONLINE);
		results = _tmp9_;
		_tmp10_ = root;
		_tmp11_ = json_node_get_object (_tmp10_);
		_tmp12_ = json_object_get_array_member (_tmp11_, "treats");
		_tmp13_ = _json_array_ref0 (_tmp12_);
		_json_array_unref0 (records);
		records = _tmp13_;
		_tmp14_ = results;
		_tmp15_ = records;
		_tmp16_ = unity_video_lens_ubuntu_video_search_process_results_array (_tmp15_, unity_video_lens_CAT_INDEX_MORE);
		_tmp17_ = _tmp16_;
		gee_array_list_add_all (_tmp14_, (GeeCollection*) _tmp17_);
		_g_object_unref0 (_tmp17_);
		result = results;
		_json_array_unref0 (records);
		__vala_JsonNode_free0 (root);
		_g_object_unref0 (parser);
		return result;
	} else {
		JsonArray* records = NULL;
		JsonNode* _tmp18_;
		JsonArray* _tmp19_;
		JsonArray* _tmp20_;
		gint _tmp21_ = 0;
		GeeArrayList* results = NULL;
		JsonArray* _tmp22_;
		GeeArrayList* _tmp23_;
		_tmp18_ = root;
		_tmp19_ = json_node_get_array (_tmp18_);
		_tmp20_ = _json_array_ref0 (_tmp19_);
		records = _tmp20_;
		if (is_treat_yourself) {
			_tmp21_ = unity_video_lens_CAT_INDEX_MORE;
		} else {
			_tmp21_ = unity_video_lens_CAT_INDEX_ONLINE;
		}
		_tmp22_ = records;
		_tmp23_ = unity_video_lens_ubuntu_video_search_process_results_array (_tmp22_, _tmp21_);
		results = _tmp23_;
		result = results;
		_json_array_unref0 (records);
		__vala_JsonNode_free0 (root);
		_g_object_unref0 (parser);
		return result;
	}
}

/**
   * Joins elements of JSON array of strings.
   */
static Block1Data*
block1_data_ref (Block1Data* _data1_)
{
	g_atomic_int_inc (&_data1_->_ref_count_);
	return _data1_;
}

static void
block1_data_unref (void * _userdata_)
{
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
		_g_string_free0 (_data1_->res);
		_g_free0 (_data1_->separator);
		g_slice_free (Block1Data, _data1_);
	}
}

static void
__lambda7_ (Block1Data* _data1_,
            JsonArray* a,
            guint index,
            JsonNode* node)
{
	const gchar* _tmp0_;
	g_return_if_fail (a != NULL);
	g_return_if_fail (node != NULL);
	_tmp0_ = json_node_get_string (node);
	g_string_append (_data1_->res, _tmp0_);
	if (index < (_data1_->len - 1)) {
		g_string_append (_data1_->res, _data1_->separator);
	}
}

static void
___lambda7__json_array_foreach (JsonArray* array,
                                guint index_,
                                JsonNode* element_node,
                                gpointer self)
{
	__lambda7_ (self, array, index_, element_node);
}

gchar*
unity_video_lens_ubuntu_video_search_join_array (JsonArray* array,
                                                 const gchar* separator)
{
	Block1Data* _data1_;
	gchar* _tmp0_;
	GString* _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* result;
	g_return_val_if_fail (array != NULL, NULL);
	g_return_val_if_fail (separator != NULL, NULL);
	_data1_ = g_slice_new0 (Block1Data);
	_data1_->_ref_count_ = 1;
	_tmp0_ = g_strdup (separator);
	_g_free0 (_data1_->separator);
	_data1_->separator = _tmp0_;
	_tmp1_ = g_string_new ("");
	_data1_->res = _tmp1_;
	_data1_->len = json_array_get_length (array);
	json_array_foreach_element (array, ___lambda7__json_array_foreach, _data1_);
	_tmp2_ = _data1_->res->str;
	_tmp3_ = g_strdup (_tmp2_);
	result = _tmp3_;
	block1_data_unref (_data1_);
	_data1_ = NULL;
	return result;
}

static Block2Data*
block2_data_ref (Block2Data* _data2_)
{
	g_atomic_int_inc (&_data2_->_ref_count_);
	return _data2_;
}

static void
block2_data_unref (void * _userdata_)
{
	Block2Data* _data2_;
	_data2_ = (Block2Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data2_->_ref_count_)) {
		_data2_->res = (_vala_array_free (_data2_->res, _data2_->res_length1, (GDestroyNotify) g_free), NULL);
		g_slice_free (Block2Data, _data2_);
	}
}

static void
_vala_array_add1 (gchar** * array,
                  gint* length,
                  gint* size,
                  gchar* value)
{
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}

static void
__lambda8_ (Block2Data* _data2_,
            JsonArray* a,
            guint index,
            JsonNode* node)
{
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (a != NULL);
	g_return_if_fail (node != NULL);
	_tmp0_ = json_node_get_string (node);
	_tmp1_ = g_strdup (_tmp0_);
	_vala_array_add1 (&_data2_->res, &_data2_->res_length1, &_data2_->_res_size_, _tmp1_);
}

static void
___lambda8__json_array_foreach (JsonArray* array,
                                guint index_,
                                JsonNode* element_node,
                                gpointer self)
{
	__lambda8_ (self, array, index_, element_node);
}

static gchar**
_vala_array_dup1 (gchar** self,
                  gssize length)
{
	if (length >= 0) {
		gchar** result;
		gssize i;
		result = g_new0 (gchar*, length + 1);
		for (i = 0; i < length; i++) {
			gchar* _tmp0_;
			_tmp0_ = g_strdup (self[i]);
			result[i] = _tmp0_;
		}
		return result;
	}
	return NULL;
}

gchar**
unity_video_lens_ubuntu_video_search_json_array_to_str_array (JsonArray* array,
                                                              gint* result_length1)
{
	Block2Data* _data2_;
	gchar** _tmp0_;
	gchar** _tmp1_;
	gint _tmp1__length1;
	gchar** _tmp2_;
	gint _tmp2__length1;
	gchar** result;
	g_return_val_if_fail (array != NULL, NULL);
	_data2_ = g_slice_new0 (Block2Data);
	_data2_->_ref_count_ = 1;
	_tmp0_ = g_new0 (gchar*, 0 + 1);
	_data2_->res = _tmp0_;
	_data2_->res_length1 = 0;
	_data2_->_res_size_ = _data2_->res_length1;
	json_array_foreach_element (array, ___lambda8__json_array_foreach, _data2_);
	_tmp1_ = (_data2_->res != NULL) ? _vala_array_dup1 (_data2_->res, _data2_->res_length1) : _data2_->res;
	_tmp1__length1 = _data2_->res_length1;
	_tmp2_ = _tmp1_;
	_tmp2__length1 = _tmp1__length1;
	if (result_length1) {
		*result_length1 = _tmp2__length1;
	}
	result = _tmp2_;
	block2_data_unref (_data2_);
	_data2_ = NULL;
	return result;
}

static gpointer
_json_object_ref0 (gpointer self)
{
	return self ? json_object_ref (self) : NULL;
}

static gchar*
g_time_format (struct tm *self,
               const gchar* format)
{
	gchar* buffer = NULL;
	gchar* _tmp0_;
	gint buffer_length1;
	gint _buffer_size_;
	gchar* _tmp1_;
	gchar* result;
	g_return_val_if_fail (format != NULL, NULL);
	_tmp0_ = g_new0 (gchar, 64);
	buffer = _tmp0_;
	buffer_length1 = 64;
	_buffer_size_ = buffer_length1;
	strftime (buffer, (gint) buffer_length1, format, &(*self));
	_tmp1_ = g_strdup ((const gchar*) buffer);
	result = _tmp1_;
	buffer = (g_free (buffer), NULL);
	return result;
}

void
unity_video_lens_ubuntu_video_search_process_details_results (const gchar* json_data,
                                                              UnityVideoLensRemoteVideoDetails* result,
                                                              GError** error)
{
	JsonParser* parser = NULL;
	JsonParser* _tmp0_;
	JsonObject* details = NULL;
	JsonNode* _tmp1_;
	JsonObject* _tmp2_;
	JsonObject* _tmp3_;
	UnityVideoLensRemoteVideoDetails video = {0};
	JsonObject* _tmp4_;
	const gchar* _tmp5_;
	gchar* _tmp6_;
	JsonObject* _tmp7_;
	const gchar* _tmp8_;
	gchar* _tmp9_;
	JsonObject* _tmp10_;
	const gchar* _tmp11_;
	gchar* _tmp12_;
	JsonObject* _tmp13_;
	const gchar* _tmp14_;
	gchar* _tmp15_;
	JsonObject* _tmp16_;
	const gchar* _tmp23_ = NULL;
	JsonObject* _tmp24_;
	gchar* _tmp27_;
	JsonObject* _tmp28_;
	gchar** _tmp31_;
	JsonObject* _tmp32_;
	JsonObject* _tmp39_;
	gchar** _tmp45_;
	JsonObject* _tmp46_;
	JsonObject* _tmp53_;
	JsonObject* _tmp57_;
	GError* _inner_error0_ = NULL;
	g_return_if_fail (json_data != NULL);
	_tmp0_ = json_parser_new ();
	parser = _tmp0_;
	json_parser_load_from_data (parser, json_data, (gssize) -1, &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_propagate_error (error, _inner_error0_);
		_g_object_unref0 (parser);
		return;
	}
	_tmp1_ = json_parser_get_root (parser);
	_tmp2_ = json_node_get_object (_tmp1_);
	_tmp3_ = _json_object_ref0 (_tmp2_);
	details = _tmp3_;
	memset (&video, 0, sizeof (UnityVideoLensRemoteVideoDetails));
	_tmp4_ = details;
	_tmp5_ = json_object_get_string_member (_tmp4_, "title");
	_tmp6_ = g_strdup (_tmp5_);
	_g_free0 (video.title);
	video.title = _tmp6_;
	_tmp7_ = details;
	_tmp8_ = json_object_get_string_member (_tmp7_, "image");
	_tmp9_ = g_strdup (_tmp8_);
	_g_free0 (video.image);
	video.image = _tmp9_;
	_tmp10_ = details;
	_tmp11_ = json_object_get_string_member (_tmp10_, "description");
	_tmp12_ = g_strdup (_tmp11_);
	_g_free0 (video.description);
	video.description = _tmp12_;
	_tmp13_ = details;
	_tmp14_ = json_object_get_string_member (_tmp13_, "source");
	_tmp15_ = g_strdup (_tmp14_);
	_g_free0 (video.source);
	video.source = _tmp15_;
	_tmp16_ = details;
	if (json_object_has_member (_tmp16_, "release_date")) {
		struct tm release_date = {0};
		JsonObject* _tmp17_;
		const gchar* _tmp18_;
		const gchar* _tmp19_;
		memset (&release_date, 0, sizeof (struct tm));
		_tmp17_ = details;
		_tmp18_ = json_object_get_string_member (_tmp17_, "release_date");
		_tmp19_ = strptime (_tmp18_, "%Y-%m-%d", &release_date);
		if (_tmp19_ != NULL) {
			gchar* _tmp20_;
			_tmp20_ = g_time_format (&release_date, "%Y");
			_g_free0 (video.release_date);
			video.release_date = _tmp20_;
		} else {
			JsonObject* _tmp21_;
			const gchar* _tmp22_;
			_tmp21_ = details;
			_tmp22_ = json_object_get_string_member (_tmp21_, "release_date");
			g_warning ("ubuntu-video-search.vala:133: Failed to parse release_date: '%s'", _tmp22_);
		}
	}
	_tmp24_ = details;
	if (json_object_has_member (_tmp24_, "formatted_price")) {
		JsonObject* _tmp25_;
		const gchar* _tmp26_;
		_tmp25_ = details;
		_tmp26_ = json_object_get_string_member (_tmp25_, "formatted_price");
		_tmp23_ = _tmp26_;
	} else {
		_tmp23_ = "";
	}
	_tmp27_ = g_strdup (_tmp23_);
	_g_free0 (video.price);
	video.price = _tmp27_;
	video.duration = 0;
	_tmp28_ = details;
	if (json_object_has_member (_tmp28_, "duration")) {
		JsonObject* _tmp29_;
		const gchar* _tmp30_;
		_tmp29_ = details;
		_tmp30_ = json_object_get_string_member (_tmp29_, "duration");
		video.duration = atoi (_tmp30_) / 60;
	}
	_tmp31_ = g_new0 (gchar*, 0 + 1);
	video.directors = (_vala_array_free (video.directors, video.directors_length1, (GDestroyNotify) g_free), NULL);
	video.directors = _tmp31_;
	video.directors_length1 = 0;
	_tmp32_ = details;
	if (json_object_has_member (_tmp32_, "directors")) {
		JsonArray* directors = NULL;
		JsonObject* _tmp33_;
		JsonArray* _tmp34_;
		JsonArray* _tmp35_;
		JsonArray* _tmp36_;
		gint _tmp37_ = 0;
		gchar** _tmp38_;
		_tmp33_ = details;
		_tmp34_ = json_object_get_array_member (_tmp33_, "directors");
		_tmp35_ = _json_array_ref0 (_tmp34_);
		directors = _tmp35_;
		_tmp36_ = directors;
		_tmp38_ = unity_video_lens_ubuntu_video_search_json_array_to_str_array (_tmp36_, &_tmp37_);
		video.directors = (_vala_array_free (video.directors, video.directors_length1, (GDestroyNotify) g_free), NULL);
		video.directors = _tmp38_;
		video.directors_length1 = _tmp37_;
		_json_array_unref0 (directors);
	}
	_tmp39_ = details;
	if (json_object_has_member (_tmp39_, "starring")) {
		JsonArray* starring = NULL;
		JsonObject* _tmp40_;
		JsonArray* _tmp41_;
		JsonArray* _tmp42_;
		JsonArray* _tmp43_;
		gchar* _tmp44_;
		_tmp40_ = details;
		_tmp41_ = json_object_get_array_member (_tmp40_, "starring");
		_tmp42_ = _json_array_ref0 (_tmp41_);
		starring = _tmp42_;
		_tmp43_ = starring;
		_tmp44_ = unity_video_lens_ubuntu_video_search_join_array (_tmp43_, ", ");
		_g_free0 (video.starring);
		video.starring = _tmp44_;
		_json_array_unref0 (starring);
	}
	_tmp45_ = g_new0 (gchar*, 0 + 1);
	video.genres = (_vala_array_free (video.genres, video.genres_length1, (GDestroyNotify) g_free), NULL);
	video.genres = _tmp45_;
	video.genres_length1 = 0;
	_tmp46_ = details;
	if (json_object_has_member (_tmp46_, "genres")) {
		JsonArray* genres = NULL;
		JsonObject* _tmp47_;
		JsonArray* _tmp48_;
		JsonArray* _tmp49_;
		JsonArray* _tmp50_;
		gint _tmp51_ = 0;
		gchar** _tmp52_;
		_tmp47_ = details;
		_tmp48_ = json_object_get_array_member (_tmp47_, "genres");
		_tmp49_ = _json_array_ref0 (_tmp48_);
		genres = _tmp49_;
		_tmp50_ = genres;
		_tmp52_ = unity_video_lens_ubuntu_video_search_json_array_to_str_array (_tmp50_, &_tmp51_);
		video.genres = (_vala_array_free (video.genres, video.genres_length1, (GDestroyNotify) g_free), NULL);
		video.genres = _tmp52_;
		video.genres_length1 = _tmp51_;
		_json_array_unref0 (genres);
	}
	_tmp53_ = details;
	if (json_object_has_member (_tmp53_, "uploaded_by")) {
		JsonObject* _tmp54_;
		const gchar* _tmp55_;
		gchar* _tmp56_;
		_tmp54_ = details;
		_tmp55_ = json_object_get_string_member (_tmp54_, "uploaded_by");
		_tmp56_ = g_strdup (_tmp55_);
		_g_free0 (video.uploaded_by);
		video.uploaded_by = _tmp56_;
	}
	_tmp57_ = details;
	if (json_object_has_member (_tmp57_, "date_uploaded")) {
		JsonObject* _tmp58_;
		const gchar* _tmp59_;
		gchar* _tmp60_;
		_tmp58_ = details;
		_tmp59_ = json_object_get_string_member (_tmp58_, "date_uploaded");
		_tmp60_ = g_strdup (_tmp59_);
		_g_free0 (video.date_uploaded);
		video.date_uploaded = _tmp60_;
	}
	*result = video;
	_json_object_unref0 (details);
	_g_object_unref0 (parser);
	return;
}

/**
   * Parses JSON data returned by 'sources' query, returns list of sources (e.g. "Amazon", "Youtube" etc.)
   */
static Block3Data*
block3_data_ref (Block3Data* _data3_)
{
	g_atomic_int_inc (&_data3_->_ref_count_);
	return _data3_;
}

static void
block3_data_unref (void * _userdata_)
{
	Block3Data* _data3_;
	_data3_ = (Block3Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data3_->_ref_count_)) {
		_g_object_unref0 (_data3_->results);
		g_slice_free (Block3Data, _data3_);
	}
}

static void
__lambda4_ (Block3Data* _data3_,
            JsonArray* array,
            guint index,
            JsonNode* node)
{
	GeeArrayList* _tmp0_;
	const gchar* _tmp1_;
	g_return_if_fail (array != NULL);
	g_return_if_fail (node != NULL);
	_tmp0_ = _data3_->results;
	_tmp1_ = json_node_get_string (node);
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp0_, _tmp1_);
}

static void
___lambda4__json_array_foreach (JsonArray* array,
                                guint index_,
                                JsonNode* element_node,
                                gpointer self)
{
	__lambda4_ (self, array, index_, element_node);
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

GeeArrayList*
unity_video_lens_ubuntu_video_search_process_sources_results (const gchar* json_data,
                                                              GError** error)
{
	Block3Data* _data3_;
	JsonParser* parser = NULL;
	JsonParser* _tmp0_;
	JsonArray* sources_array = NULL;
	JsonNode* _tmp1_;
	JsonArray* _tmp2_;
	JsonArray* _tmp3_;
	GeeArrayList* _tmp4_;
	JsonArray* _tmp5_;
	GeeArrayList* _tmp6_;
	GeeArrayList* _tmp7_;
	GError* _inner_error0_ = NULL;
	GeeArrayList* result;
	g_return_val_if_fail (json_data != NULL, NULL);
	_data3_ = g_slice_new0 (Block3Data);
	_data3_->_ref_count_ = 1;
	_tmp0_ = json_parser_new ();
	parser = _tmp0_;
	json_parser_load_from_data (parser, json_data, (gssize) -1, &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_propagate_error (error, _inner_error0_);
		_g_object_unref0 (parser);
		block3_data_unref (_data3_);
		_data3_ = NULL;
		return NULL;
	}
	_tmp1_ = json_parser_get_root (parser);
	_tmp2_ = json_node_get_array (_tmp1_);
	_tmp3_ = _json_array_ref0 (_tmp2_);
	sources_array = _tmp3_;
	_tmp4_ = gee_array_list_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, NULL, NULL, NULL);
	_data3_->results = _tmp4_;
	_tmp5_ = sources_array;
	json_array_foreach_element (_tmp5_, ___lambda4__json_array_foreach, _data3_);
	_tmp6_ = _data3_->results;
	_tmp7_ = _g_object_ref0 (_tmp6_);
	result = _tmp7_;
	_json_array_unref0 (sources_array);
	_g_object_unref0 (parser);
	block3_data_unref (_data3_);
	_data3_ = NULL;
	return result;
}

/**
   * Converts JSON results array to list of RemoteVideoFile records.
   */
static Block4Data*
block4_data_ref (Block4Data* _data4_)
{
	g_atomic_int_inc (&_data4_->_ref_count_);
	return _data4_;
}

static void
block4_data_unref (void * _userdata_)
{
	Block4Data* _data4_;
	_data4_ = (Block4Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data4_->_ref_count_)) {
		_g_object_unref0 (_data4_->videos);
		g_slice_free (Block4Data, _data4_);
	}
}

static void
__lambda6_ (Block4Data* _data4_,
            JsonArray* array,
            guint index,
            JsonNode* node)
{
	GError* _inner_error0_ = NULL;
	g_return_if_fail (array != NULL);
	g_return_if_fail (node != NULL);
	{
		UnityVideoLensRemoteVideoFile video = {0};
		JsonObject* rec = NULL;
		JsonObject* _tmp0_;
		JsonObject* _tmp1_;
		JsonObject* _tmp2_;
		const gchar* _tmp3_;
		gchar* _tmp4_;
		JsonObject* _tmp5_;
		const gchar* _tmp6_;
		gchar* _tmp7_;
		JsonObject* _tmp8_;
		const gchar* _tmp9_;
		gchar* _tmp10_;
		JsonObject* _tmp11_;
		const gchar* _tmp12_;
		gchar* _tmp13_;
		const gchar* _tmp14_ = NULL;
		JsonObject* _tmp15_;
		gchar* _tmp18_;
		UnityVideoLensRemoteVideoFile _tmp29_;
		memset (&video, 0, sizeof (UnityVideoLensRemoteVideoFile));
		_tmp0_ = json_node_get_object (node);
		_tmp1_ = _json_object_ref0 (_tmp0_);
		rec = _tmp1_;
		_tmp2_ = rec;
		_tmp3_ = json_object_get_string_member (_tmp2_, "url");
		_tmp4_ = g_strdup (_tmp3_);
		_g_free0 (video.uri);
		video.uri = _tmp4_;
		_tmp5_ = rec;
		_tmp6_ = json_object_get_string_member (_tmp5_, "title");
		_tmp7_ = g_strdup (_tmp6_);
		_g_free0 (video.title);
		video.title = _tmp7_;
		_tmp8_ = rec;
		_tmp9_ = json_object_get_string_member (_tmp8_, "img");
		_tmp10_ = g_strdup (_tmp9_);
		_g_free0 (video.icon);
		video.icon = _tmp10_;
		_tmp11_ = rec;
		_tmp12_ = json_object_get_string_member (_tmp11_, "source");
		_tmp13_ = g_strdup (_tmp12_);
		_g_free0 (video.comment);
		video.comment = _tmp13_;
		_tmp15_ = rec;
		if (json_object_has_member (_tmp15_, "details")) {
			JsonObject* _tmp16_;
			const gchar* _tmp17_;
			_tmp16_ = rec;
			_tmp17_ = json_object_get_string_member (_tmp16_, "details");
			_tmp14_ = _tmp17_;
		} else {
			_tmp14_ = "";
		}
		_tmp18_ = g_strdup (_tmp14_);
		_g_free0 (video.details_uri);
		video.details_uri = _tmp18_;
		video.category = _data4_->category;
		_g_free0 (video.price);
		video.price = NULL;
		if (_data4_->category == unity_video_lens_CAT_INDEX_MORE) {
			gchar* price = NULL;
			JsonObject* _tmp19_;
			gboolean _tmp23_ = FALSE;
			const gchar* _tmp24_;
			const gchar* _tmp27_;
			gchar* _tmp28_;
			price = NULL;
			_tmp19_ = rec;
			if (json_object_has_member (_tmp19_, "formatted_price")) {
				JsonObject* _tmp20_;
				const gchar* _tmp21_;
				gchar* _tmp22_;
				_tmp20_ = rec;
				_tmp21_ = json_object_get_string_member (_tmp20_, "formatted_price");
				_tmp22_ = g_strdup (_tmp21_);
				_g_free0 (price);
				price = _tmp22_;
			}
			_tmp24_ = price;
			if (_tmp24_ == NULL) {
				_tmp23_ = TRUE;
			} else {
				const gchar* _tmp25_;
				_tmp25_ = price;
				_tmp23_ = g_strcmp0 (_tmp25_, "free") == 0;
			}
			if (_tmp23_) {
				gchar* _tmp26_;
				_tmp26_ = g_strdup (_ ("Free"));
				_g_free0 (price);
				price = _tmp26_;
			}
			_tmp27_ = price;
			_tmp28_ = g_strdup (_tmp27_);
			_g_free0 (video.price);
			video.price = _tmp28_;
			_g_free0 (price);
		}
		_tmp29_ = video;
		gee_abstract_collection_add ((GeeAbstractCollection*) _data4_->videos, &_tmp29_);
		_json_object_unref0 (rec);
		unity_video_lens_remote_video_file_destroy (&video);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GError* _tmp30_;
		const gchar* _tmp31_;
		e = _inner_error0_;
		_inner_error0_ = NULL;
		_tmp30_ = e;
		_tmp31_ = _tmp30_->message;
		g_warning ("ubuntu-video-search.vala:229: Malformed result, skipping: %s", _tmp31_);
		_g_error_free0 (e);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
}

static void
___lambda6__json_array_foreach (JsonArray* array,
                                guint index_,
                                JsonNode* element_node,
                                gpointer self)
{
	__lambda6_ (self, array, index_, element_node);
}

GeeArrayList*
unity_video_lens_ubuntu_video_search_process_results_array (JsonArray* results,
                                                            gint category)
{
	Block4Data* _data4_;
	GeeArrayList* _tmp0_;
	GeeArrayList* _tmp1_;
	GeeArrayList* result;
	g_return_val_if_fail (results != NULL, NULL);
	_data4_ = g_slice_new0 (Block4Data);
	_data4_->_ref_count_ = 1;
	_data4_->category = category;
	_tmp0_ = gee_array_list_new (UNITY_VIDEO_LENS_TYPE_REMOTE_VIDEO_FILE, (GBoxedCopyFunc) unity_video_lens_remote_video_file_dup, (GDestroyNotify) unity_video_lens_remote_video_file_free, NULL, NULL, NULL);
	_data4_->videos = _tmp0_;
	json_array_foreach_element (results, ___lambda6__json_array_foreach, _data4_);
	_tmp1_ = _g_object_ref0 (_data4_->videos);
	result = _tmp1_;
	block4_data_unref (_data4_);
	_data4_ = NULL;
	return result;
}

static void
_vala_array_destroy (gpointer array,
                     gssize array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gssize i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gssize array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

