/* purchase-info-helper.c generated by valac 0.56.19, the Vala compiler
 * generated from purchase-info-helper.vala, do not modify */

/*
 * Copyright (C) 2012 Canonical Ltd
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Authored by Pawel Stolowski <pawel.stolowski@canonical.com>
 */

#include <glib-object.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <unity-package-search.h>
#include <gobject/gvaluecollector.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define UNITY_APPLICATIONS_LENS_TYPE_PURCHASE_INFO_HELPER (unity_applications_lens_purchase_info_helper_get_type ())
#define UNITY_APPLICATIONS_LENS_PURCHASE_INFO_HELPER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), UNITY_APPLICATIONS_LENS_TYPE_PURCHASE_INFO_HELPER, UnityApplicationsLensPurchaseInfoHelper))
#define UNITY_APPLICATIONS_LENS_PURCHASE_INFO_HELPER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), UNITY_APPLICATIONS_LENS_TYPE_PURCHASE_INFO_HELPER, UnityApplicationsLensPurchaseInfoHelperClass))
#define UNITY_APPLICATIONS_LENS_IS_PURCHASE_INFO_HELPER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), UNITY_APPLICATIONS_LENS_TYPE_PURCHASE_INFO_HELPER))
#define UNITY_APPLICATIONS_LENS_IS_PURCHASE_INFO_HELPER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), UNITY_APPLICATIONS_LENS_TYPE_PURCHASE_INFO_HELPER))
#define UNITY_APPLICATIONS_LENS_PURCHASE_INFO_HELPER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), UNITY_APPLICATIONS_LENS_TYPE_PURCHASE_INFO_HELPER, UnityApplicationsLensPurchaseInfoHelperClass))

typedef struct _UnityApplicationsLensPurchaseInfoHelper UnityApplicationsLensPurchaseInfoHelper;
typedef struct _UnityApplicationsLensPurchaseInfoHelperClass UnityApplicationsLensPurchaseInfoHelperClass;
typedef struct _UnityApplicationsLensPurchaseInfoHelperPrivate UnityApplicationsLensPurchaseInfoHelperPrivate;

#define UNITY_APPLICATIONS_LENS_PURCHASE_INFO_HELPER_TYPE_APP_INFO (unity_applications_lens_purchase_info_helper_app_info_get_type ())
typedef struct _UnityApplicationsLensPurchaseInfoHelperAppInfo UnityApplicationsLensPurchaseInfoHelperAppInfo;
#define _g_hash_table_unref0(var) ((var == NULL) ? NULL : (var = (g_hash_table_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define UNITY_APPLICATIONS_LENS_SOFTWARE_CENTER_DATA_TYPE_APP_INFO (unity_applications_lens_software_center_data_app_info_get_type ())
typedef struct _UnityApplicationsLensSoftwareCenterDataAppInfo UnityApplicationsLensSoftwareCenterDataAppInfo;
#define _unity_applications_lens_software_center_data_app_info_free0(var) ((var == NULL) ? NULL : (var = (unity_applications_lens_software_center_data_app_info_free (var), NULL)))
typedef struct _UnityApplicationsLensParamSpecPurchaseInfoHelper UnityApplicationsLensParamSpecPurchaseInfoHelper;

struct _UnityApplicationsLensPurchaseInfoHelper {
	GTypeInstance parent_instance;
	volatile int ref_count;
	UnityApplicationsLensPurchaseInfoHelperPrivate * priv;
};

struct _UnityApplicationsLensPurchaseInfoHelperClass {
	GTypeClass parent_class;
	void (*finalize) (UnityApplicationsLensPurchaseInfoHelper *self);
};

struct _UnityApplicationsLensPurchaseInfoHelperAppInfo {
	gchar* formatted_price;
	gboolean paid;
};

struct _UnityApplicationsLensPurchaseInfoHelperPrivate {
	GHashTable* data;
};

struct _UnityApplicationsLensSoftwareCenterDataAppInfo {
	gchar* application_name;
	gchar* package_name;
	gchar* icon;
	gchar* desktop_file;
};

struct _UnityApplicationsLensParamSpecPurchaseInfoHelper {
	GParamSpec parent_instance;
};

static gint UnityApplicationsLensPurchaseInfoHelper_private_offset;
static gpointer unity_applications_lens_purchase_info_helper_parent_class = NULL;

VALA_EXTERN gpointer unity_applications_lens_purchase_info_helper_ref (gpointer instance);
VALA_EXTERN void unity_applications_lens_purchase_info_helper_unref (gpointer instance);
VALA_EXTERN GParamSpec* unity_applications_lens_param_spec_purchase_info_helper (const gchar* name,
                                                                     const gchar* nick,
                                                                     const gchar* blurb,
                                                                     GType object_type,
                                                                     GParamFlags flags);
VALA_EXTERN void unity_applications_lens_value_set_purchase_info_helper (GValue* value,
                                                             gpointer v_object);
VALA_EXTERN void unity_applications_lens_value_take_purchase_info_helper (GValue* value,
                                                              gpointer v_object);
VALA_EXTERN gpointer unity_applications_lens_value_get_purchase_info_helper (const GValue* value);
VALA_EXTERN GType unity_applications_lens_purchase_info_helper_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (UnityApplicationsLensPurchaseInfoHelper, unity_applications_lens_purchase_info_helper_unref)
VALA_EXTERN GType unity_applications_lens_purchase_info_helper_app_info_get_type (void) G_GNUC_CONST ;
VALA_EXTERN UnityApplicationsLensPurchaseInfoHelperAppInfo* unity_applications_lens_purchase_info_helper_app_info_dup (const UnityApplicationsLensPurchaseInfoHelperAppInfo* self);
VALA_EXTERN void unity_applications_lens_purchase_info_helper_app_info_free (UnityApplicationsLensPurchaseInfoHelperAppInfo* self);
VALA_EXTERN void unity_applications_lens_purchase_info_helper_app_info_copy (const UnityApplicationsLensPurchaseInfoHelperAppInfo* self,
                                                                 UnityApplicationsLensPurchaseInfoHelperAppInfo* dest);
VALA_EXTERN void unity_applications_lens_purchase_info_helper_app_info_destroy (UnityApplicationsLensPurchaseInfoHelperAppInfo* self);
G_DEFINE_AUTO_CLEANUP_CLEAR_FUNC (UnityApplicationsLensPurchaseInfoHelperAppInfo, unity_applications_lens_purchase_info_helper_app_info_destroy)
VALA_EXTERN UnityApplicationsLensPurchaseInfoHelper* unity_applications_lens_purchase_info_helper_new (void);
VALA_EXTERN UnityApplicationsLensPurchaseInfoHelper* unity_applications_lens_purchase_info_helper_construct (GType object_type);
static void _g_free0_ (gpointer var);
static void _unity_applications_lens_purchase_info_helper_app_info_free0_ (gpointer var);
VALA_EXTERN void unity_applications_lens_purchase_info_helper_from_pkgresults (UnityApplicationsLensPurchaseInfoHelper* self,
                                                                   UnityPackageSearchResult* results);
static void unity_applications_lens_purchase_info_helper_from_pkgresult (UnityApplicationsLensPurchaseInfoHelper* self,
                                                                  UnityPackageInfo* pkg,
                                                                  UnityApplicationsLensPurchaseInfoHelperAppInfo* result);
VALA_EXTERN GType unity_applications_lens_software_center_data_app_info_get_type (void) G_GNUC_CONST ;
VALA_EXTERN UnityApplicationsLensSoftwareCenterDataAppInfo* unity_applications_lens_software_center_data_app_info_dup (const UnityApplicationsLensSoftwareCenterDataAppInfo* self);
VALA_EXTERN void unity_applications_lens_software_center_data_app_info_free (UnityApplicationsLensSoftwareCenterDataAppInfo* self);
VALA_EXTERN void unity_applications_lens_software_center_data_app_info_copy (const UnityApplicationsLensSoftwareCenterDataAppInfo* self,
                                                                 UnityApplicationsLensSoftwareCenterDataAppInfo* dest);
VALA_EXTERN void unity_applications_lens_software_center_data_app_info_destroy (UnityApplicationsLensSoftwareCenterDataAppInfo* self);
G_DEFINE_AUTO_CLEANUP_CLEAR_FUNC (UnityApplicationsLensSoftwareCenterDataAppInfo, unity_applications_lens_software_center_data_app_info_destroy)
VALA_EXTERN GSList* unity_applications_lens_purchase_info_helper_create_pkgsearch_query (UnityApplicationsLensPurchaseInfoHelper* self,
                                                                             UnityApplicationsLensSoftwareCenterDataAppInfo** results,
                                                                             gint results_length1);
VALA_EXTERN UnityApplicationsLensPurchaseInfoHelperAppInfo* unity_applications_lens_purchase_info_helper_find (UnityApplicationsLensPurchaseInfoHelper* self,
                                                                                                   const gchar* application_name,
                                                                                                   const gchar* package_name);
static void unity_applications_lens_purchase_info_helper_finalize (UnityApplicationsLensPurchaseInfoHelper * obj);
static GType unity_applications_lens_purchase_info_helper_get_type_once (void);

static inline gpointer
unity_applications_lens_purchase_info_helper_get_instance_private (UnityApplicationsLensPurchaseInfoHelper* self)
{
	return G_STRUCT_MEMBER_P (self, UnityApplicationsLensPurchaseInfoHelper_private_offset);
}

static void
_g_free0_ (gpointer var)
{
	var = (g_free (var), NULL);
}

static void
_unity_applications_lens_purchase_info_helper_app_info_free0_ (gpointer var)
{
	(var == NULL) ? NULL : (var = (unity_applications_lens_purchase_info_helper_app_info_free (var), NULL));
}

UnityApplicationsLensPurchaseInfoHelper*
unity_applications_lens_purchase_info_helper_construct (GType object_type)
{
	UnityApplicationsLensPurchaseInfoHelper* self = NULL;
	GHashFunc _tmp0_;
	GEqualFunc _tmp1_;
	GHashTable* _tmp2_;
	self = (UnityApplicationsLensPurchaseInfoHelper*) g_type_create_instance (object_type);
	_tmp0_ = g_str_hash;
	_tmp1_ = g_str_equal;
	_tmp2_ = g_hash_table_new_full (_tmp0_, _tmp1_, _g_free0_, _unity_applications_lens_purchase_info_helper_app_info_free0_);
	_g_hash_table_unref0 (self->priv->data);
	self->priv->data = _tmp2_;
	return self;
}

UnityApplicationsLensPurchaseInfoHelper*
unity_applications_lens_purchase_info_helper_new (void)
{
	return unity_applications_lens_purchase_info_helper_construct (UNITY_APPLICATIONS_LENS_TYPE_PURCHASE_INFO_HELPER);
}

static gpointer
_unity_applications_lens_purchase_info_helper_app_info_dup0 (gpointer self)
{
	return self ? unity_applications_lens_purchase_info_helper_app_info_dup (self) : NULL;
}

void
unity_applications_lens_purchase_info_helper_from_pkgresults (UnityApplicationsLensPurchaseInfoHelper* self,
                                                              UnityPackageSearchResult* results)
{
	GSList* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (results != NULL);
	_tmp0_ = results->results;
	{
		GSList* pkg_collection = NULL;
		GSList* pkg_it = NULL;
		pkg_collection = _tmp0_;
		for (pkg_it = pkg_collection; pkg_it != NULL; pkg_it = pkg_it->next) {
			UnityPackageInfo* pkg = NULL;
			pkg = (UnityPackageInfo*) pkg_it->data;
			{
				UnityApplicationsLensPurchaseInfoHelperAppInfo app_info = {0};
				UnityPackageInfo* _tmp1_;
				UnityApplicationsLensPurchaseInfoHelperAppInfo _tmp2_ = {0};
				GHashTable* _tmp3_;
				UnityPackageInfo* _tmp4_;
				const gchar* _tmp5_;
				gchar* _tmp6_;
				gchar* _tmp7_;
				UnityPackageInfo* _tmp8_;
				const gchar* _tmp9_;
				gchar* _tmp10_;
				UnityApplicationsLensPurchaseInfoHelperAppInfo _tmp11_;
				UnityApplicationsLensPurchaseInfoHelperAppInfo _tmp12_;
				UnityApplicationsLensPurchaseInfoHelperAppInfo* _tmp13_;
				_tmp1_ = pkg;
				unity_applications_lens_purchase_info_helper_from_pkgresult (self, _tmp1_, &_tmp2_);
				app_info = _tmp2_;
				_tmp3_ = self->priv->data;
				_tmp4_ = pkg;
				_tmp5_ = _tmp4_->application_name;
				_tmp6_ = g_strconcat (_tmp5_, "/", NULL);
				_tmp7_ = _tmp6_;
				_tmp8_ = pkg;
				_tmp9_ = _tmp8_->package_name;
				_tmp10_ = g_strconcat (_tmp7_, _tmp9_, NULL);
				_tmp11_ = app_info;
				_tmp12_ = _tmp11_;
				_tmp13_ = _unity_applications_lens_purchase_info_helper_app_info_dup0 (&_tmp12_);
				g_hash_table_insert (_tmp3_, _tmp10_, _tmp13_);
				_g_free0 (_tmp7_);
				unity_applications_lens_purchase_info_helper_app_info_destroy (&app_info);
			}
		}
	}
}

static void
unity_applications_lens_purchase_info_helper_from_pkgresult (UnityApplicationsLensPurchaseInfoHelper* self,
                                                             UnityPackageInfo* pkg,
                                                             UnityApplicationsLensPurchaseInfoHelperAppInfo* result)
{
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	const gchar* _tmp2_;
	gboolean purchased = FALSE;
	UnityApplicationsLensPurchaseInfoHelperAppInfo app_info = {0};
	const gchar* _tmp4_;
	gchar* _tmp5_;
	UnityApplicationsLensPurchaseInfoHelperAppInfo _tmp6_ = {0};
	g_return_if_fail (self != NULL);
	g_return_if_fail (pkg != NULL);
	_tmp2_ = pkg->price;
	if (_tmp2_ != NULL) {
		const gchar* _tmp3_;
		_tmp3_ = pkg->price;
		_tmp1_ = g_strcmp0 (_tmp3_, "") != 0;
	} else {
		_tmp1_ = FALSE;
	}
	if (_tmp1_) {
		_tmp0_ = !pkg->needs_purchase;
	} else {
		_tmp0_ = FALSE;
	}
	purchased = _tmp0_;
	_tmp4_ = pkg->price;
	_tmp5_ = g_strdup (_tmp4_);
	memset (&_tmp6_, 0, sizeof (UnityApplicationsLensPurchaseInfoHelperAppInfo));
	_g_free0 (_tmp6_.formatted_price);
	_tmp6_.formatted_price = _tmp5_;
	_tmp6_.paid = purchased;
	app_info = _tmp6_;
	*result = app_info;
	return;
}

static gpointer
_unity_applications_lens_software_center_data_app_info_dup0 (gpointer self)
{
	return self ? unity_applications_lens_software_center_data_app_info_dup (self) : NULL;
}

GSList*
unity_applications_lens_purchase_info_helper_create_pkgsearch_query (UnityApplicationsLensPurchaseInfoHelper* self,
                                                                     UnityApplicationsLensSoftwareCenterDataAppInfo** results,
                                                                     gint results_length1)
{
	GSList* params = NULL;
	GSList* result;
	g_return_val_if_fail (self != NULL, NULL);
	params = NULL;
	{
		UnityApplicationsLensSoftwareCenterDataAppInfo** res_collection = NULL;
		gint res_collection_length1 = 0;
		gint _res_collection_size_ = 0;
		gint res_it = 0;
		res_collection = results;
		res_collection_length1 = results_length1;
		for (res_it = 0; res_it < res_collection_length1; res_it = res_it + 1) {
			UnityApplicationsLensSoftwareCenterDataAppInfo* _tmp0_;
			UnityApplicationsLensSoftwareCenterDataAppInfo* res = NULL;
			_tmp0_ = _unity_applications_lens_software_center_data_app_info_dup0 (res_collection[res_it]);
			res = _tmp0_;
			{
				UnityApplicationsLensSoftwareCenterDataAppInfo* _tmp1_;
				const gchar* _tmp2_;
				gchar* _tmp3_;
				UnityApplicationsLensSoftwareCenterDataAppInfo* _tmp4_;
				const gchar* _tmp5_;
				gchar* _tmp6_;
				_tmp1_ = res;
				_tmp2_ = (*_tmp1_).application_name;
				_tmp3_ = g_strdup (_tmp2_);
				params = g_slist_append (params, _tmp3_);
				_tmp4_ = res;
				_tmp5_ = (*_tmp4_).package_name;
				_tmp6_ = g_strdup (_tmp5_);
				params = g_slist_append (params, _tmp6_);
				_unity_applications_lens_software_center_data_app_info_free0 (res);
			}
		}
	}
	result = params;
	return result;
}

UnityApplicationsLensPurchaseInfoHelperAppInfo*
unity_applications_lens_purchase_info_helper_find (UnityApplicationsLensPurchaseInfoHelper* self,
                                                   const gchar* application_name,
                                                   const gchar* package_name)
{
	gchar* key = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	GHashTable* _tmp4_;
	const gchar* _tmp5_;
	UnityApplicationsLensPurchaseInfoHelperAppInfo* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (application_name != NULL, NULL);
	g_return_val_if_fail (package_name != NULL, NULL);
	_tmp0_ = g_strconcat (application_name, "/", NULL);
	_tmp1_ = _tmp0_;
	_tmp2_ = g_strconcat (_tmp1_, package_name, NULL);
	_tmp3_ = _tmp2_;
	_g_free0 (_tmp1_);
	key = _tmp3_;
	_tmp4_ = self->priv->data;
	_tmp5_ = key;
	if (g_hash_table_contains (_tmp4_, _tmp5_)) {
		GHashTable* _tmp6_;
		const gchar* _tmp7_;
		gconstpointer _tmp8_;
		UnityApplicationsLensPurchaseInfoHelperAppInfo* _tmp9_;
		_tmp6_ = self->priv->data;
		_tmp7_ = key;
		_tmp8_ = g_hash_table_lookup (_tmp6_, _tmp7_);
		_tmp9_ = _unity_applications_lens_purchase_info_helper_app_info_dup0 ((UnityApplicationsLensPurchaseInfoHelperAppInfo*) _tmp8_);
		result = _tmp9_;
		_g_free0 (key);
		return result;
	}
	result = NULL;
	_g_free0 (key);
	return result;
}

void
unity_applications_lens_purchase_info_helper_app_info_copy (const UnityApplicationsLensPurchaseInfoHelperAppInfo* self,
                                                            UnityApplicationsLensPurchaseInfoHelperAppInfo* dest)
{
	const gchar* _tmp0_;
	gchar* _tmp1_;
	_tmp0_ = (*self).formatted_price;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 ((*dest).formatted_price);
	(*dest).formatted_price = _tmp1_;
	(*dest).paid = (*self).paid;
}

void
unity_applications_lens_purchase_info_helper_app_info_destroy (UnityApplicationsLensPurchaseInfoHelperAppInfo* self)
{
	_g_free0 ((*self).formatted_price);
}

UnityApplicationsLensPurchaseInfoHelperAppInfo*
unity_applications_lens_purchase_info_helper_app_info_dup (const UnityApplicationsLensPurchaseInfoHelperAppInfo* self)
{
	UnityApplicationsLensPurchaseInfoHelperAppInfo* dup;
	dup = g_new0 (UnityApplicationsLensPurchaseInfoHelperAppInfo, 1);
	unity_applications_lens_purchase_info_helper_app_info_copy (self, dup);
	return dup;
}

void
unity_applications_lens_purchase_info_helper_app_info_free (UnityApplicationsLensPurchaseInfoHelperAppInfo* self)
{
	unity_applications_lens_purchase_info_helper_app_info_destroy (self);
	g_free (self);
}

static GType
unity_applications_lens_purchase_info_helper_app_info_get_type_once (void)
{
	GType unity_applications_lens_purchase_info_helper_app_info_type_id;
	unity_applications_lens_purchase_info_helper_app_info_type_id = g_boxed_type_register_static ("UnityApplicationsLensPurchaseInfoHelperAppInfo", (GBoxedCopyFunc) unity_applications_lens_purchase_info_helper_app_info_dup, (GBoxedFreeFunc) unity_applications_lens_purchase_info_helper_app_info_free);
	return unity_applications_lens_purchase_info_helper_app_info_type_id;
}

GType
unity_applications_lens_purchase_info_helper_app_info_get_type (void)
{
	static volatile gsize unity_applications_lens_purchase_info_helper_app_info_type_id__once = 0;
	if (g_once_init_enter (&unity_applications_lens_purchase_info_helper_app_info_type_id__once)) {
		GType unity_applications_lens_purchase_info_helper_app_info_type_id;
		unity_applications_lens_purchase_info_helper_app_info_type_id = unity_applications_lens_purchase_info_helper_app_info_get_type_once ();
		g_once_init_leave (&unity_applications_lens_purchase_info_helper_app_info_type_id__once, unity_applications_lens_purchase_info_helper_app_info_type_id);
	}
	return unity_applications_lens_purchase_info_helper_app_info_type_id__once;
}

static void
unity_applications_lens_value_purchase_info_helper_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}

static void
unity_applications_lens_value_purchase_info_helper_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		unity_applications_lens_purchase_info_helper_unref (value->data[0].v_pointer);
	}
}

static void
unity_applications_lens_value_purchase_info_helper_copy_value (const GValue* src_value,
                                                               GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = unity_applications_lens_purchase_info_helper_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}

static gpointer
unity_applications_lens_value_purchase_info_helper_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}

static gchar*
unity_applications_lens_value_purchase_info_helper_collect_value (GValue* value,
                                                                  guint n_collect_values,
                                                                  GTypeCValue* collect_values,
                                                                  guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		UnityApplicationsLensPurchaseInfoHelper * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = unity_applications_lens_purchase_info_helper_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}

static gchar*
unity_applications_lens_value_purchase_info_helper_lcopy_value (const GValue* value,
                                                                guint n_collect_values,
                                                                GTypeCValue* collect_values,
                                                                guint collect_flags)
{
	UnityApplicationsLensPurchaseInfoHelper ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = unity_applications_lens_purchase_info_helper_ref (value->data[0].v_pointer);
	}
	return NULL;
}

GParamSpec*
unity_applications_lens_param_spec_purchase_info_helper (const gchar* name,
                                                         const gchar* nick,
                                                         const gchar* blurb,
                                                         GType object_type,
                                                         GParamFlags flags)
{
	UnityApplicationsLensParamSpecPurchaseInfoHelper* spec;
	g_return_val_if_fail (g_type_is_a (object_type, UNITY_APPLICATIONS_LENS_TYPE_PURCHASE_INFO_HELPER), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}

gpointer
unity_applications_lens_value_get_purchase_info_helper (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, UNITY_APPLICATIONS_LENS_TYPE_PURCHASE_INFO_HELPER), NULL);
	return value->data[0].v_pointer;
}

void
unity_applications_lens_value_set_purchase_info_helper (GValue* value,
                                                        gpointer v_object)
{
	UnityApplicationsLensPurchaseInfoHelper * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, UNITY_APPLICATIONS_LENS_TYPE_PURCHASE_INFO_HELPER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, UNITY_APPLICATIONS_LENS_TYPE_PURCHASE_INFO_HELPER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		unity_applications_lens_purchase_info_helper_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		unity_applications_lens_purchase_info_helper_unref (old);
	}
}

void
unity_applications_lens_value_take_purchase_info_helper (GValue* value,
                                                         gpointer v_object)
{
	UnityApplicationsLensPurchaseInfoHelper * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, UNITY_APPLICATIONS_LENS_TYPE_PURCHASE_INFO_HELPER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, UNITY_APPLICATIONS_LENS_TYPE_PURCHASE_INFO_HELPER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		unity_applications_lens_purchase_info_helper_unref (old);
	}
}

static void
unity_applications_lens_purchase_info_helper_class_init (UnityApplicationsLensPurchaseInfoHelperClass * klass,
                                                         gpointer klass_data)
{
	unity_applications_lens_purchase_info_helper_parent_class = g_type_class_peek_parent (klass);
	((UnityApplicationsLensPurchaseInfoHelperClass *) klass)->finalize = unity_applications_lens_purchase_info_helper_finalize;
	g_type_class_adjust_private_offset (klass, &UnityApplicationsLensPurchaseInfoHelper_private_offset);
}

static void
unity_applications_lens_purchase_info_helper_instance_init (UnityApplicationsLensPurchaseInfoHelper * self,
                                                            gpointer klass)
{
	self->priv = unity_applications_lens_purchase_info_helper_get_instance_private (self);
	self->ref_count = 1;
}

static void
unity_applications_lens_purchase_info_helper_finalize (UnityApplicationsLensPurchaseInfoHelper * obj)
{
	UnityApplicationsLensPurchaseInfoHelper * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, UNITY_APPLICATIONS_LENS_TYPE_PURCHASE_INFO_HELPER, UnityApplicationsLensPurchaseInfoHelper);
	g_signal_handlers_destroy (self);
	_g_hash_table_unref0 (self->priv->data);
}

static GType
unity_applications_lens_purchase_info_helper_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { unity_applications_lens_value_purchase_info_helper_init, unity_applications_lens_value_purchase_info_helper_free_value, unity_applications_lens_value_purchase_info_helper_copy_value, unity_applications_lens_value_purchase_info_helper_peek_pointer, "p", unity_applications_lens_value_purchase_info_helper_collect_value, "p", unity_applications_lens_value_purchase_info_helper_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (UnityApplicationsLensPurchaseInfoHelperClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) unity_applications_lens_purchase_info_helper_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (UnityApplicationsLensPurchaseInfoHelper), 0, (GInstanceInitFunc) unity_applications_lens_purchase_info_helper_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType unity_applications_lens_purchase_info_helper_type_id;
	unity_applications_lens_purchase_info_helper_type_id = g_type_register_fundamental (g_type_fundamental_next (), "UnityApplicationsLensPurchaseInfoHelper", &g_define_type_info, &g_define_type_fundamental_info, 0);
	UnityApplicationsLensPurchaseInfoHelper_private_offset = g_type_add_instance_private (unity_applications_lens_purchase_info_helper_type_id, sizeof (UnityApplicationsLensPurchaseInfoHelperPrivate));
	return unity_applications_lens_purchase_info_helper_type_id;
}

GType
unity_applications_lens_purchase_info_helper_get_type (void)
{
	static volatile gsize unity_applications_lens_purchase_info_helper_type_id__once = 0;
	if (g_once_init_enter (&unity_applications_lens_purchase_info_helper_type_id__once)) {
		GType unity_applications_lens_purchase_info_helper_type_id;
		unity_applications_lens_purchase_info_helper_type_id = unity_applications_lens_purchase_info_helper_get_type_once ();
		g_once_init_leave (&unity_applications_lens_purchase_info_helper_type_id__once, unity_applications_lens_purchase_info_helper_type_id);
	}
	return unity_applications_lens_purchase_info_helper_type_id__once;
}

gpointer
unity_applications_lens_purchase_info_helper_ref (gpointer instance)
{
	UnityApplicationsLensPurchaseInfoHelper * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}

void
unity_applications_lens_purchase_info_helper_unref (gpointer instance)
{
	UnityApplicationsLensPurchaseInfoHelper * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		UNITY_APPLICATIONS_LENS_PURCHASE_INFO_HELPER_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}

