/* settings.c generated by valac 0.56.19, the Vala compiler
 * generated from settings.vala, do not modify */

/* -*- Mode: Vala; indent-tabs-mode: nil; tab-width: 4 -*-
 *
 * Copyright (C) 2011,2012 Canonical Ltd
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Authors: Robert Ancell <robert.ancell@canonical.com>
 *          Michael Terry <michael.terry@canonical.com>
 */

#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gio/gio.h>
#include <float.h>
#include <math.h>
#include <gobject/gvaluecollector.h>

#define UG_SETTINGS_KEY_BACKGROUND "background"
#define UG_SETTINGS_KEY_BACKGROUND_COLOR "background-color"
#define UG_SETTINGS_KEY_DRAW_USER_BACKGROUNDS "draw-user-backgrounds"
#define UG_SETTINGS_KEY_DRAW_GRID "draw-grid"
#define UG_SETTINGS_KEY_SHOW_HOSTNAME "show-hostname"
#define UG_SETTINGS_KEY_LOGO "logo"
#define UG_SETTINGS_KEY_BACKGROUND_LOGO "background-logo"
#define UG_SETTINGS_KEY_THEME_NAME "theme-name"
#define UG_SETTINGS_KEY_ICON_THEME_NAME "icon-theme-name"
#define UG_SETTINGS_KEY_FONT_NAME "font-name"
#define UG_SETTINGS_KEY_XFT_ANTIALIAS "xft-antialias"
#define UG_SETTINGS_KEY_XFT_DPI "xft-dpi"
#define UG_SETTINGS_KEY_XFT_HINTSTYLE "xft-hintstyle"
#define UG_SETTINGS_KEY_XFT_RGBA "xft-rgba"
#define UG_SETTINGS_KEY_ONSCREEN_KEYBOARD "onscreen-keyboard"
#define UG_SETTINGS_KEY_HIGH_CONTRAST "high-contrast"
#define UG_SETTINGS_KEY_SCREEN_READER "screen-reader"
#define UG_SETTINGS_KEY_PLAY_READY_SOUND "play-ready-sound"
#define UG_SETTINGS_KEY_INDICATORS "indicators"
#define UG_SETTINGS_KEY_HIDDEN_USERS "hidden-users"
#define UG_SETTINGS_KEY_GROUP_FILTER "group-filter"
#define UG_SETTINGS_KEY_IDLE_TIMEOUT "idle-timeout"
#define UG_SETTINGS_SCHEMA "com.canonical.unity-greeter"
#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define TYPE_UG_SETTINGS (ug_settings_get_type ())
#define UG_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_UG_SETTINGS, UGSettings))
#define UG_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_UG_SETTINGS, UGSettingsClass))
#define IS_UG_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_UG_SETTINGS))
#define IS_UG_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_UG_SETTINGS))
#define UG_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_UG_SETTINGS, UGSettingsClass))

typedef struct _UGSettings UGSettings;
typedef struct _UGSettingsClass UGSettingsClass;
typedef struct _UGSettingsPrivate UGSettingsPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _ParamSpecUGSettings ParamSpecUGSettings;

struct _UGSettings {
	GTypeInstance parent_instance;
	volatile int ref_count;
	UGSettingsPrivate * priv;
};

struct _UGSettingsClass {
	GTypeClass parent_class;
	void (*finalize) (UGSettings *self);
};

struct _ParamSpecUGSettings {
	GParamSpec parent_instance;
};

static gpointer ug_settings_parent_class = NULL;

VALA_EXTERN gpointer ug_settings_ref (gpointer instance);
VALA_EXTERN void ug_settings_unref (gpointer instance);
VALA_EXTERN GParamSpec* param_spec_ug_settings (const gchar* name,
                                    const gchar* nick,
                                    const gchar* blurb,
                                    GType object_type,
                                    GParamFlags flags);
VALA_EXTERN void value_set_ug_settings (GValue* value,
                            gpointer v_object);
VALA_EXTERN void value_take_ug_settings (GValue* value,
                             gpointer v_object);
VALA_EXTERN gpointer value_get_ug_settings (const GValue* value);
VALA_EXTERN GType ug_settings_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (UGSettings, ug_settings_unref)
VALA_EXTERN gboolean ug_settings_get_boolean (const gchar* key);
VALA_EXTERN gboolean ug_settings_safe_get_boolean (const gchar* key,
                                       gboolean _default_);
VALA_EXTERN gint ug_settings_get_integer (const gchar* key);
VALA_EXTERN gdouble ug_settings_get_double (const gchar* key);
VALA_EXTERN gchar* ug_settings_get_string (const gchar* key);
VALA_EXTERN gboolean ug_settings_set_boolean (const gchar* key,
                                  gboolean value);
VALA_EXTERN gchar** ug_settings_get_strv (const gchar* key,
                              gint* result_length1);
VALA_EXTERN gboolean ug_settings_set_strv (const gchar* key,
                               gchar** value,
                               gint value_length1);
VALA_EXTERN UGSettings* ug_settings_new (void);
VALA_EXTERN UGSettings* ug_settings_construct (GType object_type);
static void ug_settings_finalize (UGSettings * obj);
static GType ug_settings_get_type_once (void);
static void _vala_array_destroy (gpointer array,
                          gssize array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gssize array_length,
                       GDestroyNotify destroy_func);
static gssize _vala_array_length (gpointer array);
static inline gpointer _vala_memdup2 (gconstpointer mem,
                        gsize byte_size);

gboolean
ug_settings_get_boolean (const gchar* key)
{
	GSettings* gsettings = NULL;
	GSettings* _tmp0_;
	gboolean result;
#line 46 "settings.vala"
	g_return_val_if_fail (key != NULL, FALSE);
#line 48 "settings.vala"
	_tmp0_ = g_settings_new (UG_SETTINGS_SCHEMA);
#line 48 "settings.vala"
	gsettings = _tmp0_;
#line 49 "settings.vala"
	result = g_settings_get_boolean (gsettings, key);
#line 49 "settings.vala"
	_g_object_unref0 (gsettings);
#line 49 "settings.vala"
	return result;
#line 165 "settings.c"
}

gboolean
ug_settings_safe_get_boolean (const gchar* key,
                              gboolean _default_)
{
	GSettings* gsettings = NULL;
	GSettings* _tmp0_;
	gchar** keys = NULL;
	GSettings* _tmp1_;
	gchar** _tmp2_;
	gchar** _tmp3_;
	gint keys_length1;
	gint _keys_size_;
	gchar** _tmp4_;
	gint _tmp4__length1;
	gboolean result;
#line 53 "settings.vala"
	g_return_val_if_fail (key != NULL, FALSE);
#line 55 "settings.vala"
	_tmp0_ = g_settings_new (UG_SETTINGS_SCHEMA);
#line 55 "settings.vala"
	gsettings = _tmp0_;
#line 56 "settings.vala"
	_tmp1_ = gsettings;
#line 56 "settings.vala"
	_tmp3_ = _tmp2_ = g_settings_list_keys (_tmp1_);
#line 56 "settings.vala"
	keys = _tmp3_;
#line 56 "settings.vala"
	keys_length1 = _vala_array_length (_tmp2_);
#line 56 "settings.vala"
	_keys_size_ = keys_length1;
#line 57 "settings.vala"
	_tmp4_ = keys;
#line 57 "settings.vala"
	_tmp4__length1 = keys_length1;
#line 203 "settings.c"
	{
		gchar** k_collection = NULL;
		gint k_collection_length1 = 0;
		gint _k_collection_size_ = 0;
		gint k_it = 0;
#line 57 "settings.vala"
		k_collection = _tmp4_;
#line 57 "settings.vala"
		k_collection_length1 = _tmp4__length1;
#line 57 "settings.vala"
		for (k_it = 0; k_it < k_collection_length1; k_it = k_it + 1) {
#line 215 "settings.c"
			gchar* _tmp5_;
			gchar* k = NULL;
#line 57 "settings.vala"
			_tmp5_ = g_strdup (k_collection[k_it]);
#line 57 "settings.vala"
			k = _tmp5_;
#line 222 "settings.c"
			{
				const gchar* _tmp6_;
#line 58 "settings.vala"
				_tmp6_ = k;
#line 58 "settings.vala"
				if (g_strcmp0 (_tmp6_, key) == 0) {
#line 229 "settings.c"
					GSettings* _tmp7_;
#line 59 "settings.vala"
					_tmp7_ = gsettings;
#line 59 "settings.vala"
					result = g_settings_get_boolean (_tmp7_, key);
#line 59 "settings.vala"
					_g_free0 (k);
#line 59 "settings.vala"
					keys = (_vala_array_free (keys, keys_length1, (GDestroyNotify) g_free), NULL);
#line 59 "settings.vala"
					_g_object_unref0 (gsettings);
#line 59 "settings.vala"
					return result;
#line 243 "settings.c"
				}
#line 57 "settings.vala"
				_g_free0 (k);
#line 247 "settings.c"
			}
		}
	}
#line 62 "settings.vala"
	result = _default_;
#line 62 "settings.vala"
	keys = (_vala_array_free (keys, keys_length1, (GDestroyNotify) g_free), NULL);
#line 62 "settings.vala"
	_g_object_unref0 (gsettings);
#line 62 "settings.vala"
	return result;
#line 259 "settings.c"
}

gint
ug_settings_get_integer (const gchar* key)
{
	GSettings* gsettings = NULL;
	GSettings* _tmp0_;
	gint result;
#line 65 "settings.vala"
	g_return_val_if_fail (key != NULL, -1);
#line 67 "settings.vala"
	_tmp0_ = g_settings_new (UG_SETTINGS_SCHEMA);
#line 67 "settings.vala"
	gsettings = _tmp0_;
#line 68 "settings.vala"
	result = g_settings_get_int (gsettings, key);
#line 68 "settings.vala"
	_g_object_unref0 (gsettings);
#line 68 "settings.vala"
	return result;
#line 280 "settings.c"
}

gdouble
ug_settings_get_double (const gchar* key)
{
	GSettings* gsettings = NULL;
	GSettings* _tmp0_;
	gdouble result;
#line 71 "settings.vala"
	g_return_val_if_fail (key != NULL, -1.0);
#line 73 "settings.vala"
	_tmp0_ = g_settings_new (UG_SETTINGS_SCHEMA);
#line 73 "settings.vala"
	gsettings = _tmp0_;
#line 74 "settings.vala"
	result = g_settings_get_double (gsettings, key);
#line 74 "settings.vala"
	_g_object_unref0 (gsettings);
#line 74 "settings.vala"
	return result;
#line 301 "settings.c"
}

gchar*
ug_settings_get_string (const gchar* key)
{
	GSettings* gsettings = NULL;
	GSettings* _tmp0_;
	gchar* _tmp1_;
	gchar* result;
#line 77 "settings.vala"
	g_return_val_if_fail (key != NULL, NULL);
#line 79 "settings.vala"
	_tmp0_ = g_settings_new (UG_SETTINGS_SCHEMA);
#line 79 "settings.vala"
	gsettings = _tmp0_;
#line 80 "settings.vala"
	_tmp1_ = g_settings_get_string (gsettings, key);
#line 80 "settings.vala"
	result = _tmp1_;
#line 80 "settings.vala"
	_g_object_unref0 (gsettings);
#line 80 "settings.vala"
	return result;
#line 325 "settings.c"
}

gboolean
ug_settings_set_boolean (const gchar* key,
                         gboolean value)
{
	GSettings* gsettings = NULL;
	GSettings* _tmp0_;
	gboolean result;
#line 83 "settings.vala"
	g_return_val_if_fail (key != NULL, FALSE);
#line 85 "settings.vala"
	_tmp0_ = g_settings_new (UG_SETTINGS_SCHEMA);
#line 85 "settings.vala"
	gsettings = _tmp0_;
#line 86 "settings.vala"
	result = g_settings_set_boolean (gsettings, key, value);
#line 86 "settings.vala"
	_g_object_unref0 (gsettings);
#line 86 "settings.vala"
	return result;
#line 347 "settings.c"
}

gchar**
ug_settings_get_strv (const gchar* key,
                      gint* result_length1)
{
	GSettings* gsettings = NULL;
	GSettings* _tmp0_;
	gchar** _tmp1_;
	gchar** _tmp2_;
	gchar** _tmp3_;
	gint _tmp3__length1;
	gchar** result;
#line 89 "settings.vala"
	g_return_val_if_fail (key != NULL, NULL);
#line 91 "settings.vala"
	_tmp0_ = g_settings_new (UG_SETTINGS_SCHEMA);
#line 91 "settings.vala"
	gsettings = _tmp0_;
#line 92 "settings.vala"
	_tmp2_ = _tmp1_ = g_settings_get_strv (gsettings, key);
#line 92 "settings.vala"
	_tmp3_ = _tmp2_;
#line 92 "settings.vala"
	_tmp3__length1 = _vala_array_length (_tmp1_);
#line 92 "settings.vala"
	if (result_length1) {
#line 92 "settings.vala"
		*result_length1 = _tmp3__length1;
#line 377 "settings.c"
	}
#line 92 "settings.vala"
	result = _tmp3_;
#line 92 "settings.vala"
	_g_object_unref0 (gsettings);
#line 92 "settings.vala"
	return result;
#line 385 "settings.c"
}

gboolean
ug_settings_set_strv (const gchar* key,
                      gchar** value,
                      gint value_length1)
{
	GSettings* gsettings = NULL;
	GSettings* _tmp0_;
	gboolean result;
#line 95 "settings.vala"
	g_return_val_if_fail (key != NULL, FALSE);
#line 97 "settings.vala"
	_tmp0_ = g_settings_new (UG_SETTINGS_SCHEMA);
#line 97 "settings.vala"
	gsettings = _tmp0_;
#line 98 "settings.vala"
	result = g_settings_set_strv (gsettings, key, value);
#line 98 "settings.vala"
	_g_object_unref0 (gsettings);
#line 98 "settings.vala"
	return result;
#line 408 "settings.c"
}

UGSettings*
ug_settings_construct (GType object_type)
{
	UGSettings* self = NULL;
#line 21 "settings.vala"
	self = (UGSettings*) g_type_create_instance (object_type);
#line 21 "settings.vala"
	return self;
#line 419 "settings.c"
}

UGSettings*
ug_settings_new (void)
{
#line 21 "settings.vala"
	return ug_settings_construct (TYPE_UG_SETTINGS);
#line 427 "settings.c"
}

static void
value_ug_settings_init (GValue* value)
{
#line 21 "settings.vala"
	value->data[0].v_pointer = NULL;
#line 435 "settings.c"
}

static void
value_ug_settings_free_value (GValue* value)
{
#line 21 "settings.vala"
	if (value->data[0].v_pointer) {
#line 21 "settings.vala"
		ug_settings_unref (value->data[0].v_pointer);
#line 445 "settings.c"
	}
}

static void
value_ug_settings_copy_value (const GValue* src_value,
                              GValue* dest_value)
{
#line 21 "settings.vala"
	if (src_value->data[0].v_pointer) {
#line 21 "settings.vala"
		dest_value->data[0].v_pointer = ug_settings_ref (src_value->data[0].v_pointer);
#line 457 "settings.c"
	} else {
#line 21 "settings.vala"
		dest_value->data[0].v_pointer = NULL;
#line 461 "settings.c"
	}
}

static gpointer
value_ug_settings_peek_pointer (const GValue* value)
{
#line 21 "settings.vala"
	return value->data[0].v_pointer;
#line 470 "settings.c"
}

static gchar*
value_ug_settings_collect_value (GValue* value,
                                 guint n_collect_values,
                                 GTypeCValue* collect_values,
                                 guint collect_flags)
{
#line 21 "settings.vala"
	if (collect_values[0].v_pointer) {
#line 481 "settings.c"
		UGSettings * object;
		object = collect_values[0].v_pointer;
#line 21 "settings.vala"
		if (object->parent_instance.g_class == NULL) {
#line 21 "settings.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 488 "settings.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 21 "settings.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 492 "settings.c"
		}
#line 21 "settings.vala"
		value->data[0].v_pointer = ug_settings_ref (object);
#line 496 "settings.c"
	} else {
#line 21 "settings.vala"
		value->data[0].v_pointer = NULL;
#line 500 "settings.c"
	}
#line 21 "settings.vala"
	return NULL;
#line 504 "settings.c"
}

static gchar*
value_ug_settings_lcopy_value (const GValue* value,
                               guint n_collect_values,
                               GTypeCValue* collect_values,
                               guint collect_flags)
{
	UGSettings ** object_p;
	object_p = collect_values[0].v_pointer;
#line 21 "settings.vala"
	if (!object_p) {
#line 21 "settings.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 519 "settings.c"
	}
#line 21 "settings.vala"
	if (!value->data[0].v_pointer) {
#line 21 "settings.vala"
		*object_p = NULL;
#line 525 "settings.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 21 "settings.vala"
		*object_p = value->data[0].v_pointer;
#line 529 "settings.c"
	} else {
#line 21 "settings.vala"
		*object_p = ug_settings_ref (value->data[0].v_pointer);
#line 533 "settings.c"
	}
#line 21 "settings.vala"
	return NULL;
#line 537 "settings.c"
}

GParamSpec*
param_spec_ug_settings (const gchar* name,
                        const gchar* nick,
                        const gchar* blurb,
                        GType object_type,
                        GParamFlags flags)
{
	ParamSpecUGSettings* spec;
#line 21 "settings.vala"
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_UG_SETTINGS), NULL);
#line 21 "settings.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 21 "settings.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 21 "settings.vala"
	return G_PARAM_SPEC (spec);
#line 556 "settings.c"
}

gpointer
value_get_ug_settings (const GValue* value)
{
#line 21 "settings.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_UG_SETTINGS), NULL);
#line 21 "settings.vala"
	return value->data[0].v_pointer;
#line 566 "settings.c"
}

void
value_set_ug_settings (GValue* value,
                       gpointer v_object)
{
	UGSettings * old;
#line 21 "settings.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_UG_SETTINGS));
#line 21 "settings.vala"
	old = value->data[0].v_pointer;
#line 21 "settings.vala"
	if (v_object) {
#line 21 "settings.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_UG_SETTINGS));
#line 21 "settings.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 21 "settings.vala"
		value->data[0].v_pointer = v_object;
#line 21 "settings.vala"
		ug_settings_ref (value->data[0].v_pointer);
#line 588 "settings.c"
	} else {
#line 21 "settings.vala"
		value->data[0].v_pointer = NULL;
#line 592 "settings.c"
	}
#line 21 "settings.vala"
	if (old) {
#line 21 "settings.vala"
		ug_settings_unref (old);
#line 598 "settings.c"
	}
}

void
value_take_ug_settings (GValue* value,
                        gpointer v_object)
{
	UGSettings * old;
#line 21 "settings.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_UG_SETTINGS));
#line 21 "settings.vala"
	old = value->data[0].v_pointer;
#line 21 "settings.vala"
	if (v_object) {
#line 21 "settings.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_UG_SETTINGS));
#line 21 "settings.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 21 "settings.vala"
		value->data[0].v_pointer = v_object;
#line 619 "settings.c"
	} else {
#line 21 "settings.vala"
		value->data[0].v_pointer = NULL;
#line 623 "settings.c"
	}
#line 21 "settings.vala"
	if (old) {
#line 21 "settings.vala"
		ug_settings_unref (old);
#line 629 "settings.c"
	}
}

static void
ug_settings_class_init (UGSettingsClass * klass,
                        gpointer klass_data)
{
#line 21 "settings.vala"
	ug_settings_parent_class = g_type_class_peek_parent (klass);
#line 21 "settings.vala"
	((UGSettingsClass *) klass)->finalize = ug_settings_finalize;
#line 641 "settings.c"
}

static void
ug_settings_instance_init (UGSettings * self,
                           gpointer klass)
{
#line 21 "settings.vala"
	self->ref_count = 1;
#line 650 "settings.c"
}

static void
ug_settings_finalize (UGSettings * obj)
{
	UGSettings * self;
#line 21 "settings.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_UG_SETTINGS, UGSettings);
#line 21 "settings.vala"
	g_signal_handlers_destroy (self);
#line 661 "settings.c"
}

static GType
ug_settings_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { value_ug_settings_init, value_ug_settings_free_value, value_ug_settings_copy_value, value_ug_settings_peek_pointer, "p", value_ug_settings_collect_value, "p", value_ug_settings_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (UGSettingsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) ug_settings_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (UGSettings), 0, (GInstanceInitFunc) ug_settings_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType ug_settings_type_id;
	ug_settings_type_id = g_type_register_fundamental (g_type_fundamental_next (), "UGSettings", &g_define_type_info, &g_define_type_fundamental_info, 0);
	return ug_settings_type_id;
}

GType
ug_settings_get_type (void)
{
	static volatile gsize ug_settings_type_id__once = 0;
	if (g_once_init_enter (&ug_settings_type_id__once)) {
		GType ug_settings_type_id;
		ug_settings_type_id = ug_settings_get_type_once ();
		g_once_init_leave (&ug_settings_type_id__once, ug_settings_type_id);
	}
	return ug_settings_type_id__once;
}

gpointer
ug_settings_ref (gpointer instance)
{
	UGSettings * self;
	self = instance;
#line 21 "settings.vala"
	g_atomic_int_inc (&self->ref_count);
#line 21 "settings.vala"
	return instance;
#line 696 "settings.c"
}

void
ug_settings_unref (gpointer instance)
{
	UGSettings * self;
	self = instance;
#line 21 "settings.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 21 "settings.vala"
		UG_SETTINGS_GET_CLASS (self)->finalize (self);
#line 21 "settings.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 710 "settings.c"
	}
}

static void
_vala_array_destroy (gpointer array,
                     gssize array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gssize i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gssize array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

static gssize
_vala_array_length (gpointer array)
{
	gssize length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}

static inline gpointer
_vala_memdup2 (gconstpointer mem,
               gsize byte_size)
{
	gpointer new_mem;
	if (mem && byte_size != 0) {
		new_mem = g_malloc (byte_size);
		memcpy (new_mem, mem, byte_size);
	} else {
		new_mem = NULL;
	}
	return new_mem;
}

